'use strict';
const {test:base,expect}=require('@playwright/test');
const {createHash}=require('node:crypto');
const {ownerLikeCreds,requireCreds,login,gotoTab,ALLOW_MUTATION,RUN_ID,readSeedReport}=require('../86chaos-full-audit/utils/audit-helpers.cjs');
const catalogHeader='sku,name,packSize,purchaseUnit,unitPrice,sourceUrl';
const salesHeader='date,item,quantity,sourceId,lineId';
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Chicago'});
const unique=info=>`QA${createHash('sha256').update(`${RUN_ID}|${info.project.name}|${info.title}`).digest('hex').slice(0,32).toUpperCase()}`;
// Each forecast probe owns a fresh target. Earlier schedule audits and the
// other browser project cannot satisfy its coverage before it is reviewed.
const test=base.extend({forecastFixture:async({},use,info)=>{
  requireDisposableWorkspace();
  const restaurantId=readSeedReport().restaurantId;
  const db=require('../../api/_firebase-project-admin').getAdminAppForProject('chaos-test-d1601',{requireCredentials:true}).firestore();
  const restaurant=await db.collection('restaurants').doc(restaurantId).get();
  expect(restaurant.data()).toMatchObject({qaOwned:true,qaRunId:RUN_ID});
  const id=unique(info),date=today(),ref=db.collection('scheduleCoverageTargets').doc(id);
  await ref.set({restaurantId,dayIndex:new Date(`${date}T12:00:00Z`).getUTCDay(),role:'Server',startTime:'00:07',endTime:info.title.includes('invalid time-window')?'00:07':'00:19',count:1,qaOwned:true,qaRunId:RUN_ID,createdBy:'86chaos-full-audit'});
  const shiftRefs=Array.from({length:50},(_,slot)=>db.collection('shifts').doc(`forecast_${encodeURIComponent(restaurantId)}_${encodeURIComponent(id)}_${date}_${slot}`));
  try{await use({id,date,shiftRefs,db});}finally{
    const current=await restaurant.ref.get();expect(current.data()).toMatchObject({qaOwned:true,qaRunId:RUN_ID});
    const snapshots=await db.getAll(...shiftRefs),batch=db.batch();
    for(const snapshot of snapshots)if(snapshot.exists){expect(snapshot.data()).toMatchObject({restaurantId,source:'demand_forecast_review',isPublished:false,publishState:'draft'});batch.delete(snapshot.ref);}
    batch.delete(ref);await batch.commit();
  }
}});
test.use({actionTimeout:30000,navigationTimeout:60000});
const forecastRow=(panel,fixture)=>panel.locator('article').filter({hasText:`${fixture.date} � Server`}).filter({hasText:'00:07�00:19'});
async function enter(page,tab){const account=ownerLikeCreds();requireCreds(account,'owner-like reliability account');await login(page,account.email,account.password);await gotoTab(page,tab,{settleMs:500});}
function requireDisposableWorkspace(){expect(ALLOW_MUTATION,'Reliability suite requires authorized testing mutations').toBe(true);expect(readSeedReport()?.ok,'Reliability suite requires a verified disposable QA seed').toBe(true);}
async function reloadTo(page,tab){await page.reload({waitUntil:'domcontentloaded'});await gotoTab(page,tab,{settleMs:500});}
async function catalog(page){await enter(page,'inventory');await page.getByRole('button',{name:/^(?:Open )?vendors$/i}).click();const panel=page.getByTestId('vendor-catalog-review');await expect(panel).toBeVisible();const vendor=panel.getByLabel('Catalog vendor');await expect.poll(()=>vendor.locator('option').count()).toBeGreaterThan(1);await vendor.selectOption(await vendor.locator('option').nth(1).getAttribute('value'));await expect(panel.getByRole('status')).toHaveCount(0);await expect(vendor).toBeEnabled();return panel;}
async function catalogPreview(panel,csv){await panel.getByLabel('Vendor catalog CSV').fill(csv);await panel.getByRole('button',{name:'Preview catalog evidence'}).click();}
async function sales(page){await enter(page,'today');const panel=page.getByTestId('item-sales-history-review');await panel.getByRole('button',{name:'Review item sales history'}).click();return panel;}
async function salesPreview(panel,csv){await panel.getByLabel('Item sales CSV').fill(csv);await panel.getByRole('button',{name:'Preview and match rows'}).click();}
const salesCsv=(id,quantity=2,item='QA Salmon BLT')=>`${salesHeader}\n${today()},${item},${quantity},${id},line-1`;
const catalogCsv=(id,name='QA Reliability Flour')=>`${catalogHeader}\n${id},${name},1/10 LB,CS,20,https://vendor.example/flour`;
async function history(page){await enter(page,'today');const panel=page.getByTestId('history-source-review');await expect(panel).toBeVisible();return panel;}
const historyPage=patch=>({ok:true,readOnly:true,source:'prep',data:[],scanned:1,undated:0,hasMore:false,nextCursor:'',truncated:false,window:{days:180},...patch});
async function historyRoute(page,handler){await page.route('**/api/operational-history',route=>route.request().postDataJSON()?.source==='prep'?handler(route):route.continue());}
async function policy(page){await enter(page,'today');const panel=page.getByTestId('attendance-policy-review');await expect(panel).toBeVisible();return panel;}
const policyWrite=page=>page.waitForResponse(r=>r.url().includes('/api/safe-write') && r.request().postDataJSON()?.action==='attendance-policy-approve');
async function forecast(page){await enter(page,'schedule');await page.getByRole('button',{name:'Open Copilot Tools',exact:true}).click();await page.getByRole('tab',{name:'Demand forecast',exact:true}).click();const panel=page.getByTestId('schedule-demand-forecast');await expect(panel).toBeVisible();return panel;}

test.describe('100 operational reliability: catalog',()=>{
  test.beforeEach(()=>{test.setTimeout(360000);requireDisposableWorkspace();});
  for(const [name,csv,error] of [
    ['missing required headers','sku,name\nA,Flour',/headers/],
    ['duplicate columns',`${catalogHeader},sku\nA,Flour,1 LB,CS,20,https://vendor.example/a,B`,/duplicate/],
    ['unfinished quoted field',`${catalogHeader}\nA,"unfinished`,/unfinished/],
    ['inconsistent row width',`${catalogHeader}\nA,Flour,1 LB`,/same columns/],
    ['over 100 catalog rows',`${catalogHeader}\n${Array.from({length:101},(_,i)=>`A${i},Flour,1 LB,CS,20,https://vendor.example/a`).join('\n')}`,/between 1 and 100/]
  ])test(`catalog rejects ${name}`,async({page})=>{const panel=await catalog(page);await catalogPreview(panel,csv);await expect(panel.getByRole('alert')).toContainText(error);await expect(panel.getByRole('button',{name:/Approve .*catalog rows/})).toHaveCount(0);});
  test('quoted catalog product names preserve commas in preview',async({page},info)=>{const panel=await catalog(page);await catalogPreview(panel,catalogCsv(unique(info),'"Flour, bread"'));await expect(panel).toContainText('Flour, bread · 1/10 LB');await expect(panel.getByRole('button',{name:'Approve 1 catalog rows'})).toBeEnabled();});
  test('editing CSV invalidates the prior catalog approval',async({page},info)=>{const panel=await catalog(page);await catalogPreview(panel,catalogCsv(unique(info)));await expect(panel.getByRole('button',{name:'Approve 1 catalog rows'})).toBeVisible();await panel.getByLabel('Vendor catalog CSV').fill(catalogCsv(unique(info),'Changed product'));await expect(panel.getByRole('button',{name:'Approve 1 catalog rows'})).toHaveCount(0);});
  test('approved catalog evidence persists after reloading the workspace',async({page},info)=>{const id=unique(info);let panel=await catalog(page);await catalogPreview(panel,catalogCsv(id));await panel.getByRole('button',{name:'Approve 1 catalog rows'}).click();await expect(panel.getByText(new RegExp(`${id} .* Active`))).toBeVisible();await reloadTo(page,'inventory');await page.getByRole('button',{name:/^(?:Open )?vendors$/i}).click();panel=page.getByTestId('vendor-catalog-review');const vendor=panel.getByLabel('Catalog vendor');await expect.poll(()=>vendor.locator('option').count()).toBeGreaterThan(1);await vendor.selectOption(await vendor.locator('option').nth(1).getAttribute('value'));await expect(panel.getByText(new RegExp(`${id} .* Active`))).toBeVisible();});
  test('catalog revocation requires confirmation and persists when confirmed',async({page},info)=>{const id=unique(info),panel=await catalog(page);await catalogPreview(panel,catalogCsv(id));await panel.getByRole('button',{name:'Approve 1 catalog rows'}).click();const product=panel.locator('div').filter({has:page.getByText(new RegExp(`^${id} ·`))}).last();await expect(product).toContainText('Active');page.once('dialog',dialog=>dialog.dismiss());await product.getByRole('button',{name:'Revoke catalog evidence'}).click();await expect(product).toContainText('Active');page.once('dialog',dialog=>dialog.accept());await product.getByRole('button',{name:'Revoke catalog evidence'}).click();await expect(panel.getByText(new RegExp(`${id} .* Revoked`))).toBeVisible();});
  test('catalog failed approval retains reviewed rows for a successful retry',async({page},info)=>{const id=unique(info),panel=await catalog(page);let failed=false;await page.route('**/api/safe-write',route=>{if(route.request().postDataJSON()?.action==='vendor-catalog-import'&&!failed){failed=true;return route.fulfill({status:503,json:{ok:false,error:'QA transient catalog failure'}});}return route.continue();});await catalogPreview(panel,catalogCsv(id));await panel.getByRole('button',{name:'Approve 1 catalog rows'}).click();await expect(panel.getByRole('alert')).toBeVisible();await expect(panel.getByLabel('Vendor catalog CSV')).toHaveValue(catalogCsv(id));await panel.getByRole('button',{name:'Approve 1 catalog rows'}).click();await expect(panel.getByText(new RegExp(`${id} .* Active`))).toBeVisible();});
});

test.describe('100 operational reliability: sales',()=>{
  test.beforeEach(()=>{test.setTimeout(360000);requireDisposableWorkspace();});
  for(const [name,csv,error] of [
    ['refund quantities',salesCsv('qa-negative',-1),/non-negative/],
    ['non-numeric quantities',salesCsv('qa-nan','NaN'),/non-negative/],
    ['empty quantities',salesCsv('qa-empty',''),/non-negative/],
    ['missing source identifiers','date,item,quantity\n2026-10-10,Soup,2',/headers/],
    ['duplicate quantity columns',`${salesHeader},quantity\n2026-10-10,Soup,2,r,l,5`,/duplicate/],
    ['unfinished quoted source',`${salesHeader}\n2026-10-10,"unfinished`,/unfinished/]
  ])test(`item sales rejects ${name}`,async({page})=>{const panel=await sales(page);await salesPreview(panel,csv);await expect(panel.getByRole('alert')).toContainText(error);await expect(panel.getByRole('button',{name:/Approve .*reviewed sales rows/})).toHaveCount(0);});
  test('unmatched sales require an explicit recipe mapping',async({page})=>{const panel=await sales(page);await salesPreview(panel,salesCsv('qa-unmapped',2,'QA Unmapped Reliability Item'));await expect(panel.getByLabel('Recipe for sales row 1')).toHaveValue('');await expect(panel.getByRole('button',{name:'Approve 1 reviewed sales rows'})).toBeDisabled();await panel.getByLabel('Recipe for sales row 1').selectOption({label:'QA Salmon BLT'});await expect(panel.getByRole('button',{name:'Approve 1 reviewed sales rows'})).toBeEnabled();});
  test('editing sales CSV discards the previous matched approval',async({page},info)=>{const panel=await sales(page);await salesPreview(panel,salesCsv(unique(info)));await expect(panel.getByLabel('Recipe for sales row 1')).not.toHaveValue('');await panel.getByLabel('Item sales CSV').fill(salesCsv(unique(info),9));await expect(panel.getByLabel('Recipe for sales row 1')).toHaveCount(0);await expect(panel.getByRole('button',{name:/Approve .*reviewed sales rows/})).toHaveCount(0);});
  test('sales imports save once and identical retries report duplicates',async({page},info)=>{const panel=await sales(page),csv=salesCsv(unique(info));for(const imported of [1,0]){await salesPreview(panel,csv);const pending=page.waitForResponse(r=>r.url().includes('/api/demand-history')&&r.request().postDataJSON()?.action==='import');await panel.getByRole('button',{name:'Approve 1 reviewed sales rows'}).click();const response=await pending;expect(response.status()).toBe(200);expect(await response.json()).toMatchObject({ok:true,imported,duplicates:imported?0:1});await expect(panel.getByLabel('Item sales CSV')).toHaveValue('');}});
  test('sales import network failure preserves mappings and supports retry',async({page},info)=>{const panel=await sales(page),csv=salesCsv(unique(info));let failed=false;await page.route('**/api/demand-history',route=>{if(route.request().postDataJSON()?.action==='import'&&!failed){failed=true;return route.abort('failed');}return route.continue();});await salesPreview(panel,csv);await panel.getByRole('button',{name:'Approve 1 reviewed sales rows'}).click();await expect(panel.getByRole('alert')).toBeVisible();await expect(panel.getByLabel('Recipe for sales row 1')).not.toHaveValue('');await panel.getByRole('button',{name:'Approve 1 reviewed sales rows'}).click();await expect(panel.getByLabel('Item sales CSV')).toHaveValue('');});
});

test.describe('100 operational reliability: history',()=>{
  test.beforeEach(()=>{test.setTimeout(360000);requireDisposableWorkspace();});
  test('real history endpoint returns bounded read-only workspace evidence',async({page})=>{const panel=await history(page);const pending=page.waitForResponse(r=>r.url().includes('/api/operational-history')&&r.request().postDataJSON()?.source==='prep');await panel.getByRole('button',{name:'Load prep history',exact:true}).click();const response=await pending;expect(response.status()).toBe(200);const body=await response.json();expect(body).toMatchObject({ok:true,readOnly:true,window:{days:180}});expect(body.scanned).toBeLessThanOrEqual(100);await expect(panel).toContainText(/Prep history: \d+ records/);});
  test('history retries an offline first page without claiming verified coverage',async({page})=>{const panel=await history(page);let attempts=0;await historyRoute(page,route=>++attempts===1?route.abort('failed'):route.fulfill({json:historyPage({data:[{id:'one'}]})}));await panel.getByRole('button',{name:'Load prep history',exact:true}).click();await expect(panel.getByRole('button',{name:'Retry prep history',exact:true})).toBeVisible();await expect(panel).toContainText('Coverage incomplete');await panel.getByRole('button',{name:'Retry prep history',exact:true}).click();await expect(panel).toContainText('1 records · 1 scanned · Window verified');});
  test('history pages merge overlapping IDs and use the server cursor',async({page})=>{const panel=await history(page),requests=[];await historyRoute(page,route=>{requests.push(route.request().postDataJSON());return route.fulfill({json:requests.length===1?historyPage({data:[{id:'one'}],scanned:100,hasMore:true,nextCursor:'one'}):historyPage({data:[{id:'one'},{id:'two'}],scanned:102})});});await panel.getByRole('button',{name:'Load prep history',exact:true}).click();await panel.getByRole('button',{name:'Load more prep history',exact:true}).click();await expect(panel).toContainText('2 records · 102 scanned · Window verified');expect(requests[1]).toMatchObject({after:'one',scanned:100,days:180});});
  test('undated history keeps exhausted coverage incomplete',async({page})=>{const panel=await history(page);await historyRoute(page,route=>route.fulfill({json:historyPage({undated:2})}));await panel.getByRole('button',{name:'Load prep history',exact:true}).click();await expect(panel).toContainText('2 records have no usable timestamp');await expect(panel).toContainText('Coverage incomplete');await expect(panel.getByRole('button',{name:'Refresh prep history',exact:true})).toBeEnabled();});
  test('truncated history cannot claim complete coverage or scan again',async({page})=>{const panel=await history(page);await historyRoute(page,route=>route.fulfill({json:historyPage({scanned:2000,truncated:true})}));await panel.getByRole('button',{name:'Load prep history',exact:true}).click();await expect(panel).toContainText('cannot be called complete');await expect(panel).toContainText('0 records · 2000 scanned · Coverage incomplete');await expect(panel.getByRole('button',{name:'Refresh prep history',exact:true})).toBeDisabled();});
  test('explicit history refresh starts at the first cursor and replaces rows',async({page})=>{const panel=await history(page),requests=[];await historyRoute(page,route=>{requests.push(route.request().postDataJSON());return route.fulfill({json:historyPage({data:requests.length===1?[{id:'old'}]:[{id:'new'},{id:'two'}]})});});await panel.getByRole('button',{name:'Load prep history',exact:true}).click();await panel.getByRole('button',{name:'Refresh prep history',exact:true}).click();await expect(panel).toContainText('2 records · 1 scanned · Window verified');expect(requests[1]).toMatchObject({after:'',scanned:0});});
  test('history disables duplicate loading while a request is pending',async({page})=>{const panel=await history(page);let release;const barrier=new Promise(resolve=>{release=resolve;});let requests=0;await historyRoute(page,async route=>{requests++;await barrier;await route.fulfill({json:historyPage({})});});await panel.getByRole('button',{name:'Load prep history',exact:true}).click();await expect(panel.getByRole('button',{name:'Load prep history',exact:true})).toBeDisabled();await expect(panel.getByText('Loading historical evidence…')).toBeVisible();release();await expect(panel.getByRole('button',{name:'Refresh prep history',exact:true})).toBeEnabled();expect(requests).toBe(1);});
  test('invalid history response shows a retry instead of an empty healthy window',async({page})=>{const panel=await history(page);let attempts=0;await historyRoute(page,route=>++attempts===1?route.fulfill({contentType:'text/html',body:'<html>Unavailable</html>'}):route.fulfill({json:historyPage({})}));await panel.getByRole('button',{name:'Load prep history',exact:true}).click();await expect(panel.getByRole('alert')).toBeVisible();await panel.getByRole('button',{name:'Retry prep history',exact:true}).click();await expect(panel).toContainText('0 records · 1 scanned · Window verified');});
});

test.describe('100 operational reliability: attendance',()=>{
  test.beforeEach(()=>{test.setTimeout(360000);requireDisposableWorkspace();});
  for(const [label,value] of [['Start/end grace minutes','-1'],['Open-break review minutes','0'],['Workspace attendance timezone','QA/Invalid']])test(`attendance rejects invalid ${label}`,async({page})=>{const panel=await policy(page);await panel.getByLabel(label).fill(value);const pending=policyWrite(page);await panel.getByRole('button',{name:'Approve attendance review policy'}).click();expect((await pending).status()).toBe(400);await expect(panel.getByRole('alert')).toBeVisible();await expect(panel.getByLabel(label)).toHaveValue(value);});
  test('attendance approval persists explicit thresholds and reviewer evidence',async({page})=>{let panel=await policy(page);await panel.getByLabel('Start/end grace minutes').fill('11');await panel.getByLabel('Open-break review minutes').fill('31');await panel.getByLabel('Workspace attendance timezone').fill('America/Chicago');await panel.getByRole('checkbox').check();const pending=policyWrite(page);await panel.getByRole('button',{name:'Approve attendance review policy'}).click();const body=await(await pending).json();expect(body).toMatchObject({ok:true,policy:{graceMinutes:11,maxOpenBreakMinutes:31,enabled:true,reviewOnly:true}});expect(body.policy.approvedBy).toBeTruthy();await reloadTo(page,'today');panel=page.getByTestId('attendance-policy-review');await expect(panel.getByLabel('Start/end grace minutes')).toHaveValue('11');await expect(panel.getByRole('checkbox')).toBeChecked();});
  test('attendance transient failure retains the reviewed policy for retry',async({page})=>{const panel=await policy(page);let failed=false;await page.route('**/api/safe-write',route=>{if(route.request().postDataJSON()?.action==='attendance-policy-approve'&&!failed){failed=true;return route.abort('failed');}return route.continue();});await panel.getByLabel('Start/end grace minutes').fill('12');await panel.getByRole('button',{name:'Approve attendance review policy'}).click();await expect(panel.getByRole('alert')).toBeVisible();await expect(panel.getByLabel('Start/end grace minutes')).toHaveValue('12');const pending=policyWrite(page);await panel.getByRole('button',{name:'Approve attendance review policy'}).click();expect((await pending).status()).toBe(200);await expect(panel.getByRole('alert')).toHaveCount(0);});
  test('attendance can be explicitly disabled without modifying punches',async({page})=>{const panel=await policy(page);await panel.getByRole('checkbox').uncheck();const pending=policyWrite(page);await panel.getByRole('button',{name:'Approve attendance review policy'}).click();expect(await(await pending).json()).toMatchObject({ok:true,policy:{enabled:false,reviewOnly:true}});await reloadTo(page,'today');await expect(page.getByTestId('attendance-policy-review').getByRole('checkbox')).not.toBeChecked();});
});

test.describe('100 operational reliability: forecast and training',()=>{
  test.beforeEach(()=>{test.setTimeout(360000);requireDisposableWorkspace();});
  test('forecast exposes dated comparable evidence for reviewed recommendations',async({page,forecastFixture})=>{const panel=forecastRow(await forecast(page),forecastFixture);await expect(panel.getByText('Demand evidence',{exact:true})).toBeVisible();await panel.getByText('Demand evidence',{exact:true}).click();await expect(panel).toContainText(/Comparable dates: \d{4}-\d{2}-\d{2}/);await expect(panel).toContainText(/Average daily sales/);});
  test('forecast never offers invalid time-window targets as actionable drafts',async({page,forecastFixture})=>{const panel=await forecast(page);const invalid=panel.locator('article').filter({hasText:`${forecastFixture.date} � Server`}).filter({hasText:'Configure a valid role'});await expect(invalid.first()).toContainText('Configure a valid role');await expect(invalid.getByRole('button',{name:'Review forecast drafts'})).toHaveCount(0);});
  test('cancelled forecast approval leaves the draft count unchanged',async({page,forecastFixture})=>{const panel=await forecast(page),row=forecastRow(panel,forecastFixture);await expect(row).toBeVisible();const before=await row.innerText();page.once('dialog',async dialog=>{expect(dialog.message()).toContain('Shifts remain unpublished');await dialog.dismiss();});await row.getByRole('button',{name:'Review forecast drafts'}).click();expect(await row.innerText()).toBe(before);});
  test('approved forecast drafts satisfy coverage and survive reload without duplicates',async({page,forecastFixture})=>{let panel=await forecast(page),row=forecastRow(panel,forecastFixture);const heading=await row.locator('h5').innerText();page.once('dialog',dialog=>dialog.accept());await row.getByRole('button',{name:'Review forecast drafts'}).click();await expect(row).toContainText('0 draft(s) to review');await expect(row.getByRole('button',{name:'Review forecast drafts'})).toBeDisabled();await reloadTo(page,'schedule');await page.getByRole('button',{name:'Open Copilot Tools',exact:true}).click();await page.getByRole('tab',{name:'Demand forecast',exact:true}).click();panel=page.getByTestId('schedule-demand-forecast');row=forecastRow(panel,forecastFixture);await expect(row.locator('h5')).toHaveText(heading);await expect(row).toContainText('0 draft(s) to review');await expect(row.getByRole('button',{name:'Review forecast drafts'})).toBeDisabled();});
  test('completing an evidence-linked training task persists and updates Today follow-up',async({page})=>{await enter(page,'hr');await page.getByRole('button',{name:'Onboarding',exact:true}).click();const row=page.locator('div').filter({has:page.getByText('QA Reliability Training',{exact:true})}).filter({has:page.getByRole('button',{name:/Mark (in)?complete/})}).last();const incomplete=row.getByRole('button',{name:'Mark incomplete',exact:true});if(await incomplete.count())await incomplete.click();await row.getByRole('button',{name:'Mark complete',exact:true}).click();await expect(row.getByRole('button',{name:'Mark incomplete',exact:true})).toBeEnabled();await reloadTo(page,'hr');await page.getByRole('button',{name:'Onboarding',exact:true}).click();await expect(page.getByRole('button',{name:'Mark incomplete',exact:true}).first()).toBeVisible();await gotoTab(page,'today');await expect(page.getByTestId('training-follow-up')).toContainText('1/1 checklist items complete');});
  test('completed training with partial history cannot claim effectiveness',async({page})=>{await enter(page,'today');const panel=page.getByTestId('training-follow-up');await expect(panel).toContainText('QA Reliability Employee');await expect(panel).toContainText(/no effectiveness claim|Review assignment completion/);});
});
