#!/usr/bin/env node
'use strict';
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const json=file=>JSON.parse(read(file));
const exists=file=>fs.existsSync(path.join(root,file));
const pkg=json('package.json'), lock=json('package-lock.json'), version=json('public/version.json');
assert.equal(pkg.version,'17.0.34');
assert.equal(lock.version,'17.0.34');
assert.equal(lock.packages[''].version,'17.0.34');
assert.equal(version.version,'17.0.34');
assert.equal(version.build,'17.0.34');
assert.equal(version.releaseTitle,'Restaurant Readiness Command Center');
assert.equal(pkg.scripts['test:source'],'node scripts/validate-17-0-34.js');
assert.equal(pkg.scripts['validate:17.0.34'],'node scripts/validate-17-0-34.js');
assert(pkg.scripts['test:current-release-targeted'].includes('api/restaurant-readiness-17-0-34.test.cjs'));
assert(pkg.scripts['test:current-release-targeted'].endsWith('node scripts/validate-17-0-34.js'));
assert(read('src/core/appCore.js').includes("CURRENT_VERSION = '17.0.34'"));
assert(read('api/_version.js').includes("APP_VERSION = '17.0.34'"));
assert(read('api/_version.js').includes("SECURITY_SCHEMA_VERSION = '17.0.34'"));
assert(read('api/_pos-bridge-config.js').includes("APP_RELEASE = '17.0.34'"));
assert(read('src/core/customerHelpKnowledge.js').includes("CUSTOMER_HELP_VERSION = '17.0.34'"));
assert(read('src/core/customerHelpKnowledge.cjs').includes("CUSTOMER_HELP_VERSION = '17.0.34'"));
const ops=read('src/features/operations.jsx');
assert(ops.includes("restaurantReadiness.cjs"));
assert(ops.includes('data-testid="restaurant-readiness-command-center"'));
assert(ops.includes('No automatic changes'));
const engine=read('src/core/restaurantReadiness.cjs');
for(const label of ['Inventory','Prep','Staffing','Maintenance','Food Safety','Financial','Operations','System']) assert(engine.includes(`label:'${label}'`), `${label} readiness exists`);
assert(engine.includes("status:'needs-data'"));
assert(engine.includes('reviewOnly:true'));
assert(exists('api/restaurant-readiness-17-0-34.test.cjs'));
assert(exists('tests/86chaos-release-gate/43-restaurant-readiness-command-center.spec.cjs'));
const universe=read('scripts/86chaos-release-gate/release-test-universe.cjs');
assert(universe.includes('tests/86chaos-release-gate/43-restaurant-readiness-command-center.spec.cjs'));
const workflow=read('.github/workflows/testing-targeted-delta.yml');
assert(workflow.includes('npm run test:current-release-targeted'));
assert(!workflow.includes('npm run test:play-store'));
for(const file of ['test-tools/certification/groups.json','test-tools/regressions/registry.json','test-tools/certification/cost-performance-baselines.json']) assert.equal(json(file).release,'17.0.34');
console.log('17.0.34 Restaurant Readiness Command Center validation passed; this does not certify the full release gate.');
