#!/usr/bin/env node
'use strict';
const fs=require('node:fs');
const assert=require('node:assert/strict');
const read=f=>fs.readFileSync(f,'utf8');
const json=f=>JSON.parse(read(f));
const pkg=json('package.json'),lock=json('package-lock.json'),version=json('public/version.json');
assert.equal(pkg.version,'17.0.18');
assert.equal(lock.version,pkg.version);
assert.equal(lock.packages[''].version,pkg.version);
assert.equal(version.version,pkg.version);
assert.equal(version.build,pkg.version);
assert.equal(version.releaseTitle,'Release Gate Schedule Subprocess Timeout Repair');
assert.equal(pkg.scripts['test:source'],'node scripts/validate-17-0-18.js');
assert.equal(pkg.scripts['validate:17.0.18'],'node scripts/validate-17-0-18.js');
assert(pkg.scripts['test:schedule-publish:core']?.includes('react-scripts test --watchAll=false --runInBand'),'schedule core script keeps Node/React publication coverage');
assert(!/playwright|mobile-voice-layout/.test(pkg.scripts['test:schedule-publish:core']),'schedule core script does not nest Playwright');
assert.equal(pkg.scripts['test:schedule-publish'],'npm run test:schedule-publish:core && npm run test:mobile-voice-layout');
const runner=read('scripts/86chaos-release-gate/run-node-release-checks.cjs');
assert(runner.includes('--timeout 600 -- npm run test:schedule-publish:core'),'release gate runs schedule core separately');
assert(runner.includes("group: 'mobile layout Playwright smoke'"),'release gate gives layout smoke a separate step');
assert(runner.includes('--timeout 180 -- node node_modules/@playwright/test/cli.js test --config=playwright.layout.config.cjs'),'release gate launches local Playwright CLI directly');
assert(!runner.includes('--timeout 900 -- npm run test:schedule-publish'),'old nested schedule Playwright launch removed');
const extractor=read('scripts/86chaos-release-gate/failure-extractor.cjs');
assert(extractor.includes('if (status === 124)'),'failure extraction has timeout-first classification');
assert(extractor.includes("'Command timed out (exit code 124).'"),'timeout classification has deterministic fallback');
for(const file of ['src/core/appCore.js','api/_version.js','api/_pos-bridge-config.js']) assert(read(file).includes("'17.0.18'"),`${file} carries 17.0.18`);
const schedule=read('src/features/schedule.jsx');
assert(schedule.includes('publishResult.verifiedNewCount'),'17.0.16 authoritative publish summary preserved');
const service=read('api/_schedule-publish-service.cjs');
assert(service.includes('resolveEmployeeForPublishShift'),'17.0.17 legacy publish identity repair preserved');
const app=read('src/App.js');
const navStart=app.indexOf('const transitionActiveTabState = useCallback((nextTab) => {');
const navEnd=app.indexOf('const disarmPwaBackExit',navStart);
assert(navStart>=0&&navEnd>navStart&&!app.slice(navStart,navEnd).includes('React.startTransition'),'17.0.17 synchronous top-level navigation preserved');
for(const file of ['test-tools/certification/groups.json','test-tools/regressions/registry.json','test-tools/certification/cost-performance-baselines.json']) assert.equal(json(file).release,pkg.version);
console.log('17.0.18 targeted release-gate harness validation passed; this is not full release certification.');
