#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),json=f=>JSON.parse(read(f));
const p=json('package.json'),l=json('package-lock.json'),v=json('public/version.json');
assert.equal(p.version,'17.0.36');
assert.equal(l.version,'17.0.36');
assert.equal(l.packages[''].version,'17.0.36');
assert.equal(v.version,'17.0.36');
assert.equal(p.dependencies['firebase-admin'],'14.5.0');
assert.equal(l.packages['node_modules/firebase-admin'].version,'14.5.0');
assert.equal(p.scripts['test:source'],'node scripts/validate-17-0-36.js');
assert.equal(p.scripts['validate:17.0.36'],'node scripts/validate-17-0-36.js');
assert(p.scripts['test:current-release-targeted'].includes('firebase-admin-url-api-17-0-36.test.cjs'));
const shim=read('api/_firebase-admin-compat.js');
for(const entry of ['firebase-admin/app','firebase-admin/auth','firebase-admin/firestore','firebase-admin/app-check']) assert(shim.includes(entry),`compat facade imports ${entry}`);
assert(!/require\(['"]firebase-admin['"]\)/.test(shim));
assert(read('src/core/localReminderBridge.js').includes('LocalNotifications'));
assert(!/firebase|firestore|secureFetch|\/api\//i.test(read('src/core/localReminderBridge.js')));
assert(read('src/features/intelligence.jsx').includes('This device only'));
assert(read('src/core/restaurantReadiness.cjs').includes('function buildRestaurantReadiness'));
const universe=read('scripts/86chaos-release-gate/release-test-universe.cjs');
assert(universe.includes('44-device-local-reminders.spec.cjs'));
assert(universe.includes('45-firebase-admin-url-api.spec.cjs'));
const workflow=read('.github/workflows/testing-targeted-delta.yml');
assert(workflow.includes('npm run test:current-release-targeted'));
assert(!workflow.includes('npm run test:play-store'));
assert(!workflow.includes('Run full Release Gate'));
for(const file of ['test-tools/certification/groups.json','test-tools/regressions/registry.json','test-tools/certification/cost-performance-baselines.json']) assert.equal(json(file).release,'17.0.36');
console.log('17.0.36 Firebase Admin WHATWG URL modernization validation passed; this does not certify the full release gate.');
