#!/usr/bin/env node
'use strict';
const fs=require('node:fs');
const assert=require('node:assert/strict');
const read=f=>fs.readFileSync(f,'utf8');
const json=f=>JSON.parse(read(f));
const pkg=json('package.json'),lock=json('package-lock.json'),version=json('public/version.json');
assert.equal(pkg.version,'17.0.15');
assert.equal(lock.version,pkg.version);
assert.equal(lock.packages[''].version,pkg.version);
assert.equal(version.version,pkg.version);
assert.equal(version.build,pkg.version);
assert.equal(pkg.scripts['test:source'],'node scripts/validate-17-0-15.js');
assert.equal(pkg.scripts['validate:17.0.15'],'node scripts/validate-17-0-15.js');
for(const file of ['src/core/appCore.js','api/_version.js','api/_pos-bridge-config.js']) assert(read(file).includes("'17.0.15'"),`${file} carries 17.0.15`);
const service=read('api/_schedule-publish-service.cjs');
assert(service.includes("_source:'user-identity-fallback'"),'server roster accepts tenant user identity fallback');
assert(!service.includes("user.legacyMembershipFallback===true&&Number(user.membershipMigrationVersion||0)<2"),'old migration-only roster restriction removed from publish identity resolution');
const core=read('api/_schedule-publish-core.cjs');
assert(core.includes('if (missingEvidenceIds.length) throw Object.assign'),'missing authoritative write evidence still fails closed');
assert(core.includes('if (unchanged) assertConfirmedEvidenceMatches'),'extra no-write evidence is ignored unless it maps to an authoritative unchanged shift');
assert(core.includes('unavailableEvidenceIds'),'diagnostic unavailable evidence is still calculated');
const schedule=read('src/features/schedule.jsx');
assert(schedule.includes('getDocsFromServer(candidateQuery)'),'authoritative candidate reads preserved');
assert(schedule.includes('confirmedEvidenceRows'),'unchanged evidence repair preserved');
const pwa=read('tests/86chaos-release-gate/27-pwa-browser-icon-matrix.spec.cjs');
assert(!pwa.includes('{ page,'),'request-only PWA repair preserved');
for(const file of ['test-tools/certification/groups.json','test-tools/regressions/registry.json','test-tools/certification/cost-performance-baselines.json']) assert.equal(json(file).release,pkg.version);
console.log('17.0.15 targeted source validation passed; this is not full release certification.');
