#!/usr/bin/env node
'use strict';
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const json=file=>JSON.parse(read(file));
const version='18.0.0';
const pkg=json('package.json');
const lock=json('package-lock.json');
const pub=json('public/version.json');
const contract=json('mobile/native-platform-contract.json');
const cap=json('capacitor.config.json');
assert.equal(pkg.version,version);
assert.equal(lock.version,version);
assert.equal(lock.packages[''].version,version);
assert.equal(pub.version,version);
assert.equal(pub.build,version);
assert.equal(pkg.scripts['test:source'],'node scripts/validate-18-0-0.js');
assert.equal(pkg.scripts['validate:18.0.0'],'node scripts/validate-18-0-0.js');
assert.match(read('api/_version.js'),/APP_VERSION = '18\.0\.0'/);
assert.match(read('api/_version.js'),/SECURITY_SCHEMA_VERSION = '18\.0\.0'/);
assert.match(read('api/_pos-bridge-config.js'),/APP_RELEASE = '18\.0\.0'/);
assert.match(read('src/core/appCore.js'),/CURRENT_VERSION = '18\.0\.0'/);
assert.equal(contract.release,version);
assert.deepEqual(contract.platforms,['android','ios']);
assert.equal(contract.equalPlatformPriority,true);
assert.equal(contract.firebase.projectId,'chaos-test-d1601');
assert.equal(contract.firebase.productionProjectAllowed,false);
assert.equal(contract.costControls.newPaidServices,false);
assert.equal(contract.costControls.nativeBackgroundReleaseGraceMs,15000);
assert.equal(cap.appId,'com.chiltonappworks.chaos86');
assert.equal(cap.webDir,'build');
assert.equal(cap.server.url,undefined);
for(const file of ['test-tools/certification/groups.json','test-tools/regressions/registry.json','test-tools/certification/cost-performance-baselines.json']) assert.equal(json(file).release,version);
assert.equal(json('vercel.json').git.deploymentEnabled.mobile,true);
assert.match(read('scripts/86chaos-release-gate/release-test-universe.cjs'),/58-native-mobile-cost-foundation\.spec\.cjs/);
console.log('18.0.0 native mobile and Firebase cost foundation validated.');
