#!/usr/bin/env node
'use strict';
const fs=require('node:fs');
const assert=require('node:assert/strict');
const {validateCurrentReleaseMetadata}=require('./86chaos-release-gate/current-release-metadata.cjs');
const read=f=>fs.readFileSync(f,'utf8'); const json=f=>JSON.parse(read(f));
const expected='17.0.27'; const title='Time Clock and Schedule Runtime Recovery Repair';
const pkg=json('package.json'), lock=json('package-lock.json'), version=json('public/version.json');
assert.equal(pkg.version,expected); assert.equal(lock.version,expected); assert.equal(lock.packages[''].version,expected); assert.equal(version.version,expected); assert.equal(version.build,expected); assert.equal(version.releaseTitle,title);
assert.equal(pkg.scripts['test:source'],'node scripts/validate-17-0-27.js');
for(const file of ['src/core/appCore.js','api/_version.js','api/_pos-bridge-config.js']) assert(read(file).includes("'17.0.27'"),file);
for(const file of ['RELEASE_17_0_27.md','RUN_86CHAOS_PLAY_STORE_RELEASE_GATE.ps1','RUN_86CHAOS_UPDATE_TEST_DEPLOY.ps1','release-source-manifest.json','scripts/verify-schedule-runtime-bundle.cjs']) assert(fs.statSync(file).isFile(),file);
for(const file of ['test-tools/certification/groups.json','test-tools/regressions/registry.json','test-tools/certification/cost-performance-baselines.json']) assert.equal(json(file).release,expected,file);
const metadata=validateCurrentReleaseMetadata(process.cwd()); assert.equal(metadata.ok,true,metadata.errors.join('\n'));
const scheduleWrapper=read('src/core/scheduleRuntimeSafety.js');
const requestWrapper=read('src/core/requestOffRuntimeSafety.js');
assert(scheduleWrapper.includes("const safety = require('./scheduleRuntimeSafety.shared.js');"));
assert(requestWrapper.includes("const safety = require('./requestOffRuntimeSafety.shared.js');"));
assert(!scheduleWrapper.includes('.cjs')); assert(!requestWrapper.includes('.cjs'));
for(const name of ['safeScheduleObjectRows','safeScheduleRosterRows','safeScheduleShiftRows','safeScheduleAvailabilityRows','safeScheduleEventRows']) assert(scheduleWrapper.includes(`export const ${name} = safety.${name};`),name);
const routeTest=read('src/features/scheduleRuntimeSafety.test.jsx');
assert(routeTest.includes('top-level Time Clock and Schedule route survives hostile legacy data across every schedule subtab'));
assert(routeTest.includes('TabMasterSchedule'));
const gate=read('RUN_86CHAOS_PLAY_STORE_RELEASE_GATE.ps1'); assert(gate.includes('$BrowserTestUrl = [string]$PreflightReport.resolvedBrowserTestUrl')); assert(gate.includes('$env:CHAOS_IMMUTABLE_VERCEL_URL = $PinnedDeploymentUrl.TrimEnd')); assert(gate.includes('$env:CHAOS_BROWSER_BASE_URL = $BrowserTestUrl.TrimEnd'));
const preflight=read('scripts/86chaos-release-gate/preflight-env.cjs'); assert(preflight.includes('browserAliasIdentityVerified')); assert(preflight.includes('aliasServer.vercelDeploymentId')); assert(preflight.includes("resolvedBrowserTestUrl: browserAliasIdentityVerified ? approvedBrowserTestUrl : ''"));
assert(pkg.scripts['test:repair:17.0.27'].includes('api/schedule-runtime-browser-contract-17-0-27.test.cjs')); assert(pkg.scripts['test:repair:17.0.27'].includes('api/request-off-runtime-safety-17-0-9.test.cjs'));
assert.equal(pkg.scripts['test:schedule-runtime:17.0.27'],'react-scripts test --watchAll=false --runInBand src/features/scheduleRuntimeSafety.test.jsx');
assert.equal(pkg.scripts['test:schedule-runtime:bundle'],'node scripts/verify-schedule-runtime-bundle.cjs');
const defects=json('test-tools/regressions/registry.json').defects; assert(defects.some(x=>x.defectId==='SCHEDULE-RUNTIME-CJS-STATIC-MEDIA-1727'&&x.fixedVersion===expected));
const updater=read('RUN_86CHAOS_UPDATE_TEST_DEPLOY.ps1'); assert(updater.includes("[string]$ExpectedVersion = '17.0.27'")); assert(updater.includes("'test:schedule-runtime:17.0.27'")); assert(updater.includes("'test:schedule-runtime:bundle'"));
console.log('17.0.27 source validation passed; this does not certify the release.');
