#!/usr/bin/env node
'use strict';
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const root=path.resolve(__dirname,'..');const read=file=>fs.readFileSync(path.join(root,file),'utf8');const json=file=>JSON.parse(read(file));const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');let failures=0;const ok=(value,message)=>{if(value)console.log(`OK: ${message}`);else{failures+=1;console.error(`FAIL: ${message}`);}};
const pkg=json('package.json'),lock=json('package-lock.json'),version=json('public/version.json');ok(pkg.version==='17.0.0'&&lock.version==='17.0.0'&&lock.packages[''].version==='17.0.0','package version surfaces are exactly 17.0.0');ok(version.version==='17.0.0'&&version.build==='17.0.0'&&version.releaseTitle==='Role-Based Schedule Publishing and Hostile Certification Foundation','public release identity is current');ok(read('api/_version.js').includes("APP_VERSION = '17.0.0'")&&read('src/core/appCore.js').includes("CURRENT_VERSION = '17.0.0'")&&read('api/_pos-bridge-config.js').includes("APP_RELEASE = '17.0.0'"),'client, API, and bridge release identity agree');
for(const file of ['src/core/rosterRoleIdentity.js','src/core/schedulePublicationPlan.js','api/_schedule-publish-core.cjs','api/_schedule-publish-service.cjs','api/schedule-publish.js'])ok(fs.existsSync(path.join(root,file)),`${file} exists`);const schedule=read('src/features/schedule.jsx');ok(schedule.includes('All Roles')&&schedule.includes('Selected Roles')&&schedule.includes("'/api/schedule-publish'")&&schedule.includes('digestSchedulePublicationPlan'),'one publish dialog composes week and role scope through the server operation');ok(!/using loaded schedule candidates for date/.test(schedule),'publish query failures no longer fall back to incomplete local candidates');ok(schedule.includes('Punch saved but unscheduled alert failed')&&schedule.includes('setActivePunch(durablePunch)'),'clock-in keeps committed punch truth after secondary alert failure');
const role=read('src/core/rosterRoleIdentity.js');ok(role.includes('previousNames')&&role.includes('archivedAt')&&role.includes('ambiguous-legacy-role-name'),'role identity preserves rename/archive history and rejects ambiguity');const service=read('api/_schedule-publish-service.cjs');for(const term of ['planDigest','leaseToken','generation','committedShiftIds','verifiedShiftIds','conflictedShiftIds','remainingShiftIds','processTimeOff','notifyAffected'])ok(service.includes(term),`publish service records ${term}`);ok(service.includes("where('restaurantId','==',plan.restaurantId)")&&service.includes('employeeSet.has(subject)'),'time-off effects are tenant, employee, date, and fresh-status scoped');
const safe=read('api/safe-write.js');ok(safe.includes('verifyExistingTargetOwnership')&&safe.includes('protectServerOwnedFields'),'safe-write validates existing target ownership and server fields');const auth=read('api/_chaos-admin.js');ok(auth.includes('verifyIdToken(token, true)')&&auth.includes('getUser(decoded.uid)')&&auth.includes('Workspace membership is inactive or removed'),'human authority checks revocation, disabled Auth users, and canonical inactive membership');
const packageScripts=pkg.scripts;for(const name of ['test:release:fast','test:release:firebase','test:hostile','test:release:hostile','test:release:deployed','test:release:recovery','test:release:scale','test:hostile:contracts','test:hostile:mutations','test:schedule-publish','validate:17.0.0'])ok(Boolean(packageScripts[name]),`${name} is wired`);const groups=json('test-tools/certification/groups.json');ok(Object.values(groups.groups).filter(group=>group.mandatory).length>=7,'mandatory certification groups are declared');const registry=json('test-tools/regressions/registry.json');ok(registry.defects.length>=5&&registry.defects.every(row=>row.permanentTestIds?.length&&row.fidelity&&row.fixedVersion==='17.0.0'),'permanent regression registry is complete');
const protectedHashes={'firestore.rules':'51bfd7d39edd59f680ae41a149c108cec8cd42d00b102d84cb00ee40d90264d9','firestore.indexes.json':'ee666de303988cd269f7c09fa63678a2deb1cfcaa199cb4f1656dd9bddcc4b4b','storage.rules':'174e7e9a140193ff69ccf0f0d3e5c65b81a9e0fbbd612bff45ce57e7a3a7ce9c','database.rules.json':'152b5cd3f9839f598c9602706d8205b96759296e865d540b52c780900bfba138','firebase.json':'bd837a11c71750d4da6ccfcb725ca54e78dd76008b525ec54c7fe79a5b8a3ca4','vercel.json':'3a42afbec525fe1abfe52f28d9b973c9494bdaca6edf3b0ed1a43f30c69db276','public/firebase-messaging-sw.js':'46c7f5760350721d424ba6db9a3a9127449fbb670a24b04328e71d3a74ed2366'};for(const [file,expected] of Object.entries(protectedHashes))ok(sha(file)===expected,`${file} remains byte-for-byte protected`);ok(!/collection\(['"](?:inventoryItems|sales|timePunches|payroll|recipes|vendors)['"]\)/.test(read('api/_pos-bridge-events.js')),'POS Bridge remains staging-only with no downstream processor');
if(failures){console.error(`17.0.0 validation failed with ${failures} failure(s).`);process.exit(1);}console.log('17.0.0 source validation passed.');
