#!/usr/bin/env node
'use strict';
const fs=require('node:fs');
const assert=require('node:assert/strict');
const {validateCurrentReleaseMetadata}=require('./86chaos-release-gate/current-release-metadata.cjs');
const read=f=>fs.readFileSync(f,'utf8'); const json=f=>JSON.parse(read(f));
const expected='17.0.28'; const title='Time Clock and Schedule Roster Role Runtime Repair';
const pkg=json('package.json'), lock=json('package-lock.json'), version=json('public/version.json');
assert.equal(pkg.version,expected); assert.equal(lock.version,expected); assert.equal(lock.packages[''].version,expected); assert.equal(version.version,expected); assert.equal(version.build,expected); assert.equal(version.releaseTitle,title);
assert.equal(pkg.scripts['test:source'],'node scripts/validate-17-0-28.js');
for(const file of ['src/core/appCore.js','api/_version.js','api/_pos-bridge-config.js']) assert(read(file).includes("'17.0.28'"),file);
for(const file of ['RELEASE_17_0_28.md','RUN_86CHAOS_PLAY_STORE_RELEASE_GATE.ps1','RUN_86CHAOS_UPDATE_TEST_DEPLOY.ps1','release-source-manifest.json','scripts/verify-schedule-runtime-bundle.cjs','src/core/rosterRoleIdentity.shared.js']) assert(fs.statSync(file).isFile(),file);
for(const file of ['test-tools/certification/groups.json','test-tools/regressions/registry.json','test-tools/certification/cost-performance-baselines.json']) assert.equal(json(file).release,expected,file);
const metadata=validateCurrentReleaseMetadata(process.cwd()); assert.equal(metadata.ok,true,metadata.errors.join('\n'));
const rosterWrapper=read('src/core/rosterRoleIdentity.js'); const rosterProxy=read('src/core/rosterRoleIdentityCore.cjs');
assert(rosterWrapper.includes("require('./rosterRoleIdentity.shared.js')")); assert(!rosterWrapper.includes('rosterRoleIdentityCore.cjs'));
assert(rosterProxy.includes("module.exports = require('./rosterRoleIdentity.shared.js')"));
const verifier=read('scripts/verify-schedule-runtime-bundle.cjs'); assert(verifier.includes('rosterRoleIdentityCore'));
assert(pkg.scripts['test:repair:17.0.28'].includes('api/roster-role-browser-runtime-contract-17-0-28.test.cjs'));
assert.equal(pkg.scripts['test:schedule-runtime:17.0.28'],'react-scripts test --watchAll=false --runInBand src/features/scheduleRuntimeSafety.test.jsx src/core/rosterRoleIdentity.test.js');
const defects=json('test-tools/regressions/registry.json').defects; assert(defects.some(x=>x.defectId==='SCHEDULE-ROSTER-ROLE-CJS-STATIC-MEDIA-1728'&&x.fixedVersion===expected));
const updater=read('RUN_86CHAOS_UPDATE_TEST_DEPLOY.ps1'); assert(updater.includes("[string]$ExpectedVersion = '17.0.28'")); assert(updater.includes("'test:schedule-runtime:17.0.28'")); assert(updater.includes("'test:schedule-runtime:bundle'"));
console.log('17.0.28 source validation passed; this does not certify the release.');
