#!/usr/bin/env node
'use strict';
const fs = require('node:fs');
const assert = require('node:assert/strict');
const { validateCurrentReleaseMetadata } = require('./86chaos-release-gate/current-release-metadata.cjs');
const read = f => fs.readFileSync(f, 'utf8');
const json = f => JSON.parse(read(f));
const expected = '17.0.29';
const title = 'Time Clock and Schedule Parent Route Recovery';
const pkg = json('package.json');
const lock = json('package-lock.json');
const version = json('public/version.json');
assert.equal(pkg.version, expected);
assert.equal(lock.version, expected);
assert.equal(lock.packages[''].version, expected);
assert.equal(version.version, expected);
assert.equal(version.build, expected);
assert.equal(version.releaseTitle, title);
assert.equal(pkg.scripts['test:source'], 'node scripts/validate-17-0-29.js');
assert.equal(pkg.scripts['test:repair:17.0.29'], 'node --test api/time-clock-schedule-parent-boundary-17-0-29.test.cjs');
assert.equal(pkg.scripts['test:time-clock-schedule-parent:17.0.29'], 'react-scripts test --watchAll=false --runInBand src/features/timeClockScheduleParentRecovery.test.jsx');
assert(pkg.scripts['test:targeted:time-clock-schedule-browser:17.0.29'].includes('time-clock-schedule-parent-recovery-17-0-29.spec.cjs'));
for (const file of ['src/core/appCore.js', 'api/_version.js', 'api/_pos-bridge-config.js']) assert(read(file).includes("'17.0.29'"), file);
for (const file of ['RELEASE_17_0_29.md', 'RUN_86CHAOS_UPDATE_TEST_DEPLOY.ps1', 'release-source-manifest.json', 'src/features/timeClockScheduleParentRecovery.test.jsx', 'tests/e2e/time-clock-schedule-parent-recovery-17-0-29.spec.cjs', 'api/time-clock-schedule-parent-boundary-17-0-29.test.cjs']) assert(fs.statSync(file).isFile(), file);
for (const file of ['test-tools/certification/groups.json', 'test-tools/regressions/registry.json', 'test-tools/certification/cost-performance-baselines.json']) assert.equal(json(file).release, expected, file);
const updater = read('RUN_86CHAOS_UPDATE_TEST_DEPLOY.ps1');
assert(updater.includes("[string]$ExpectedVersion = '17.0.29'"));
assert(updater.includes("'test:time-clock-schedule-parent:17.0.29'"));
assert(updater.includes("'test:targeted:time-clock-schedule-browser:17.0.29'"));
assert(!updater.includes("Invoke-Checked 'npm' @('run', 'test:play-store')"), '17.0.29 updater must not launch the 282-test Play Store gate');
const metadata = validateCurrentReleaseMetadata(process.cwd());
assert.equal(metadata.ok, true, metadata.errors.join('\n'));
console.log('17.0.29 source validation passed; targeted workflow intentionally excludes the full Play Store gate.');
