#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const json=file=>JSON.parse(read(file));
const version='17.0.40';
const p=json('package.json'),l=json('package-lock.json'),v=json('public/version.json');
assert.equal(p.version,version);assert.equal(l.version,version);assert.equal(l.packages[''].version,version);assert.equal(v.version,version);assert.equal(v.build,version);
assert.equal(p.scripts['test:source'],'node scripts/validate-17-0-40.js');assert.equal(p.scripts['validate:17.0.40'],'node scripts/validate-17-0-40.js');assert.equal(p.scripts['test:repair:17.0.40'],'npm run test:current-release-targeted');
assert.ok(p.scripts['test:current-release-targeted'].includes('api/emergency-schedule-requestoff-17-0-40.test.cjs'));
assert.match(read('api/_version.js'),/APP_VERSION = '17\.0\.40'/);assert.match(read('api/_version.js'),/SECURITY_SCHEMA_VERSION = '17\.0\.40'/);assert.match(read('api/_pos-bridge-config.js'),/APP_RELEASE = '17\.0\.40'/);assert.match(read('src/core/appCore.js'),/CURRENT_VERSION = '17\.0\.40'/);
for(const file of ['test-tools/certification/groups.json','test-tools/regressions/registry.json','test-tools/certification/cost-performance-baselines.json'])assert.equal(json(file).release,version);
for(const file of ['src/core/needsAttention.cjs','src/core/restaurantKnowledgeGraph.cjs','src/core/smartPrepIntelligence.cjs','src/core/purchaseReconciliation.cjs','src/core/operationalHistoryIntelligence.cjs','src/core/firebaseCostDiagnostics.cjs','api/_security-maturity.cjs','scripts/86chaos-release-gate/certification-truth.cjs','src/core/requestOffValidation.shared.js','src/core/requestOffValidation.js'])assert.ok(fs.statSync(path.join(root,file)).isFile(),`${file} exists`);
const emergency=read('api/emergency-schedule-requestoff-17-0-40.test.cjs');for(const marker of ['staggered handoffs','backward/equal ranges','Ghost cancellation','sticky day header'])assert.ok(emergency.includes(marker),`emergency test contains ${marker}`);
const schedule=read('src/features/schedule.jsx');for(const marker of ['sortScheduleWarningsChronologically','validatePartialRequestOffTimeRange','requestOffApi(\'create\'','requestOffApi(\'ghost-cancel\'','schedule-builder-sticky-day-header','schedule-builder-header-scroll','schedule-builder-body-scroll'])assert.ok(schedule.includes(marker),`Schedule contains ${marker}`);
const warningCore=read('src/core/scheduleWarningControls.shared.js');for(const marker of ['measureCoverageForTarget','sortScheduleWarningsChronologically','minimumCoverage','maximumCoverage'])assert.ok(warningCore.includes(marker),`coverage engine contains ${marker}`);
const api=read('api/time-off-request.js');for(const marker of ['validatePartialRequestOffTimeRange','handleCreate','handleGhostCreate','handleGhostCancel'])assert.ok(api.includes(marker),`Request Off API contains ${marker}`);
const rules=read('firestore.rules');assert.ok(rules.includes('timeOffCreateRangeIsValid(request.resource.data)'));
const ruleTests=read('scripts/run-rules-tests.js');for(const marker of ['Request Off partial-day time-order validation','partial_backward_blocked','partial_equal_blocked','manager_cannot_bypass_partial_order'])assert.ok(ruleTests.includes(marker),`rules regression contains ${marker}`);
const app=read('src/App.js');assert.ok(app.includes('userGhostRequestOffPath'));assert.match(app,/wantsTimeOffData[\s\S]*!userGhostRequestOffPath/);
const styles=read('src/styles.css');assert.match(styles,/\.schedule-builder-sticky-day-header\s*\{[\s\S]*position:\s*sticky/);
const universe=read('scripts/86chaos-release-gate/release-test-universe.cjs');for(const n of [54,55])assert.match(universe,new RegExp(`tests/86chaos-release-gate/${n}-`),`browser regression ${n} is release-critical`);
const workflow=read('.github/workflows/testing-targeted-delta.yml');assert.ok(workflow.includes('[full-gate]'));assert.ok(workflow.includes('npm run test:play-store'));assert.ok(workflow.includes('Run 17.0.40 targeted delta only'));for(const file of ['54-emergency-schedule-requestoff.spec.cjs','55-full-surface-traceability.spec.cjs','06-request-off-events-integration.spec.cjs'])assert.ok(workflow.includes(file),`targeted browser delta contains ${file}`);
const trace=json('test-tools/certification/release-gate-traceability-17-0-40.json');assert.equal(trace.release,version);assert.ok(trace.coverageLayers.length>=15);assert.ok(trace.manualOnly.length>=1);for(const row of trace.coverageLayers)for(const file of row.tests||[])assert.ok(fs.existsSync(path.join(root,file)),`traceability target exists: ${file}`);
const ghostTest=read('tests/86chaos-full-audit/06-request-off-events-integration.spec.cjs');assert.match(ghostTest,/INTERNAL ASSERTION FAILED/);assert.match(ghostTest,/EXIT GHOST MODE/);assert.match(ghostTest,/restore the System Administrator session/);
const runner=read('RUN_86CHAOS_PLAY_STORE_RELEASE_GATE.ps1');for(const marker of ['playwrightStarted = $false','playwrightCompleted = $false','$RunnerState.playwrightCompleted = $true','$RunnerState.playwrightExitCode = $PlaywrightExit'])assert.ok(runner.includes(marker),`runner contains ${marker}`);
const identity=require('./86chaos-release-gate/source-identity.cjs').captureSourceIdentity(root),manifest=json('release-source-manifest.json');assert.equal(manifest.sourceHash,identity.sourceHash,'tracked release source manifest matches current source');
console.log('17.0.40 emergency schedule/request-off reliability and full-gate traceability validation passed.');
