#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),json=f=>JSON.parse(read(f)),version='17.0.53';
const p=json('package.json'),l=json('package-lock.json'),v=json('public/version.json');
assert.equal(p.version,version); assert.equal(l.version,version); assert.equal(l.packages[''].version,version); assert.equal(v.version,version); assert.equal(v.build,version);
assert.equal(p.scripts['test:source'],'node scripts/validate-17-0-53.js');
assert.equal(p.scripts['validate:17.0.53'],'node scripts/validate-17-0-53.js');
assert.equal(p.scripts['test:repair:17.0.53'],'npm run test:current-release-targeted');
assert.ok(p.scripts['test:current-release-targeted'].includes('api/release-gate-cascade-repair-17-0-53.test.cjs'));
assert.ok(p.scripts['test:current-release-targeted'].endsWith('node scripts/validate-17-0-53.js'));
assert.ok(read('api/_version.js').includes("const APP_VERSION = '17.0.53';"));
assert.ok(read('api/_version.js').includes("const SECURITY_SCHEMA_VERSION = '17.0.53';"));
assert.ok(read('api/_pos-bridge-config.js').includes("const APP_RELEASE = '17.0.53';"));
assert.ok(read('src/core/appCore.js').includes("export const CURRENT_VERSION = '17.0.53';"));
for(const f of ['src/core/customerHelpKnowledge.js','src/core/customerHelpKnowledge.cjs']) assert.ok(read(f).includes("const CUSTOMER_HELP_VERSION = '17.0.53';"));
for(const f of ['test-tools/certification/groups.json','test-tools/regressions/registry.json','test-tools/certification/cost-performance-baselines.json']) assert.equal(json(f).release,version);
assert.ok(read('src/core/schedulePdf.js').includes("document.setProducer('86 Chaos 17.0.53')"));
assert.ok(read('src/App.js').includes('window.setInterval(syncStoredLanguage, 200)'));
assert.ok(read('src/features/schedule.jsx').includes("orderByField: null"));
assert.ok(read('src/features/schedule.jsx').includes('deckIsSticky'));
assert.ok(read('tests/86chaos-new-implementations/08-phase1-spanish-interface.spec.cjs').includes("restore.selectOption('en')"));
assert.ok(read('api/release-gate-cascade-repair-17-0-53.test.cjs').includes('same-tab language state'));
const workflow=read('.github/workflows/testing-targeted-delta.yml');
assert.ok(workflow.includes('Run 17.0.53 targeted delta only'));
assert.ok(workflow.includes('08-phase1-spanish-interface.spec.cjs'));
console.log('17.0.53 release-gate state isolation and Schedule reliability validation passed.');
