#!/usr/bin/env node
'use strict';
const fs=require('node:fs');
const assert=require('node:assert/strict');
const read=f=>fs.readFileSync(f,'utf8');
const json=f=>JSON.parse(read(f));
const pkg=json('package.json'),lock=json('package-lock.json'),version=json('public/version.json');
assert.equal(pkg.version,'17.0.23');
assert.equal(lock.version,pkg.version);
assert.equal(lock.packages[''].version,pkg.version);
assert.equal(version.version,pkg.version);
assert.equal(version.build,pkg.version);
assert.equal(version.releaseTitle,'Request Off Cutoff and Blackout Policy');
assert.equal(pkg.scripts['test:source'],'node scripts/validate-17-0-23.js');
assert.equal(pkg.scripts['validate:17.0.23'],'node scripts/validate-17-0-23.js');
assert(pkg.scripts['test:repair:17.0.23']?.includes('time-off-policy-17-0-23.test.cjs'),'17.0.23 repair test covers Request Off policy behavior and authority');
const schedule=read('src/features/schedule.jsx');
const route=read('api/time-off-request.js');
const policy=read('src/core/timeOffPolicy.js');
const serverPolicy=read('api/_time-off-policy.cjs');
const voice=read('src/components/common.jsx');
assert(schedule.includes("requestOffApi('policy-save'"),'Request Off page saves policy through the protected API');
assert(schedule.includes("requestOffApi('policy-check'"),'Request Off submit rechecks policy server-side');
assert(schedule.includes('canConfigureRequestOffPolicy'),'Request Off policy UI has an explicit owner/admin authority gate');
assert(route.includes("action === 'policy-save'"),'Request Off API exposes protected policy save');
assert(route.includes("action === 'policy-check'"),'Request Off API exposes policy validation');
assert(route.includes('callerCanConfigurePolicy'),'server policy save uses strict owner/admin authority');
assert(serverPolicy.includes("role==='owner'||role==='admin'||role==='administrator'"),'server authority recognizes owner/admin roles');
assert(!/permissions\?\.(?:schedule|team|settings)/.test(policy),'client policy authority does not grant schedule/team/settings permission-only users policy control');
assert(voice.includes("action:'policy-check'"),'86 Voice Request Off respects the same cutoff and blackout policy');
// Preserve the release-gate repairs already carried by the baseline.
const releaseChecks=read('scripts/86chaos-release-gate/run-node-release-checks.cjs');
const full=read('RUN_86CHAOS_PLAY_STORE_RELEASE_GATE.ps1');
const layout=read('playwright.layout.config.cjs');
assert(!/mobile layout Playwright smoke/i.test(releaseChecks),'synchronous Node readiness runner no longer launches the browser smoke');
assert(full.includes("Set-RunnerPhase 'playwright-layout-smoke'"),'top-level gate records the layout-smoke phase');
assert(full.includes('$LayoutSmokeExit = Run-LiveStep "Mobile layout Playwright smoke"'),'top-level gate launches the layout smoke as a live step');
assert(layout.includes('globalTimeout:180000'),'layout smoke keeps the bounded 180-second global limit');
const execution=read('api/release-gate-execution-17-0-5.test.cjs');
assert(!execution.includes('assert.match(good.result.stdout,/source validation passed/)'),'source-validator execution stays independent of success prose');
const preflight=read('scripts/86chaos-release-gate/preflight-env.cjs');
assert(full.includes("SetEnvironmentVariable('CHAOS_EXPECTED_VERSION', $PackageVersion, 'Process')"),'full gate still pins expected version from package.json');
assert(preflight.includes("TARGET_ENV_KEYS.filter(key => key !== 'CHAOS_EXPECTED_VERSION')"),'full certification still ignores stale persisted expected-version conflicts');
for(const file of ['src/core/appCore.js','api/_version.js','api/_pos-bridge-config.js']) assert(read(file).includes("'17.0.23'"),`${file} carries 17.0.23`);
for(const file of ['test-tools/certification/groups.json','test-tools/regressions/registry.json','test-tools/certification/cost-performance-baselines.json']) assert.equal(json(file).release,pkg.version);
console.log('17.0.23 Request Off cutoff and blackout policy validation passed; this does not certify the release.');
