'use strict';
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const json = file => JSON.parse(read(file));
const version = '17.0.64';
const pkg = json('package.json');
const lock = json('package-lock.json');
assert.equal(pkg.version, version);
assert.equal(lock.version, version);
assert.equal(lock.packages[''].version, version);
assert.equal(json('public/version.json').version, version);
assert.match(read('src/core/appCore.js'), /CURRENT_VERSION = '17\.0\.64'/);
assert.match(read('api/_version.js'), /17\.0\.64/);
assert.equal(json('test-tools/certification/groups.json').release, version);
assert.equal(json('test-tools/certification/cost-performance-baselines.json').release, version);
assert.equal(json('test-tools/regressions/registry.json').release, version);
assert.equal(pkg.scripts['test:source'], 'node scripts/validate-17-0-64.js');
assert.equal(pkg.scripts['validate:17.0.64'], 'node scripts/validate-17-0-64.js');
assert.equal(pkg.scripts['test:repair:17.0.64'], 'npm run test:current-release-targeted');
assert.match(pkg.scripts['test:current-release-targeted'], /release-gate-emulator-runtime-boundaries-17-0-64\.test\.cjs/);
assert.ok(pkg.scripts['test:current-release-targeted'].endsWith('node scripts/validate-17-0-64.js'));
const target = read('src/core/firebaseTarget.js');
assert.match(target, /probe\('Storage',[\s\S]*\/v0\/b\//);
const requestOff = read('tests/e2e/schedule-request-off-management.spec.cjs');
assert.match(requestOff, /expectedFirebaseProject\(process\.env\)/);
assert.doesNotMatch(requestOff, /const QA_TEST_PROJECT_ID = ['"]chaos-test-d1601['"]/);
const core = read('src/core/appCore.js');
assert.ok(core.indexOf('if (isFirebaseEmulatorTarget)') < core.indexOf('enableMultiTabIndexedDbPersistence(db)'));
const universe = require('./86chaos-release-gate/release-test-universe.cjs');
const regression = 'tests/86chaos-release-gate/76-emulator-runtime-boundaries-17-0-64.spec.cjs';
assert.ok(universe.RELEASE_CRITICAL_SPECS.includes(regression));
assert.equal(fs.existsSync(path.join(root, 'api/release-gate-emulator-runtime-boundaries-17-0-64.test.cjs')), true);
assert.equal(fs.existsSync(path.join(root, regression)), true);
assert.match(read('.github/workflows/testing-targeted-delta.yml'), /76-emulator-runtime-boundaries-17-0-64\.spec\.cjs/);
assert.equal(read('src/core/customerHelpKnowledge.cjs').includes("CUSTOMER_HELP_VERSION = '17.0.64'"), true);
assert.equal(read('src/core/customerHelpKnowledge.js').includes("CUSTOMER_HELP_VERSION = '17.0.64'"), true);
console.log('86 Chaos 17.0.64 emulator release-gate cascade repair validation PASS');
