#!/usr/bin/env node
'use strict';
const fs = require('node:fs');
const assert = require('node:assert/strict');
const read = file => fs.readFileSync(file, 'utf8');
const json = file => JSON.parse(read(file));
const pkg = json('package.json');
const lock = json('package-lock.json');
const version = json('public/version.json');

assert.equal(pkg.scripts['test:source'], 'node scripts/validate-17-0-13.js');
assert.equal(pkg.version, '17.0.13');
assert.equal(lock.version, pkg.version);
assert.equal(lock.packages[''].version, pkg.version);
assert.equal(version.version, pkg.version);
assert.equal(version.releaseTitle, 'Idempotent Automated Release Resume Repair');
for (const file of ['src/core/appCore.js', 'api/_version.js', 'api/_pos-bridge-config.js']) assert(read(file).includes("'17.0.13'"));
for (const directory of ['src', 'api', 'scripts', 'test-tools', 'tests']) assert(fs.statSync(directory).isDirectory(), `${directory} is required`);
for (const file of ['firebase.json', 'vercel.json', 'firestore.rules', 'storage.rules', 'RUN_86CHAOS_PLAY_STORE_RELEASE_GATE.ps1', 'RUN_86CHAOS_UPDATE_TEST_DEPLOY.ps1', 'RELEASE_TEST_POLICY.md', '.gitignore', 'release-source-manifest.json']) assert(fs.statSync(file).isFile(), `${file} is required`);
assert.equal(json('test-tools/certification/groups.json').release, pkg.version);
assert.equal(json('test-tools/regressions/registry.json').release, pkg.version);
assert.equal(json('test-tools/certification/cost-performance-baselines.json').release, pkg.version);

const schedule = read('src/features/schedule.jsx');
assert(schedule.includes('safeScheduleEventRows(rawEvents)'));
assert(schedule.includes("events.filter(e => e.type === 'special_event' && e.date?.startsWith(eventsCalMonth))"));
const referrer = read('scripts/86chaos-release-gate/firebase-auth-referrer.cjs');
assert(referrer.includes('CHAOS_FIREBASE_AUTH_REFERRER_URL'));
assert(referrer.includes('86chaos-git-testing-cheers-portal-s-projects.vercel.app'));
assert(referrer.includes('chaos-test-d1601'));
assert(referrer.includes('cheers-34b8d'));
const runner = read('RUN_86CHAOS_PLAY_STORE_RELEASE_GATE.ps1');
assert(runner.includes('TOTAL ELAPSED TIME:'));
assert(runner.includes('Update-TotalTimingEvidence'));
assert(runner.lastIndexOf('TOTAL ELAPSED TIME:') > runner.lastIndexOf('Exported:'));
const safety = read('scripts/verify-repository-safety.cjs');
assert(safety.includes("allowedTrackedExclusions=new Set(['release-source-manifest.json'])"));
assert(pkg.scripts['test:repair:17.0.13'].includes('api/firebase-auth-referrer-17-0-11.test.cjs'));
assert(pkg.scripts['test:repair:17.0.13'].includes('api/playwright-progress-17-0-11.test.cjs'));
assert(pkg.scripts['test:repair:17.0.13'].includes('api/release-workflow-17-0-11.test.cjs'));

const historicalIdentity = read('api/repair-17-0-5.test.cjs');
assert(historicalIdentity.includes('release-source-manifest.json'));
assert(historicalIdentity.includes('CHAOS_STRICT_VERCEL_BUILD_WORKSPACE'));
assert(historicalIdentity.includes("workspaceVerification,'vercel-git-metadata'"));
assert(pkg.scripts['test:repair:17.0.13'].includes('api/source-identity-history-17-0-12.test.cjs'));
assert(pkg.scripts['test:repair:17.0.13'].includes('api/repair-17-0-5.test.cjs'));
assert(json('test-tools/regressions/registry.json').defects.some(row => row.defectId === 'RG-HISTORICAL-VERCEL-WORKSPACE-IDENTITY-1712' && row.fixedVersion === '17.0.12'));
assert(read('RUN_86CHAOS_UPDATE_TEST_DEPLOY.ps1').includes('Vercel wait attempt'));
assert(pkg.scripts['test:repair:17.0.13'].includes('api/release-workflow-resume-17-0-13.test.cjs'));
assert(json('test-tools/regressions/registry.json').defects.some(row => row.defectId === 'RG-AUTOMATED-WORKFLOW-IDEMPOTENT-RESUME-1713' && row.fixedVersion === '17.0.13'));
const updater = read('RUN_86CHAOS_UPDATE_TEST_DEPLOY.ps1');
assert(updater.includes('Resume mode:'));
assert(updater.includes('Upgrade mode:'));
assert(updater.includes('validate:$ExpectedVersion'));
assert(updater.includes('test:repair:$ExpectedVersion'));
console.log('17.0.13 source validation passed; this does not certify the release.');
