#!/usr/bin/env node
'use strict';
const fs=require('node:fs');
const assert=require('node:assert/strict');
const read=f=>fs.readFileSync(f,'utf8');
const json=f=>JSON.parse(read(f));
const pkg=json('package.json'),lock=json('package-lock.json'),version=json('public/version.json');
assert.equal(pkg.version,'17.0.16');
assert.equal(lock.version,pkg.version);
assert.equal(lock.packages[''].version,pkg.version);
assert.equal(version.version,pkg.version);
assert.equal(version.build,pkg.version);
assert.equal(pkg.scripts['test:source'],'node scripts/validate-17-0-16.js');
assert.equal(pkg.scripts['validate:17.0.16'],'node scripts/validate-17-0-16.js');
for(const file of ['src/core/appCore.js','api/_version.js','api/_pos-bridge-config.js']) assert(read(file).includes("'17.0.16'"),`${file} carries 17.0.16`);
const service=read('api/_schedule-publish-service.cjs');
assert(service.includes('buildFinalPublicationCounts'),'server publishes authoritative outcome counts');
assert(service.includes('verifiedNewCount'),'server returns verified new-shift count');
assert(service.includes('verifiedRepairCount'),'server returns verified repair count');
assert(service.includes('unchangedCount'),'server returns authoritative unchanged count');
assert(service.includes('unresolvedEmployeeCount'),'server returns employee-review count');
assert(service.includes("_source:'user-identity-fallback'"),'17.0.15 roster parity repair preserved');
const schedule=read('src/features/schedule.jsx');
assert(schedule.includes('publishResult.verifiedNewCount'),'client uses server new count');
assert(schedule.includes('publishResult.verifiedRepairCount'),'client uses server repair count');
assert(schedule.includes('Schedule Already Current'),'client has accurate no-op completion state');
assert(schedule.includes('Publish Needs Employee Review'),'client exposes unresolved server rows');
assert(schedule.includes('getDocsFromServer(candidateQuery)'),'authoritative candidate reads preserved');
const pwa=read('tests/86chaos-release-gate/27-pwa-browser-icon-matrix.spec.cjs');
assert(!pwa.includes('{ page,'),'request-only PWA repair preserved');
for(const file of ['test-tools/certification/groups.json','test-tools/regressions/registry.json','test-tools/certification/cost-performance-baselines.json']) assert.equal(json(file).release,pkg.version);
console.log('17.0.16 targeted source validation passed; this is not full release certification.');
