#!/usr/bin/env node
'use strict';
const fs=require('node:fs');
const assert=require('node:assert/strict');
const read=f=>fs.readFileSync(f,'utf8');
const json=f=>JSON.parse(read(f));
const pkg=json('package.json'),lock=json('package-lock.json'),version=json('public/version.json');
assert.equal(pkg.version,'17.0.17');
assert.equal(lock.version,pkg.version);
assert.equal(lock.packages[''].version,pkg.version);
assert.equal(version.version,pkg.version);
assert.equal(version.build,pkg.version);
assert.equal(version.releaseTitle,'Schedule Builder Navigation and Legacy Publish Identity Repair');
assert.equal(pkg.scripts['test:source'],'node scripts/validate-17-0-17.js');
assert.equal(pkg.scripts['validate:17.0.17'],'node scripts/validate-17-0-17.js');
for(const file of ['src/core/appCore.js','api/_version.js','api/_pos-bridge-config.js']) assert(read(file).includes("'17.0.17'"),`${file} carries 17.0.17`);
const app=read('src/App.js');
const navStart=app.indexOf('const transitionActiveTabState = useCallback((nextTab) => {');
const navEnd=app.indexOf('const disarmPwaBackExit',navStart);
assert(navStart>=0&&navEnd>navStart,'top-level navigation block exists');
const nav=app.slice(navStart,navEnd);
assert(!nav.includes('React.startTransition'),'top-level tab routing is not deferred');
assert(/activeTabStateRef\.current = normalized;\s*setActiveTabState\(normalized\);/.test(nav),'top-level tab state commits directly');
const service=read('api/_schedule-publish-service.cjs');
assert(service.includes('resolveEmployeeForPublishShift'),'server has publication-specific legacy identity resolver');
assert(service.includes("_source:'shift-identity-fallback'"),'server mirrors legacy shift roster identity fallback');
assert(service.includes('canonicalRosterPerson'),'server canonicalizes workspace-member/account identity without blank-field loss');
assert(service.includes('identityIntersects'),'server refuses to synthesize over real matching roster identities');
assert(service.includes('buildFinalPublicationCounts'),'17.0.16 authoritative result counts preserved');
assert(service.includes('verifiedNewCount')&&service.includes('verifiedRepairCount')&&service.includes('unresolvedEmployeeCount'),'server result summary contract preserved');
assert(service.includes("_source:'user-identity-fallback'"),'17.0.15 tenant-user identity fallback preserved');
const schedule=read('src/features/schedule.jsx');
assert(schedule.includes('publishResult.verifiedNewCount'),'client uses authoritative server new count');
assert(schedule.includes('Publish Needs Employee Review'),'employee-review completion state preserved');
assert(schedule.includes('getDocsFromServer(candidateQuery)'),'authoritative candidate reads preserved');
const pwa=read('tests/86chaos-release-gate/27-pwa-browser-icon-matrix.spec.cjs');
assert(!pwa.includes('{ page,'),'request-only PWA repair preserved');
const vercel=json('vercel.json');
assert.equal(vercel.github?.autoAlias,true,'Vercel Git auto-alias remains enabled in source config');
for(const file of ['test-tools/certification/groups.json','test-tools/regressions/registry.json','test-tools/certification/cost-performance-baselines.json']) assert.equal(json(file).release,pkg.version);
console.log('17.0.17 targeted source validation passed; this is not full release certification.');
