#!/usr/bin/env node
'use strict';
const fs = require('node:fs');
const assert = require('node:assert/strict');
const read = file => fs.readFileSync(file, 'utf8');
const json = file => JSON.parse(read(file));
const pkg = json('package.json');
const lock = json('package-lock.json');
const version = json('public/version.json');

assert.equal(pkg.scripts['test:source'], 'node scripts/validate-17-0-14.js');
assert.equal(pkg.version, '17.0.14');
assert.equal(lock.version, pkg.version);
assert.equal(lock.packages[''].version, pkg.version);
assert.equal(version.version, pkg.version);
assert.equal(version.releaseTitle, 'Release Check Streaming, Timeout, and Orphan Process Repair');
for (const file of ['src/core/appCore.js', 'api/_version.js', 'api/_pos-bridge-config.js']) assert(read(file).includes("'17.0.14'"));
for (const directory of ['src', 'api', 'scripts', 'test-tools', 'tests']) assert(fs.statSync(directory).isDirectory(), `${directory} is required`);
for (const file of ['firebase.json', 'vercel.json', 'firestore.rules', 'storage.rules', 'RUN_86CHAOS_PLAY_STORE_RELEASE_GATE.ps1', 'RUN_86CHAOS_UPDATE_TEST_DEPLOY.ps1', 'RELEASE_TEST_POLICY.md', 'RELEASE_17_0_14.md', '.gitignore', 'release-source-manifest.json']) assert(fs.statSync(file).isFile(), `${file} is required`);
assert.equal(json('test-tools/certification/groups.json').release, pkg.version);
assert.equal(json('test-tools/regressions/registry.json').release, pkg.version);
assert.equal(json('test-tools/certification/cost-performance-baselines.json').release, pkg.version);

const runner = read('scripts/86chaos-release-gate/run-node-release-checks.cjs');
const streamed = read('scripts/86chaos-release-gate/streamed-command-runner.cjs');
assert(runner.includes('runStreamedCommand'));
assert(runner.includes('STILL RUNNING'));
assert(runner.includes("result.status === 'timedOut'"));
assert(runner.includes('STOPPING remaining local release checks'));
assert(!runner.includes('spawnSync(row.command'));
assert(streamed.includes("'taskkill'"));
assert(streamed.includes("'/T', '/F'"));
assert(streamed.includes("process.kill(-numericPid, 'SIGKILL')"));
assert(streamed.includes('Command timed out after'));
assert(pkg.scripts['test:hostile:contracts'].includes('--test-concurrency=1'));
for (const file of ['api/source-identity-history-17-0-12.test.cjs', 'api/release-workflow-resume-17-0-13.test.cjs', 'api/release-check-streaming-17-0-14.test.cjs']) assert(pkg.scripts['test:hostile:contracts'].includes(file));
assert(pkg.scripts['test:hostile'].includes('--test-concurrency=1 api/permission-matrix-17-0-0.test.cjs'));
assert(pkg.scripts['test:release:fast'].includes('validate:17.0.14'));
assert(pkg.scripts['test:new-implementations'].includes('validate:17.0.14'));
assert(pkg.scripts['test:repair:17.0.14'].includes('api/release-check-streaming-17-0-14.test.cjs'));
assert(json('test-tools/regressions/registry.json').defects.some(row => row.defectId === 'RG-RELEASE-CHECK-STREAMING-TIMEOUT-1714' && row.fixedVersion === '17.0.14'));

const schedule = read('src/features/schedule.jsx');
assert(schedule.includes('safeScheduleEventRows(rawEvents)'));
assert(schedule.includes("events.filter(e => e.type === 'special_event' && e.date?.startsWith(eventsCalMonth))"));
const referrer = read('scripts/86chaos-release-gate/firebase-auth-referrer.cjs');
assert(referrer.includes('CHAOS_FIREBASE_AUTH_REFERRER_URL'));
assert(referrer.includes('86chaos-git-testing-cheers-portal-s-projects.vercel.app'));
assert(referrer.includes('chaos-test-d1601'));
assert(referrer.includes('cheers-34b8d'));

const playStoreRunner = read('RUN_86CHAOS_PLAY_STORE_RELEASE_GATE.ps1');
assert(playStoreRunner.includes('TOTAL ELAPSED TIME:'));
assert(playStoreRunner.includes('Update-TotalTimingEvidence'));
assert(playStoreRunner.lastIndexOf('TOTAL ELAPSED TIME:') > playStoreRunner.lastIndexOf('Exported:'));
const safety = read('scripts/verify-repository-safety.cjs');
assert(safety.includes("allowedTrackedExclusions=new Set(['release-source-manifest.json'])"));
const updater = read('RUN_86CHAOS_UPDATE_TEST_DEPLOY.ps1');
assert(updater.includes("[string]$ExpectedVersion = '17.0.14'"));
assert(updater.includes('Resume mode:'));
assert(updater.includes('Upgrade mode:'));
assert(updater.includes('Vercel wait attempt'));
assert(updater.includes('validate:$ExpectedVersion'));
assert(updater.includes('test:repair:$ExpectedVersion'));
assert(updater.includes("@('run', 'test:play-store')"));
assert(!/test:play-store:(?:failed|delta|repair)/.test(updater));
assert(updater.includes("$env:GIT_PAGER = 'cat'"));
assert(updater.includes("$env:PAGER = 'cat'"));
assert(updater.includes('--no-pager'));
assert(updater.includes("@('switch', 'testing')"));
assert(updater.includes("$env:NODE_OPTIONS = '--max-old-space-size=4096'"));
assert(updater.includes("$env:GENERATE_SOURCEMAP = 'false'"));
assert(updater.includes("$env:CHAOS_RELEASE_CHECK_HEARTBEAT_MS = '15000'"));

console.log('17.0.14 source validation passed; this does not certify the release.');
