'use strict';
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const json = file => JSON.parse(read(file));
const version = '17.0.58';
const pkg = json('package.json');
const lock = json('package-lock.json');
assert.equal(pkg.version, version);
assert.equal(lock.version, version);
assert.equal(lock.packages[''].version, version);
assert.equal(json('public/version.json').version, version);
assert.match(read('src/core/appCore.js'), /CURRENT_VERSION = '17\.0\.58'/);
assert.match(read('api/_version.js'), /17\.0\.58/);
assert.equal(json('test-tools/certification/groups.json').release, version);
assert.equal(json('test-tools/certification/cost-performance-baselines.json').release, version);
assert.equal(pkg.scripts['test:source'], 'node scripts/validate-17-0-58.js');
assert.equal(pkg.scripts['validate:17.0.58'], 'node scripts/validate-17-0-58.js');
assert.equal(pkg.scripts['test:repair:17.0.58'], 'npm run test:current-release-targeted');
assert.match(pkg.scripts['test:current-release-targeted'], /release-gate-emulator-target-coherence-17-0-58/);
assert.ok(pkg.scripts['test:current-release-targeted'].endsWith('node scripts/validate-17-0-58.js'));
const failedConfig = read('playwright.failed-release.config.cjs');
assert.ok(failedConfig.startsWith("require('./scripts/86chaos-firebase-target.cjs').applyFirebaseEmulatorEnv(process.env);"));
assert.ok(failedConfig.indexOf('applyFirebaseEmulatorEnv(process.env)') < failedConfig.indexOf('const baseURL ='));
const bridgeSpec = read('tests/86chaos-release-gate/66-firebase-emulator-bridge-17-0-54.spec.cjs');
assert.match(bridgeSpec, /getFirebaseTarget\(process\.env\)\.emulator/);
assert.doesNotMatch(bridgeSpec, /REACT_APP_86CHAOS_FIREBASE_TARGET \|\| 'live'/);
const safeguards = read('tests/86chaos-release-gate/61-release-gate-surgical-repairs-17-0-46.spec.cjs');
assert.doesNotMatch(safeguards, /toBe\(['"]17\.0\.52['"]\)/);
const universe = require('./86chaos-release-gate/release-test-universe.cjs');
const regression = 'tests/86chaos-release-gate/70-release-gate-emulator-target-coherence-17-0-58.spec.cjs';
assert.ok(universe.RELEASE_CRITICAL_SPECS.includes(regression));
assert.ok(universe.PWA_SPEC_PATTERN.test(regression.replace(/^tests\//, '')));
assert.equal(fs.existsSync(path.join(root, 'api/release-gate-emulator-target-coherence-17-0-58.test.cjs')), true);
assert.equal(fs.existsSync(path.join(root, regression)), true);
console.log('86 Chaos 17.0.58 failed+new Firebase target coherence validation PASS');
