#!/usr/bin/env node
'use strict';
const fs = require('node:fs');
const assert = require('node:assert/strict');
const read = file => fs.readFileSync(file, 'utf8');
const json = file => JSON.parse(read(file));
const pkg = json('package.json');
const lock = json('package-lock.json');
const version = json('public/version.json');
assert.equal(pkg.version, '17.0.14');
assert.equal(lock.version, pkg.version);
assert.equal(lock.packages[''].version, pkg.version);
assert.equal(version.version, pkg.version);
assert.equal(version.build, pkg.version);
assert.equal(pkg.scripts['test:source'], 'node scripts/validate-17-0-14.js');
assert.equal(pkg.scripts['validate:17.0.14'], 'node scripts/validate-17-0-14.js');
for (const file of ['src/core/appCore.js','api/_version.js','api/_pos-bridge-config.js']) assert(read(file).includes("'17.0.14'"), `${file} carries 17.0.14`);
const schedule = read('src/features/schedule.jsx');
assert(schedule.includes('getDocsFromServer(candidateQuery)'), 'schedule publish uses server-authoritative candidate reads');
assert(schedule.includes('const confirmedEvidenceRows = [...updatePlan, ...alreadyValid];'), 'schedule publish confirms unchanged selected shifts too');
assert(schedule.includes('isIntentionalOpenScheduleShift(shift)'), 'schedule publish preserves intentional open shifts');
assert(schedule.includes('desiredEmployeeIdentity: item.intentionalOpen ? null'), 'open-shift evidence matches server canonical fingerprinting');
const core = read('api/_schedule-publish-core.cjs');
assert(core.includes('unchangedEvidenceById'), 'server tracks authoritative unchanged evidence');
assert(core.includes('missingEvidenceIds'), 'server still rejects missing writable evidence');
assert(core.includes('unavailableEvidenceIds'), 'server rejects non-authoritative extra evidence');
const planner = read('src/core/scheduleQueryPlanner.js');
assert.match(planner, /return wanted && \(!actual \|\| wanted !== actual\);/);
const pwa = read('tests/86chaos-release-gate/27-pwa-browser-icon-matrix.spec.cjs');
assert(!pwa.includes('{ page,'), 'PWA metadata matrix is request-only');
assert(pwa.includes('request.get(rootUrl'), 'PWA metadata matrix verifies app-shell metadata by request');
for (const file of ['playwright.play-store-release.config.cjs','playwright.failed-release.config.cjs']) assert(!read(file).includes("{ name: 'firefox-pwa', retries:"), `${file} has no Firefox-only retry`);
for (const file of ['test-tools/certification/groups.json','test-tools/regressions/registry.json','test-tools/certification/cost-performance-baselines.json']) assert.equal(json(file).release, pkg.version);
console.log('17.0.14 targeted source validation passed; this is not full release certification.');
