#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),json=f=>JSON.parse(read(f)),version='17.0.52';
const p=json('package.json'),l=json('package-lock.json'),v=json('public/version.json');
assert.equal(p.version,version); assert.equal(l.version,version); assert.equal(l.packages[''].version,version); assert.equal(v.version,version); assert.equal(v.build,version);
assert.equal(p.scripts['test:source'],'node scripts/validate-17-0-52.js');
assert.equal(p.scripts['validate:17.0.52'],'node scripts/validate-17-0-52.js');
assert.equal(p.scripts['test:repair:17.0.52'],'npm run test:current-release-targeted');
assert.ok(p.scripts['test:current-release-targeted'].includes('api/system-admin-firebase-cost-runtime-17-0-52.test.cjs'));
assert.ok(p.scripts['test:current-release-targeted'].includes('api/system-admin-runtime-boundary-17-0-51.test.cjs'));
assert.ok(p.scripts['test:current-release-targeted'].endsWith('node scripts/validate-17-0-52.js'));
assert.ok(read('api/_version.js').includes("const APP_VERSION = '17.0.52';"));
assert.ok(read('api/_version.js').includes("const SECURITY_SCHEMA_VERSION = '17.0.52';"));
assert.ok(read('api/_pos-bridge-config.js').includes("const APP_RELEASE = '17.0.52';"));
assert.ok(read('src/core/appCore.js').includes("export const CURRENT_VERSION = '17.0.52';"));
for(const f of ['src/core/customerHelpKnowledge.js','src/core/customerHelpKnowledge.cjs']) assert.ok(read(f).includes("const CUSTOMER_HELP_VERSION = '17.0.52';"));
for(const f of ['test-tools/certification/groups.json','test-tools/regressions/registry.json','test-tools/certification/cost-performance-baselines.json']) assert.equal(json(f).release,version);
assert.ok(read('src/core/schedulePdf.js').includes("document.setProducer('86 Chaos 17.0.52')"));

const management=read('src/features/management.jsx');
const browserModule=read('src/core/firebaseCostDiagnostics.js');
const cjsModule=read('src/core/firebaseCostDiagnostics.cjs');
const browser=read('tests/86chaos-release-gate/65-system-admin-firebase-cost-runtime-17-0-52.spec.cjs');
assert.ok(management.includes("import { buildFirebaseCostDiagnostics } from '../core/firebaseCostDiagnostics.js';"));
assert.ok(!management.includes("firebaseCostDiagnosticsHelpers"));
assert.ok(!management.includes("firebaseCostDiagnostics.cjs"));
assert.ok(browserModule.includes('function buildFirebaseCostDiagnostics'));
assert.ok(browserModule.includes('export { buildFirebaseCostDiagnostics };'));
assert.ok(!browserModule.includes('module.exports'));
assert.ok(cjsModule.includes('module.exports = { buildFirebaseCostDiagnostics };'));
assert.ok(management.includes('useMemo(() => buildFirebaseCostDiagnostics(getFirebaseUsageDiagnostics?.() || {}, { rtdbKnown:false })'));
assert.ok(browser.includes('firebase-cost-observability'));
assert.ok(browser.includes('ut is not a function'));
assert.ok(browser.includes('not a function'));
assert.ok(read('scripts/86chaos-release-gate/release-test-universe.cjs').includes('65-system-admin-firebase-cost-runtime-17-0-52.spec.cjs'));
const workflow=read('.github/workflows/testing-targeted-delta.yml');
assert.ok(workflow.includes('Run 17.0.52 targeted delta only'));
assert.ok(workflow.includes('65-system-admin-firebase-cost-runtime-17-0-52.spec.cjs'));
console.log('17.0.52 System Administrator Firebase cost-diagnostics runtime validation passed.');
