'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {inactiveRecord,profileForWorkspace,legacyMembershipFallbackAllowed}=require('./_chaos-admin');
test('canonical inactive and removed memberships are inactive authority evidence',()=>{for(const row of [{isActive:false},{status:'revoked'},{removed:true},{disabled:true}])assert.equal(inactiveRecord(row),true);});
test('inactive canonical membership cannot contribute legacy owner authority',()=>{const user={id:'u',restaurantId:'r',isOwner:true,permissions:{settings:true}};const scoped=profileForWorkspace(user,{isActive:false,isOwner:true,permissions:{settings:true}},'r');assert.equal(scoped.isActive,false);});
test('active canonical role remains tenant scoped',()=>{const user={id:'u',restaurantId:'primary',isOwner:true};const scoped=profileForWorkspace(user,{isActive:true,isAdmin:true,permissions:{schedule:true}},'secondary');assert.equal(scoped.isAdmin,true);assert.equal(scoped.isOwner,false);assert.equal(scoped.restaurantId,'secondary');});
test('canonical staff never inherits legacy admin or elevated permissions',()=>{const user={id:'u',restaurantId:'r',isAdmin:true,isOwner:true,permissions:{settings:true,team:true}};const scoped=profileForWorkspace(user,{isActive:true,role:'Staff',isAdmin:false,isOwner:false,permissions:{schedule:true}},'r');assert.equal(scoped.isAdmin,false);assert.equal(scoped.isOwner,false);assert.deepEqual(scoped.permissions,{schedule:true});assert.equal(scoped.authoritySource,'canonical-workspace-member');});
test('legacy fallback is explicit, primary-only, and unavailable after migration evidence',()=>{assert.equal(legacyMembershipFallbackAllowed({restaurantId:'r',legacyMembershipFallback:true},'r'),true);assert.equal(legacyMembershipFallbackAllowed({restaurantId:'r',legacyMembershipFallback:true,workspaceIds:['r']},'r'),false);assert.equal(legacyMembershipFallbackAllowed({restaurantId:'r',legacyMembershipFallback:true,membershipMigrationVersion:2},'r'),false);assert.equal(profileForWorkspace({id:'u',restaurantId:'r',isAdmin:true},null,'r').isAdmin,false);});
test('independent canonical fixtures preserve owner/admin distinctions and schedule-only authority',()=>{const fixtures={staff:{role:'Staff',permissions:{}},manager:{role:'Manager',permissions:{schedule:true}},admin:{role:'Administrator',isAdmin:true,permissions:{}},owner:{role:'Owner',isOwner:true,accountOwner:true,permissions:{}},scheduleOnly:{role:'Staff',permissions:{schedule:true}}};for(const [name,member] of Object.entries(fixtures)){const scoped=profileForWorkspace({id:name,email:`${name}@example.invalid`,isAdmin:name==='staff'}, {isActive:true,...member},'r');assert.equal(scoped.isAdmin,member.isAdmin===true,name);assert.equal(scoped.isOwner,member.isOwner===true||member.accountOwner===true,name);if(name==='scheduleOnly')assert.equal(scoped.permissions.schedule,true);}});
