'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const intelligence = require('../src/core/intelligenceConnections.cjs');
const { buildSmartPrepRecommendations } = require('../src/core/smartPrepIntelligence.cjs');
const { buildOperationalHistory } = require('../src/core/operationalHistoryIntelligence.cjs');
const owner = { restaurantId:'r1', id:'owner', isOwner:true };
const resolved = { resolved:true, data:[], stale:false };
const recipes = [{ id:'burger', restaurantId:'r1', title:'Burger' }];
const sales = ['2026-09-10','2026-09-17','2026-09-24','2026-10-01'].map((date,i) => ({ id:`day${i}`,restaurantId:'r1',date,grossSales:100+(i*50),lineItems:[{recipeId:'burger',quantity:10+i,unit:'each'}] }));
const history = () => intelligence.normalizeItemSalesHistory({workspaceId:'r1',sales,recipes,targetDate:'2026-10-08',sourceState:{...resolved,data:sales},limit:400});
test('bulk recipe weights cannot silently become sold servings',()=>{const report=intelligence.normalizeItemSalesHistory({workspaceId:'r1',sales,recipes:[{...recipes[0],batchYieldUnit:'lb'}],targetDate:'2026-10-08',sourceState:resolved});assert.equal(report.rows.length,0);assert.equal(report.complete,false);});
test('stale comparable item history is insufficient rather than a zero forecast',()=>{const prep=buildSmartPrepRecommendations({workspaceId:'r1',targetDate:'2026-10-08',recipes,salesHistory:['2026-07-09','2026-07-16','2026-07-23'].map(date=>({restaurantId:'r1',recipeId:'burger',date,quantity:5}))});assert.equal(prep.recommendations[0].state,'insufficient-data');assert.equal(prep.recommendations[0].recommendedQuantity,null);assert.match(prep.recommendations[0].reason,/28 days old/);});

test('item history spans prior months and resolves real recipe identities', () => {
  const report=history();assert.equal(report.complete,true);assert.equal(report.rows.length,4);
  const prep=buildSmartPrepRecommendations({workspaceId:'r1',targetDate:'2026-10-08',recipes,salesHistory:report.rows});
  assert.equal(prep.recommendations[0].state,'recommendation');assert.equal(prep.recommendations[0].dataWindow.comparableDays,4);
});
test('item history never invents item demand from aggregate sales',()=>{const report=intelligence.normalizeItemSalesHistory({workspaceId:'r1',sales:[{restaurantId:'r1',date:'2026-10-01',grossSales:500}],recipes,targetDate:'2026-10-08',sourceState:resolved});assert.equal(report.rows.length,0);assert.equal(report.aggregateOnlyDays,1);});
test('explicit zero item demand survives normalization',()=>{const report=intelligence.normalizeItemSalesHistory({workspaceId:'r1',sales:sales.map(row=>({...row,lineItems:[{recipeId:'burger',quantity:0}]})),recipes,targetDate:'2026-10-08',sourceState:resolved});assert.equal(report.rows[0].quantity,0);assert.equal(report.complete,true);});
test('refunds, invalid quantities, unknown units and ambiguous names are not zero sales',()=>{
  for(const item of [{recipeId:'burger',quantity:-2},{recipeId:'burger',quantity:'bad'},{recipeId:'burger',quantity:2,unit:'lb'},{itemName:'Burger',quantity:2}]) {
    const report=intelligence.normalizeItemSalesHistory({workspaceId:'r1',sales:[{restaurantId:'r1',date:'2026-10-01',lineItems:[item]}],recipes:[...recipes,{id:'other',restaurantId:'r1',title:'Burger'}],targetDate:'2026-10-08',sourceState:resolved});assert.equal(report.rows.length,0);assert.equal(report.complete,false);
  }
});
test('tenant, child tenant, future dates and invalid calendar dates are excluded',()=>{
  const rows=[...sales,{...sales[0],restaurantId:'r2'},{...sales[0],date:'2026-10-15'},{...sales[0],date:'2026-02-30'},{...sales[0],id:'foreign-child',lineItems:[{restaurantId:'r2',recipeId:'burger',quantity:99}]}];
  const report=intelligence.normalizeItemSalesHistory({workspaceId:'r1',sales:rows,recipes,targetDate:'2026-10-08',sourceState:resolved});assert.equal(report.rows.length,4);assert.equal(report.rows.some(row=>row.quantity===99),false);
});
test('same receipt line retries deduplicate without deleting separate lines',()=>{const a={...sales[0],sourceId:'receipt1'};const report=intelligence.normalizeItemSalesHistory({workspaceId:'r1',sales:[a,a,{...a,id:'second',sourceId:'receipt2'}],recipes,targetDate:'2026-10-08',sourceState:resolved});assert.equal(report.rows.length,2);});
test('loading, stale, query errors and the row cap fail completeness closed',()=>{for(const state of [{resolved:false},{resolved:true,stale:true},{resolved:true,error:'offline'}])assert.equal(intelligence.sourceCompleteness(state,400).complete,false);assert.equal(intelligence.sourceCompleteness({...resolved,data:Array(400).fill({})},400).complete,false);});
test('snapshot records only shared operations summaries and respects write authority',()=>{
  const snapshot=intelligence.buildReadinessSnapshot({actor:owner,workspaceId:'r1',date:'2026-10-08',readiness:{categories:[{key:'inventory',label:'Inventory',status:'attention',score:60,reason:'private product price'},{key:'financial',status:'critical',reason:'private revenue'},{key:'system',reason:'password=secret'}]},existingSnapshots:[]});
  assert.equal(snapshot.type,'readiness_snapshot');assert.equal(snapshot.snapshots.length,1);assert.equal(JSON.stringify(snapshot).includes('private'),false);assert.equal(JSON.stringify(snapshot).includes('secret'),false);
  assert.throws(()=>intelligence.buildReadinessSnapshot({actor:{role:'manager',restaurantId:'r1'},workspaceId:'r1',date:'2026-10-08',readiness:{}}),/permission/i);
});
test('duplicate same-day snapshot is a no-op',()=>{const args={actor:owner,workspaceId:'r1',date:'2026-10-08',readiness:{categories:[{key:'prep',label:'Prep',status:'attention',score:70}]}};const snapshot=intelligence.buildReadinessSnapshot(args);assert.equal(intelligence.buildReadinessSnapshot({...args,existingSnapshots:[{...snapshot,id:'saved'}]}),null);});
test('real saved readiness, approved receipts, and classified alerts feed History',()=>{
  const input=intelligence.buildHistoryInputs({workspaceId:'r1',events:[{id:'snapshot',restaurantId:'r1',type:'readiness_snapshot',date:'2026-10-01',snapshots:[{key:'prep',status:'attention'}]}],invoices:[{id:'invoice',restaurantId:'r1',status:'approved',approvedAt:'2026-10-01',lineItems:[{matchedItemId:'stock',approvedStockQuantity:2}]}],alerts:[{id:'err',restaurantId:'r1',createdAt:{seconds:1790812800},errorCategory:'sync',title:'Sync issue',detail:'password=secret'}]});
  const report=buildOperationalHistory({workspaceId:'r1',actor:owner,now:'2026-10-08T23:59:59Z',...input});assert.ok(report.events.some(row=>row.category==='readiness'));assert.ok(report.events.some(row=>row.category==='receiving'));assert.ok(report.events.some(row=>row.category==='error'));assert.equal(JSON.stringify(report).includes('secret'),false);
});
const forecastArgs=()=>({workspaceId:'r1',actor:owner,currentDate:'2026-10-08',dates:['2026-10-08'],sales,sourceState:{...resolved,data:sales},coverageTargets:[{id:'cook',restaurantId:'r1',dayIndex:4,role:'Cook',count:4,startTime:'09:00',endTime:'17:00'}],shifts:[]});
test('forecast explains comparable sales and configured role coverage',()=>{const report=intelligence.buildScheduleForecast(forecastArgs());assert.equal(report.allowed,true);assert.equal(report.rows[0].state,'recommendation');assert.equal(report.rows[0].baselineCount,4);assert.equal(report.rows[0].forecastCount,5);assert.equal(report.rows[0].needed,5);assert.equal(report.rows[0].evidence.dates.length,4);assert.equal(report.automaticPublish,false);});
test('forecast explicitly refuses insufficient, stale, incomplete and unauthorized evidence',()=>{
  for(const patch of [{sales:sales.slice(-1)},{sourceState:{resolved:false}},{sales:sales.map(row=>({...row,date:row.date.replace('09','07').replace('10','08')}))},{actor:{restaurantId:'r1',role:'staff'}},{actor:{...owner,restaurantId:'r2'}}]) {const report=intelligence.buildScheduleForecast({...forecastArgs(),...patch});assert.equal(report.rows.some(row=>row.state==='recommendation'),false);}
});
test('forecast only counts overlapping role coverage in the current workspace',()=>{const args=forecastArgs();args.shifts=[{id:'one',restaurantId:'r1',date:'2026-10-08',role:'Cook',startTime:'09:00',endTime:'17:00'},{id:'two',restaurantId:'r2',date:'2026-10-08',role:'Cook',startTime:'09:00',endTime:'17:00'},{id:'three',restaurantId:'r1',date:'2026-10-08',role:'Cook',startTime:'18:00',endTime:'22:00'}];assert.equal(intelligence.buildScheduleForecast(args).rows[0].existing,1);});
test('forecast duplicate conflicting daily totals and unsupported target windows fail closed',()=>{for(const patch of [{sales:[...sales,{...sales[0],id:'conflict',grossSales:999}]},{coverageTargets:[{...forecastArgs().coverageTargets[0],startTime:'bad'}]}]) assert.equal(intelligence.buildScheduleForecast({...forecastArgs(),...patch}).rows[0].state,'insufficient-data');});
test('training review requires HR authority and preserves source evidence',()=>{const report={allowed:true,trainingOpportunities:[{id:'training:prep',workspaceId:'r1',title:'Review repeated prep issue',reason:'Two incomplete prep runs',evidenceIds:['a','b'],roleScope:['kitchen']}]};const draft=intelligence.buildTrainingDraft({actor:owner,workspaceId:'r1',opportunity:report.trainingOpportunities[0],now:'2026-10-08T12:00:00Z'});assert.deepEqual(draft.evidenceIds,['a','b']);assert.equal(draft.automaticAssignment,false);assert.throws(()=>intelligence.buildTrainingDraft({actor:{restaurantId:'r1',permissions:{ops:true}},workspaceId:'r1',opportunity:report.trainingOpportunities[0]}),/HR permission/);assert.equal(intelligence.readTrainingDraft(draft,'r2',owner),null);});
test('training handoff expires and cannot cross workspaces',()=>{const draft=intelligence.buildTrainingDraft({actor:owner,workspaceId:'r1',now:'2026-10-08T12:00:00Z',opportunity:{workspaceId:'r1',title:'Review prep',evidenceIds:['a']}});assert.equal(intelligence.readTrainingDraft(draft,'r1',owner,'2026-10-08T12:11:00Z'),null);assert.equal(intelligence.readTrainingDraft({...draft,createdAt:'bad'},'r1',owner),null);});
const punches=[{id:'p1',restaurantId:'r1',employeeId:'staff',date:'2026-10-07',clockIn:'2026-10-07T22:00:00Z',status:'clocked_in'}];
test('clock awareness detects long open punches and duplicate active punches without mutations',()=>{const report=intelligence.buildClockAwareness({workspaceId:'r1',actor:owner,now:'2026-10-08T12:00:00Z',timePunches:[...punches,{...punches[0],id:'p2'}],sourceState:{...resolved,data:punches},users:[{id:'staff',restaurantId:'r1',name:'Sam'}]});assert.ok(report.findings.some(row=>row.kind==='long-open-punch'));assert.ok(report.findings.some(row=>row.kind==='duplicate-active-punch'));assert.equal(report.mutationAllowed,false);});
test('clock awareness preserves overnight work, source completeness and employee privacy',()=>{const args={workspaceId:'r1',actor:owner,now:'2026-10-08T02:00:00Z',timePunches:punches,sourceState:resolved};assert.equal(intelligence.buildClockAwareness(args).findings.length,0);assert.equal(intelligence.buildClockAwareness({...args,actor:{restaurantId:'r1',role:'staff'}}).allowed,false);assert.equal(intelligence.buildClockAwareness({...args,sourceState:{resolved:false}}).complete,false);assert.equal(intelligence.buildClockAwareness({...args,timePunches:punches.map(row=>({...row,restaurantId:'r2'}))}).findings.length,0);});
test('forecast draft identities deduplicate retries and separate date/role/workspace slots',()=>{const row=intelligence.buildScheduleForecast(forecastArgs()).rows[0];assert.equal(intelligence.forecastDraftId(row,'r1',2),intelligence.forecastDraftId(row,'r1',2));assert.notEqual(intelligence.forecastDraftId(row,'r1',2),intelligence.forecastDraftId(row,'r1',3));assert.throws(()=>intelligence.forecastDraftId(row,'r2',2));});
test('forecast assignments exclude overnight overlap and weekly caps; unknown hours do not imply eligibility',()=>{
  const person={id:'cook',restaurantId:'r1',maxWeeklyHours:20};const args={person,date:'2026-10-08',startTime:'09:00',endTime:'17:00',loadedDates:['2026-10-05','2026-10-06','2026-10-07','2026-10-08','2026-10-09','2026-10-10','2026-10-11'],shifts:[]};assert.equal(intelligence.isForecastCandidateEligible(args),true);assert.equal(intelligence.isForecastCandidateEligible({...args,loadedDates:[]}),false);
  assert.equal(intelligence.isForecastCandidateEligible({...args,shifts:[{restaurantId:'r1',employeeId:'cook',date:'2026-10-07',startTime:'23:00',endTime:'10:00'}]}),false);
  assert.equal(intelligence.isForecastCandidateEligible({...args,shifts:[{restaurantId:'r1',employeeId:'cook',date:'2026-10-06',startTime:'01:00',endTime:'15:00'}]}),false);
});
test('saved forecast drafts cannot overwrite existing published/deleted shifts',async()=>{
  const saved=new Map();const ref={id:'draft'};const payload={restaurantId:'r1',isPublished:false};
  const transact=async callback=>callback({get:async()=>({exists:()=>saved.has(ref.id),data:()=>saved.get(ref.id)}),set:(_,data)=>saved.set(ref.id,data)});
  assert.equal((await intelligence.saveForecastDraft({transact,ref,payload})).created,true);saved.set(ref.id,{restaurantId:'r1',isPublished:true});assert.equal((await intelligence.saveForecastDraft({transact,ref,payload})).created,false);assert.equal(saved.get(ref.id).isPublished,true);
  saved.set(ref.id,{restaurantId:'r2'});await assert.rejects(intelligence.saveForecastDraft({transact,ref,payload}),/workspace/);
});
test('repeated readiness gaps become training evidence; repeated ready categories do not',()=>{const events=['2026-10-01','2026-10-02'].map((date,index)=>({id:`s${index}`,restaurantId:'r1',type:'readiness_snapshot',date,snapshots:[{key:'prep',status:'attention'},{key:'inventory',status:'ready'}]}));const inputs=intelligence.buildHistoryInputs({workspaceId:'r1',events});const report=buildOperationalHistory({workspaceId:'r1',actor:owner,now:'2026-10-08T12:00:00Z',...inputs});assert.equal(report.trainingOpportunities.length,1);assert.deepEqual(report.trainingOpportunities[0].evidenceIds.sort(),['s0','s1']);});
