'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
test('root ESLint config exists and lint scope remains meaningful', () => {
  assert.ok(fs.existsSync(path.join(root, '.eslintrc.cjs')));
  assert.match(pkg.scripts.lint, /src\/\*\*\/\*\.\{js,jsx\}/);
  assert.match(pkg.scripts.lint, /api\/\*\*\/\*\.js/);
  assert.doesNotMatch(pkg.scripts.lint, /\|\|\s*exit\s+0/);
  const config = fs.readFileSync(path.join(root, '.eslintrc.cjs'), 'utf8');
  assert.doesNotMatch(config, /ignorePatterns\s*:\s*\[[^\]]*src/);
  assert.doesNotMatch(config, /ignorePatterns\s*:\s*\[[^\]]*api/);
  assert.match(config, /no-unreachable/);
  assert.match(config, /no-dupe-keys/);
  assert.match(config, /no-duplicate-case/);
  assert.match(config, /valid-typeof/);
});
