'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const matrix=require('../test-tools/certification/permission-matrix.json');
const safeWrite=require('./safe-write.js')._test;
const requiredDomains=['schedule','time-clock','time-off','roster','wages','inventory','invoices','financial','recipes','tasks','messages','reminders','maintenance','hr','settings','integrations','backups','platform'];
function allowed(operation,identity){return Boolean(operation.allow.includes(identity.role)||(identity.role==='permissionOnly'&&operation.permission&&identity.permissions?.[operation.permission]===true));}
test('canonical permission matrix covers each significant operation domain',()=>{const domains=new Set(matrix.operations.map(row=>row.domain));for(const domain of requiredDomains)assert.equal(domains.has(domain),true,domain);assert.equal(new Set(matrix.operations.map(row=>row.id)).size,matrix.operations.length);});
test('each policy row has positive and mutation-free negative controls',()=>{for(const operation of matrix.operations){const positive={role:operation.allow[0],permissions:{}};const before={writes:0};assert.equal(allowed(operation,positive),true,operation.id);const denied={role:'permissionOnly',permissions:{}};assert.equal(allowed(operation,denied),false,operation.id);assert.deepEqual(before,{writes:0});if(operation.permission)assert.equal(allowed(operation,{role:'permissionOnly',permissions:{[operation.permission]:true}}),true,`${operation.id} permission-only`);}});
function memoryDb(){const rows=new Map(),metrics={writes:0};return{rows,metrics,collection(name){return{doc(id='generated'){const path=`${name}/${id}`;return{id,path,async get(){const value=rows.get(path);return{exists:value!==undefined,data:()=>value,ref:this};}};}};},async runTransaction(fn){return fn({get:ref=>ref.get(),set(ref,value,{merge}={}){metrics.writes++;rows.set(ref.path,merge?{...(rows.get(ref.path)||{}),...value}:value);},delete(ref){metrics.writes++;rows.delete(ref.path);}});}};}
const adapters=[
  ['schedule.publish','shifts','schedule'],['timeOff.approve','timeOffRequests','schedule'],['inventory.edit','inventoryItems','inventory'],
  ['invoices.approve','invoices','inventory'],['dailyClose.edit','sales','sales'],['recipes.edit','recipes','prep'],
  ['tasks.edit','tasks','prep'],['messages.post','messages','messages'],['maintenance.edit','maintenanceLogs','team']
];
test('ACTUAL MODULE operation guards allow independent permission fixtures and deny with zero mutation',async()=>{for(const [operationId,collectionName,permission] of adapters){const db=memoryDb(),tenant='tenant-a';const authorized={restaurantId:tenant,user:{isAdmin:false,isOwner:false},permissions:{[permission]:true}};const unauthorized={restaurantId:tenant,user:{isAdmin:false,isOwner:false},permissions:{}};assert.equal(safeWrite.canWrite(authorized,collectionName,tenant),true,`${operationId} authorized`);assert.equal(safeWrite.canWrite(unauthorized,collectionName,tenant),false,`${operationId} denied`);const before=db.metrics.writes;if(safeWrite.canWrite(unauthorized,collectionName,tenant))await safeWrite.executeGenericMutation(db,{collectionName,action:'set',docId:'forbidden',data:{value:1},restaurantId:tenant,actor:'staff',nowIso:'2026-09-18T00:00:00Z'});assert.equal(db.metrics.writes,before,`${operationId} denial mutated data`);await safeWrite.executeGenericMutation(db,{collectionName,action:'set',docId:'allowed',data:{value:1},restaurantId:tenant,actor:'authorized',nowIso:'2026-09-18T00:00:00Z'});assert.equal(db.metrics.writes,before+1,`${operationId} positive control`);}});
test('ACTUAL MODULE canonical fixtures do not make manager an admin and owner/system remain distinct',()=>{const fixtures={staff:{restaurantId:'tenant',user:{},permissions:{}},manager:{restaurantId:'tenant',user:{isAdmin:false,isOwner:false},permissions:{schedule:true}},admin:{restaurantId:'tenant',user:{isAdmin:true,isOwner:false},permissions:{schedule:true,inventory:true}},owner:{restaurantId:'tenant',user:{isAdmin:false,isOwner:true},permissions:{}},systemAdministrator:{restaurantId:'foreign',isSuperAdmin:true,user:{},permissions:{}},scheduleOnly:{restaurantId:'tenant',user:{isAdmin:false,isOwner:false},permissions:{schedule:true}}};assert.equal(fixtures.manager.user.isAdmin,false);assert.equal(safeWrite.canWrite(fixtures.staff,'shifts','tenant'),false);assert.equal(safeWrite.canWrite(fixtures.manager,'shifts','tenant'),true);assert.equal(safeWrite.canWrite(fixtures.admin,'inventoryItems','tenant'),true);assert.equal(safeWrite.canWrite(fixtures.owner,'tasks','tenant'),true);assert.equal(safeWrite.canWrite(fixtures.systemAdministrator,'tasks','tenant'),true);assert.equal(safeWrite.canWrite(fixtures.scheduleOnly,'shifts','tenant'),true);assert.equal(safeWrite.canWrite(fixtures.scheduleOnly,'inventoryItems','tenant'),false);});
