'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const matrix=require('../test-tools/certification/permission-matrix.json');
const safeWrite=require('./safe-write.js')._test;
const scheduleGuard=require('./schedule-publish.js')._test.canPublishSchedule;
const dailyCloseGuard=require('./daily-close.js')._test.canManageDailyClose;
const requiredDomains=['schedule','time-clock','time-off','roster','wages','inventory','invoices','financial','recipes','tasks','messages','reminders','maintenance','hr','settings','integrations','backups','platform'];
function allowed(operation,identity){return Boolean(operation.allow.includes(identity.role)||(identity.role==='permissionOnly'&&operation.permission&&identity.permissions?.[operation.permission]===true));}
test('canonical permission matrix covers each significant operation domain',()=>{const domains=new Set(matrix.operations.map(row=>row.domain));for(const domain of requiredDomains)assert.equal(domains.has(domain),true,domain);assert.equal(new Set(matrix.operations.map(row=>row.id)).size,matrix.operations.length);});
test('independent policy table defines positive and negative expectations',()=>{for(const operation of matrix.operations){const positive={role:operation.allow[0],permissions:{}};assert.equal(allowed(operation,positive),true,operation.id);const denied={role:'permissionOnly',permissions:{}};assert.equal(allowed(operation,denied),false,operation.id);if(operation.permission)assert.equal(allowed(operation,{role:'permissionOnly',permissions:{[operation.permission]:true}}),true,`${operation.id} permission-only`);}});
function memoryDb(){const rows=new Map(),metrics={writes:0};return{rows,metrics,collection(name){return{doc(id='generated'){const path=`${name}/${id}`;return{id,path,async get(){const value=rows.get(path);return{exists:value!==undefined,data:()=>value,ref:this};}};}};},async runTransaction(fn){return fn({get:ref=>ref.get(),set(ref,value,{merge}={}){metrics.writes++;rows.set(ref.path,merge?{...(rows.get(ref.path)||{}),...value}:value);},delete(ref){metrics.writes++;rows.delete(ref.path);}});}};}
const adapters=[
  ['timeOff.approve','timeOffRequests','schedule'],['inventory.edit','inventoryItems','inventory'],
  ['recipes.edit','recipes','prep'],
  ['tasks.edit','tasks','prep'],['messages.post','messages','messages'],['maintenance.edit','maintenanceLogs','team']
];
test('ACTUAL MODULE operation guards allow independent permission fixtures and deny with zero mutation',async()=>{for(const [operationId,collectionName,permission] of adapters){const db=memoryDb(),tenant='tenant-a';const authorized={restaurantId:tenant,user:{isAdmin:false,isOwner:false},permissions:{[permission]:true}};const unauthorized={restaurantId:tenant,user:{isAdmin:false,isOwner:false},permissions:{}};assert.equal(safeWrite.canWrite(authorized,collectionName,tenant),true,`${operationId} authorized`);assert.equal(safeWrite.canWrite(unauthorized,collectionName,tenant),false,`${operationId} denied`);const before=db.metrics.writes;if(safeWrite.canWrite(unauthorized,collectionName,tenant))await safeWrite.executeGenericMutation(db,{collectionName,action:'set',docId:'forbidden',data:{value:1},restaurantId:tenant,actor:'staff',nowIso:'2026-09-18T00:00:00Z'});assert.equal(db.metrics.writes,before,`${operationId} denial mutated data`);await safeWrite.executeGenericMutation(db,{collectionName,action:'set',docId:'allowed',data:{value:1},restaurantId:tenant,actor:'authorized',nowIso:'2026-09-18T00:00:00Z'});assert.equal(db.metrics.writes,before+1,`${operationId} positive control`);}});
test('ACTUAL MODULE schedule, Daily Close, and invoice policies use their real operation guards',()=>{const tenant='tenant';const fixtures={staff:{restaurantId:tenant,user:{},permissions:{}},manager:{restaurantId:tenant,user:{isAdmin:false,isOwner:false},permissions:{schedule:true,salesEdit:true,inventory:true}},admin:{restaurantId:tenant,user:{isAdmin:true,isOwner:false},permissions:{inventory:true}},owner:{restaurantId:tenant,user:{isOwner:true},permissions:{}},systemAdministrator:{restaurantId:'foreign',isSuperAdmin:true,user:{},permissions:{}},scheduleOnly:{restaurantId:tenant,user:{},permissions:{schedule:true}},settingsOnly:{restaurantId:tenant,user:{},permissions:{settings:true}}};for(const name of ['manager','admin','owner','systemAdministrator']){assert.equal(scheduleGuard(fixtures[name]),true,`${name} schedule`);assert.equal(dailyCloseGuard(fixtures[name]),true,`${name} daily close`);assert.equal(safeWrite.canWrite(fixtures[name],'inventoryItems',name==='systemAdministrator'?'foreign':tenant),true,`${name} invoice inventory authority`);}assert.equal(scheduleGuard(fixtures.scheduleOnly),true);assert.equal(dailyCloseGuard(fixtures.scheduleOnly),false);assert.equal(dailyCloseGuard(fixtures.settingsOnly),false);assert.equal(scheduleGuard(fixtures.settingsOnly),false);assert.equal(safeWrite.canWrite(fixtures.staff,'inventoryItems',tenant),false);});
test('ACTUAL HANDLER Daily Close denies unrelated permission-only users before mutation',async()=>{const chaosPath=require.resolve('./_chaos-admin.js'),servicePath=require.resolve('./_daily-close-service.cjs'),routePath=require.resolve('./daily-close.js'),oldChaos=require.cache[chaosPath],oldService=require.cache[servicePath];const fixtures=[{name:'settings-only',ctx:{ok:true,restaurantId:'tenant',user:{},permissions:{settings:true}},status:403,calls:0},{name:'schedule-only',ctx:{ok:true,restaurantId:'tenant',user:{},permissions:{schedule:true}},status:403,calls:0},{name:'manager-sales',ctx:{ok:true,restaurantId:'tenant',uid:'manager',user:{isAdmin:false},permissions:{salesEdit:true}},status:200,calls:1},{name:'admin',ctx:{ok:true,restaurantId:'tenant',uid:'admin',user:{isAdmin:true},permissions:{}},status:200,calls:1},{name:'owner',ctx:{ok:true,restaurantId:'tenant',uid:'owner',user:{isOwner:true},permissions:{}},status:200,calls:1},{name:'system',ctx:{ok:true,restaurantId:'tenant',uid:'system',isSuperAdmin:true,user:{},permissions:{}},status:200,calls:1},{name:'foreign',ctx:{ok:false,status:403,error:'unavailable'},status:403,calls:0}];try{for(const fixture of fixtures){let calls=0;require.cache[chaosPath]={id:chaosPath,filename:chaosPath,loaded:true,exports:{initAdmin:()=>({firestore:()=>({})}),authorize:async()=>fixture.ctx,requireAppCheckIfEnforced:async()=>({ok:true})}};require.cache[servicePath]={id:servicePath,filename:servicePath,loaded:true,exports:{saveDailyClose:async()=>{calls+=1;return{id:'close',revision:1};}}};delete require.cache[routePath];const handler=require('./daily-close.js'),res={statusCode:0,payload:null,status(code){this.statusCode=code;return this;},json(payload){this.payload=payload;return this;}};await handler({method:'POST',headers:{},body:{restaurantId:'tenant',date:'2026-09-18',operationId:'daily_permission_123',expectedRevision:0,data:{grossSales:1}}},res);assert.equal(res.statusCode,fixture.status,`${fixture.name}: ${JSON.stringify(res.payload)}`);assert.equal(calls,fixture.calls,`${fixture.name} mutation calls`);}}finally{delete require.cache[routePath];if(oldChaos)require.cache[chaosPath]=oldChaos;else delete require.cache[chaosPath];if(oldService)require.cache[servicePath]=oldService;else delete require.cache[servicePath];}});
test('ACTUAL MODULE canonical fixtures do not make manager an admin and owner/system remain distinct',()=>{const fixtures={staff:{restaurantId:'tenant',user:{},permissions:{}},manager:{restaurantId:'tenant',user:{isAdmin:false,isOwner:false},permissions:{schedule:true}},admin:{restaurantId:'tenant',user:{isAdmin:true,isOwner:false},permissions:{schedule:true,inventory:true}},owner:{restaurantId:'tenant',user:{isAdmin:false,isOwner:true},permissions:{}},systemAdministrator:{restaurantId:'foreign',isSuperAdmin:true,user:{},permissions:{}},scheduleOnly:{restaurantId:'tenant',user:{isAdmin:false,isOwner:false},permissions:{schedule:true}}};assert.equal(fixtures.manager.user.isAdmin,false);assert.equal(safeWrite.canWrite(fixtures.staff,'shifts','tenant'),false);assert.equal(safeWrite.canWrite(fixtures.manager,'shifts','tenant'),true);assert.equal(safeWrite.canWrite(fixtures.admin,'inventoryItems','tenant'),true);assert.equal(safeWrite.canWrite(fixtures.owner,'tasks','tenant'),true);assert.equal(safeWrite.canWrite(fixtures.systemAdministrator,'tasks','tenant'),true);assert.equal(safeWrite.canWrite(fixtures.scheduleOnly,'shifts','tenant'),true);assert.equal(safeWrite.canWrite(fixtures.scheduleOnly,'inventoryItems','tenant'),false);});
