'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {authorizeControlPlane}=require('./_pos-bridge-authority');
const original={...process.env};
function token(project='demo-project'){return `e30.${Buffer.from(JSON.stringify({aud:project})).toString('base64url')}.signature`;}
function setup({member={restaurantId:'rest-a',isActive:true,isOwner:true},accountUser={isActive:true},workspaceUser={isActive:true,isOwner:true},verifyError=null}={}){Object.assign(process.env,{POS_BRIDGE_ENABLED:'true',POS_BRIDGE_ENVIRONMENT:'testing'});let verified=0;const db={collection:name=>({doc:id=>({get:async()=>name==='restaurants'&&id==='rest-a'?{exists:true,data:()=>({isActive:true,status:'active'})}:{exists:false,data:()=>undefined}})})};const app={options:{projectId:'demo-project'},firestore:()=>db};const auth={ok:true,app,db,uid:'uid-a',email:'owner@example.test',restaurantId:'rest-a',accountUser,user:workspaceUser,decoded:{auth_time:Math.floor(Date.now()/1000)},isSuperAdmin:false};const dependencies={getPosBridgeAdminApp:()=>app,authorize:async()=>auth,requireAppCheckIfEnforced:async()=>({ok:true}),verifyFirebaseAccount:async()=>{verified+=1;if(verifyError)throw verifyError;return {uid:'uid-a',disabled:false};},canonicalMembershipState:async()=>member?{exists:true,member}:{exists:false,member:null}};const req={headers:{authorization:`Bearer ${token()}`}};return {req,dependencies,verified:()=>verified};}
test.after(()=>{for(const key of Object.keys(process.env))if(!(key in original))delete process.env[key];Object.assign(process.env,original);});
test('revoked Firebase sessions and disabled Auth users fail before bridge mutation',async()=>{for(const error of [Object.assign(new Error('revoked'),{code:'auth/id-token-revoked'}),Object.assign(new Error('disabled'),{code:'account_inactive'})]){const loaded=setup({verifyError:error});let mutations=0;await assert.rejects(async()=>{await authorizeControlPlane(loaded.req,'rest-a',{dependencies:loaded.dependencies});mutations+=1;});assert.equal(loaded.verified(),1);assert.equal(mutations,0);}});
test('canonical inactive or removed membership defeats every legacy owner fallback',async()=>{for(const member of [{restaurantId:'rest-a',isActive:false,isOwner:true,status:'inactive'},null]){const loaded=setup({member,accountUser:{isActive:true,restaurantId:'rest-a',workspaceIds:['rest-a'],memberships:{'rest-a':{isActive:true,isOwner:true}}},workspaceUser:{isActive:true,isOwner:true}});await assert.rejects(()=>authorizeControlPlane(loaded.req,'rest-a',{dependencies:loaded.dependencies}),error=>error.code==='forbidden');}});
test('manager and permission-only users are denied while active canonical owner and admin are allowed',async()=>{for(const denied of [{restaurantId:'rest-a',isActive:true,role:'manager'},{restaurantId:'rest-a',isActive:true,permissions:{team:true,settings:true}}]){const loaded=setup({member:denied,workspaceUser:denied});await assert.rejects(()=>authorizeControlPlane(loaded.req,'rest-a',{dependencies:loaded.dependencies}),error=>error.code==='forbidden');}for(const allowed of [{restaurantId:'rest-a',isActive:true,isOwner:true},{restaurantId:'rest-a',isActive:true,isAdmin:true}]){const loaded=setup({member:allowed,workspaceUser:allowed});const ctx=await authorizeControlPlane(loaded.req,'rest-a',{dependencies:loaded.dependencies});assert.deepEqual(ctx.canonicalMembership,allowed);}});
test('inactive 86 Chaos account state is denied even with active canonical admin membership',async()=>{for(const accountUser of [{isActive:false},{disabled:true},{status:'revoked'}]){const loaded=setup({member:{restaurantId:'rest-a',isActive:true,isAdmin:true},accountUser,workspaceUser:{isActive:true,isAdmin:true}});await assert.rejects(()=>authorizeControlPlane(loaded.req,'rest-a',{dependencies:loaded.dependencies}),error=>error.code==='forbidden');}});
