'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {MemoryDb}=require('../test-tools/pos-bridge-memory-db.cjs');
const {orderEvent}=require('../test-tools/pos-bridge-fixtures.cjs');
const {stageEvent}=require('./_pos-bridge-storage');
const {summary,compareManifest}=require('./_pos-bridge-reconciliation');
function setup({highest=0,missingFirst=false}={}){Object.assign(process.env,{POS_BRIDGE_ENABLED:'true',POS_BRIDGE_ENVIRONMENT:'testing',POS_BRIDGE_TOKEN_ISSUER:'issuer',POS_BRIDGE_TOKEN_AUDIENCE:'aud',POS_BRIDGE_ASSERTION_AUDIENCE:'token-aud',POS_BRIDGE_SIGNING_KEY_ID:'k',POS_BRIDGE_SIGNING_PRIVATE_JWK:JSON.stringify({kty:'EC',crv:'P-256',x:'x',y:'y',d:'d',alg:'ES256'}),POS_BRIDGE_SECURITY_EPOCH:'1'});const installation={posInstallationId:'pbi-test',restaurantId:'rest-a',locationId:'loc-a',sourceNamespaceId:'ns-a',tenantScopeId:'scope-a',environment:'testing',status:'active',credentialVersion:1,securityEpoch:1};const seed={'posBridgeInstallations/pbi-test':installation,'restaurants/rest-a':{isActive:true,status:'active'},'posBridgeControl/global':{enabled:true,securityEpoch:1},'posBridgeScopes/scope-a':{restaurantId:'rest-a',locationId:'loc-a',sourceNamespaceId:'ns-a',active:true,locationStatus:'active',activeInstallationId:'pbi-test'}};if(highest){for(let sequence=missingFirst?2:1;sequence<=highest;sequence+=1){const windowId=String(Math.floor((sequence-1)/256)).padStart(12,'0');const path=`posBridgeScopes/scope-a/streams/pbi-test/sequenceWindows/${windowId}`;const doc=seed[path]||{slots:{}};doc.slots[String((sequence-1)%256)]=`hash-${sequence}`;seed[path]=doc;}seed['posBridgeScopes/scope-a/streams/pbi-test']={restaurantId:'rest-a',locationId:'loc-a',sourceNamespaceId:'ns-a',highestSequenceObserved:highest,highestContiguousSequence:missingFirst?0:highest,uniqueSequencesObserved:highest-(missingFirst?1:0),uniqueEventsReceived:highest-(missingFirst?1:0),stagedEvents:highest-(missingFirst?1:0),missingSequenceCount:missingFirst?1:0,checkpointComplete:true,checkpointWorkPending:false,reconciliationStatus:missingFirst?'transport-gaps':'transport-contiguous'};}const db=new MemoryDb(seed);return {db,authority:{installation,claims:{posInstallationId:'pbi-test',credentialVersion:1,securityEpoch:1}}};}
test('exact window boundary completes without fabricating pending checkpoint work',async()=>{const {db,authority}=setup({highest:256,missingFirst:true});await stageEvent(db,authority,orderEvent());const transport=await summary(db,authority);assert.equal(transport.highestSequenceObserved,256);assert.equal(transport.highestContiguousSequence,256);assert.equal(transport.missingSequenceCount,0);assert.equal(transport.checkpointComplete,true);assert.equal(transport.checkpointWorkPending,false);assert.equal(transport.reconciliationStatus,'transport-contiguous');});
test('2 through 600 then 1 converges across bounded windows while idle',async()=>{const {db,authority}=setup({highest:600,missingFirst:true});await stageEvent(db,authority,orderEvent());let transport=await summary(db,authority);assert.equal(transport.highestContiguousSequence,512);assert.equal(transport.missingSequenceCount,0);assert.equal(transport.checkpointWorkPending,true);assert.equal(transport.reconciliationStatus,'checkpoint-pending');transport=await summary(db,authority);assert.equal(transport.highestContiguousSequence,600);assert.equal(transport.checkpointComplete,true);assert.equal(transport.checkpointWorkPending,false);assert.equal(transport.missingSequenceCount,0);assert.equal(transport.reconciliationStatus,'transport-contiguous');});
test('reconciliation distinguishes pending scan work from real transport gaps',async()=>{const {db,authority}=setup();await stageEvent(db,authority,orderEvent());await stageEvent(db,authority,orderEvent({eventId:'evt-3',eventType:'order.updated',sourceEntityVersion:3,sequence:3}));let transport=await summary(db,authority);assert.equal(transport.missingSequenceCount,1);assert.equal(transport.checkpointWorkPending,false);assert.equal(transport.reconciliationStatus,'transport-gaps');await stageEvent(db,authority,orderEvent({eventId:'evt-2',eventType:'order.updated',sourceEntityVersion:2,sequence:2}));transport=await summary(db,authority);assert.equal(transport.highestContiguousSequence,3);assert.equal(transport.reconciliationStatus,'transport-contiguous');});
test('reconciliation metrics report only retained aggregate validation evidence',async()=>{const {db,authority}=setup();const first=await stageEvent(db,authority,orderEvent());db.resetOperations();await stageEvent(db,authority,orderEvent());assert.equal(db.operations.writes,0);const transport=await summary(db,authority);assert.equal('duplicateDeliveryAttempts' in transport,false);assert.equal('semanticRejectedEvents' in transport,false);assert.equal(transport.validationFailureAttempts,0);const manifest=await compareManifest(db,authority,[{eventId:'evt-1',contentHash:first.contentHash},{eventId:'missing'}]);assert.deepEqual(manifest.map(entry=>entry.status),['present','missing']);await assert.rejects(()=>compareManifest(db,authority,[{eventId:''}]),error=>error.code==='invalid_request');});
