'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {MemoryDb}=require('../test-tools/pos-bridge-memory-db.cjs');
const {orderEvent}=require('../test-tools/pos-bridge-fixtures.cjs');
const {stageEvent}=require('./_pos-bridge-storage');
const {processEventBatch}=require('./_pos-bridge-events');
function setup(){Object.assign(process.env,{POS_BRIDGE_ENABLED:'true',POS_BRIDGE_ENVIRONMENT:'testing',POS_BRIDGE_TOKEN_ISSUER:'issuer',POS_BRIDGE_TOKEN_AUDIENCE:'aud',POS_BRIDGE_ASSERTION_AUDIENCE:'token-aud',POS_BRIDGE_SIGNING_KEY_ID:'k',POS_BRIDGE_SIGNING_PRIVATE_JWK:JSON.stringify({kty:'EC',crv:'P-256',x:'x',y:'y',d:'d',alg:'ES256'}),POS_BRIDGE_SECURITY_EPOCH:'1'});const installation={posInstallationId:'pbi-test',restaurantId:'rest-a',locationId:'loc-a',sourceNamespaceId:'ns-a',tenantScopeId:'scope-a',environment:'testing',status:'active',credentialVersion:1,securityEpoch:1,approvedCapabilities:['event.staging']};const db=new MemoryDb({'posBridgeInstallations/pbi-test':installation,'restaurants/rest-a':{isActive:true,status:'active'},'posBridgeControl/global':{enabled:true,securityEpoch:1},'posBridgeScopes/scope-a':{restaurantId:'rest-a',locationId:'loc-a',sourceNamespaceId:'ns-a',active:true,locationStatus:'active',activeInstallationId:'pbi-test'}});return {db,authority:{installation,claims:{posInstallationId:'pbi-test',credentialVersion:1,securityEpoch:1}}};}
function batch(){const base=orderEvent();return [base,orderEvent({eventId:'evt-2',eventType:'order.updated',sourceEntityVersion:2,sequence:2}),orderEvent({eventId:'evt-conflict',sourceEntityId:'other-order',payload:{...base.payload,orderId:'other-order'},sequence:2}),orderEvent({eventId:'evt-4',eventType:'order.updated',sourceEntityVersion:4,sequence:4})];}
function response(){return {statusCode:0,headers:{},status(value){this.statusCode=value;return this;},setHeader(name,value){this.headers[name]=value;},end(value){this.body=JSON.parse(value);}};}
test('partial batch exposes committed receipts, conflict position, and later unattempted events',async()=>{const {db,authority}=setup();const events=batch();const first=await processEventBatch(db,authority,events);assert.equal(first.ok,false);assert.equal(first.partial,true);assert.deepEqual(first.results.map(result=>result.outcome),['accepted','accepted','conflict','unattempted']);assert.equal(first.receipts.length,2);assert.equal(first.failedIndex,2);assert.equal([...db.docs.keys()].filter(path=>path.includes('/events/')).length,2);const wholeRetry=await processEventBatch(db,authority,events);assert.deepEqual(wholeRetry.results.map(result=>result.outcome),['duplicate','duplicate','conflict','unattempted']);assert.equal(wholeRetry.receipts[0].receiptId,first.receipts[0].receiptId);const partialRetry=await processEventBatch(db,authority,[events[3]]);assert.equal(partialRetry.ok,true);assert.equal(partialRetry.results[0].outcome,'accepted');});
test('transient failure and lost acknowledgement report unknown commit while whole retry remains safe',async()=>{const {db,authority}=setup();const events=batch().slice(0,2);let calls=0;const commitThenLoseAck=async(database,current,event)=>{calls+=1;const receipt=await stageEvent(database,current,event);if(calls===2)throw new Error('connection reset after commit');return receipt;};const first=await processEventBatch(db,authority,events,{stage:commitThenLoseAck});assert.deepEqual(first.results.map(result=>result.outcome),['accepted','retryable']);assert.equal(first.results[1].commitState,'unknown');assert.equal([...db.docs.keys()].filter(path=>path.includes('/events/')).length,2);const retry=await processEventBatch(db,authority,events);assert.deepEqual(retry.results.map(result=>result.outcome),['duplicate','duplicate']);assert.equal(retry.ok,true);});
test('persistent conflict remains explicit and never hides later unattempted work',async()=>{const {db,authority}=setup();const events=batch();await processEventBatch(db,authority,events);for(let attempt=0;attempt<2;attempt+=1){const result=await processEventBatch(db,authority,events.slice(2));assert.equal(result.results[0].outcome,'conflict');assert.equal(result.results[1].outcome,'unattempted');assert.equal(result.results[1].blockedByIndex,0);}});
test('schema rejection records only aggregate evidence and never a rejected payload receipt',async()=>{const {db,authority}=setup();const invalid=orderEvent();invalid.payload.tenders=[{tenderId:'t',classification:'credit',amountCents:100,status:'captured',cardNumber:'4111111111111111'}];const result=await processEventBatch(db,authority,[invalid]);assert.equal(result.results[0].outcome,'rejected');assert.equal(result.results[0].evidenceRecorded,true);assert.equal([...db.docs.keys()].some(path=>path.includes('/events/')),false);const stream=db.docs.get('posBridgeScopes/scope-a/streams/pbi-test');assert.equal(stream.validationFailureAttempts,1);assert.equal('semanticRejectedEvents' in stream,false);});
test('events route returns HTTP 207 with the truthful per-event partial result contract',async()=>{const {db,authority}=setup();const projectPath=require.resolve('./_pos-bridge-project');const authPath=require.resolve('./_pos-bridge-auth');const routePath=require.resolve('./pos-bridge/v1/events');const originals=new Map([[projectPath,require.cache[projectPath]],[authPath,require.cache[authPath]],[routePath,require.cache[routePath]]]);require.cache[projectPath]={id:projectPath,filename:projectPath,loaded:true,exports:{getPosBridgeAdminApp:()=>({firestore:()=>db})}};require.cache[authPath]={id:authPath,filename:authPath,loaded:true,exports:{verifyAccessToken:async()=>authority,admitRate:async()=>{}}};delete require.cache[routePath];try{const handler=require('./pos-bridge/v1/events');const res=response();await handler({method:'POST',headers:{'x-pos-bridge-contract':'1.0'},query:{},body:{contractVersion:'1.0',events:batch()}},res);assert.equal(res.statusCode,207);assert.equal(res.body.partial,true);assert.deepEqual(res.body.results.map(result=>result.outcome),['accepted','accepted','conflict','unattempted']);assert.equal(res.body.receipts.length,2);}finally{delete require.cache[routePath];for(const [path,cached] of originals){if(path===routePath)continue;if(cached)require.cache[path]=cached;else delete require.cache[path];}}});
