'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const admin=require('firebase-admin');const {stageEvent}=require('./_pos-bridge-storage');const {summary}=require('./_pos-bridge-reconciliation');const {changeMapping}=require('./_pos-bridge-mappings');const {scopeId}=require('./_pos-bridge-authority');const {validateSimulatorTarget}=require('../test-tools/pos-bridge-simulator.cjs');const {orderEvent}=require('../test-tools/pos-bridge-fixtures.cjs');
if(!process.env.FIRESTORE_EMULATOR_HOST){test('POS Bridge concurrency suite runs only through required emulator command',{skip:'Run npm run test:pos-bridge:emulator; release gate requires it.'},()=>{});}else{
Object.assign(process.env,{POS_BRIDGE_ENABLED:'true',POS_BRIDGE_ENVIRONMENT:'testing',POS_BRIDGE_TOKEN_ISSUER:'issuer',POS_BRIDGE_TOKEN_AUDIENCE:'audience',POS_BRIDGE_ASSERTION_AUDIENCE:'token-audience',POS_BRIDGE_SIGNING_KEY_ID:'key',POS_BRIDGE_SIGNING_PRIVATE_JWK:JSON.stringify({kty:'EC',crv:'P-256',x:'x',y:'y',d:'d',alg:'ES256'}),POS_BRIDGE_SECURITY_EPOCH:'1'});
const app=admin.apps.find(a=>a.name==='pos-bridge-emulator')||admin.initializeApp({projectId:process.env.GCLOUD_PROJECT||'demo-pos-bridge'},'pos-bridge-emulator');const db=app.firestore();
let targetProof;async function requireSafeTarget(){if(!targetProof)targetProof=await validateSimulatorTarget('http://127.0.0.1:5001',{...process.env,GCLOUD_PROJECT:process.env.GCLOUD_PROJECT||'demo-pos-bridge'});return targetProof;}
async function clear(){await requireSafeTarget();for(const name of ['posBridgeInstallations','posBridgeScopes','posBridgeControl','posBridgeAuthReplays','restaurants','workspaceMembers','auditLogs']){const snap=await db.collection(name).get();await Promise.all(snap.docs.map(d=>db.recursiveDelete(d.ref)));}}
async function seed(){await clear();const installation={posInstallationId:'pbi-test',restaurantId:'rest-a',locationId:'loc-a',sourceNamespaceId:'ns-a',tenantScopeId:'scope-a',environment:'testing',status:'active',credentialVersion:1,securityEpoch:1,approvedCapabilities:['event.staging']};await Promise.all([db.collection('posBridgeInstallations').doc('pbi-test').set(installation),db.collection('restaurants').doc('rest-a').set({isActive:true,status:'active'}),db.collection('posBridgeControl').doc('global').set({enabled:true,securityEpoch:1}),db.collection('posBridgeScopes').doc('scope-a').set({restaurantId:'rest-a',locationId:'loc-a',sourceNamespaceId:'ns-a',active:true,locationStatus:'active',activeInstallationId:'pbi-test'})]);return {installation,claims:{posInstallationId:'pbi-test',credentialVersion:1,securityEpoch:1}};}
test.before(requireSafeTarget);test.beforeEach(seed);test.after(clear);
test('simultaneous same delivery converges on one durable receipt',async()=>{const authority=await seed();const results=await Promise.all(Array.from({length:8},()=>stageEvent(db,authority,orderEvent())));assert.equal(new Set(results.map(r=>r.receiptId)).size,1);const events=await db.collection('posBridgeScopes').doc('scope-a').collection('events').get();assert.equal(events.size,1);});
test('same sequence and same entity version conflicts serialize safely',async()=>{const authority=await seed();const first=stageEvent(db,authority,orderEvent());const second=stageEvent(db,authority,orderEvent({eventId:'other',sourceEntityId:'order-2',payload:{...orderEvent().payload,orderId:'order-2'}}));const settled=await Promise.allSettled([first,second]);assert.equal(settled.filter(r=>r.status==='fulfilled').length,1);assert.equal(settled.filter(r=>r.status==='rejected'&&r.reason.code==='conflict').length,1);const conflicting=orderEvent({eventId:'entity-conflict',sequence:2,payload:{...orderEvent().payload,totalCents:999}});await assert.rejects(()=>stageEvent(db,authority,conflicting),e=>e.code==='conflict');});
test('sequence gap closure advances only with complete evidence',async()=>{const authority=await seed();await stageEvent(db,authority,orderEvent());await stageEvent(db,authority,orderEvent({eventId:'e3',eventType:'order.updated',sourceEntityVersion:3,sequence:3}));let stream=(await db.collection('posBridgeScopes').doc('scope-a').collection('streams').doc('pbi-test').get()).data();assert.equal(stream.highestContiguousSequence,1);await stageEvent(db,authority,orderEvent({eventId:'e2',eventType:'order.updated',sourceEntityVersion:2,sequence:2}));stream=(await db.collection('posBridgeScopes').doc('scope-a').collection('streams').doc('pbi-test').get()).data();assert.equal(stream.highestContiguousSequence,3);});
test('credential rotation and revocation serialize against event acceptance',async()=>{const authority=await seed();const install=db.collection('posBridgeInstallations').doc('pbi-test');await Promise.allSettled([stageEvent(db,authority,orderEvent()),db.runTransaction(async tx=>{const snap=await tx.get(install);tx.update(install,{credentialVersion:snap.data().credentialVersion+1});})]);await assert.rejects(()=>stageEvent(db,authority,orderEvent({eventId:'after-rotation',sequence:2,sourceEntityVersion:2,eventType:'order.updated'})),e=>e.code==='authority_changed');const rotated=(await install.get()).data();const fresh={installation:rotated,claims:{posInstallationId:'pbi-test',credentialVersion:2,securityEpoch:1}};await Promise.allSettled([stageEvent(db,fresh,orderEvent({eventId:'during-revoke',sequence:2,sourceEntityVersion:2,eventType:'order.updated'})),db.runTransaction(async tx=>{await tx.get(install);tx.update(install,{status:'revoked',securityEpoch:2});})]);await assert.rejects(()=>stageEvent(db,fresh,orderEvent({eventId:'after-revoke',sequence:3,sourceEntityVersion:3,eventType:'order.updated'})),e=>e.code==='installation_inactive');});
test('concurrent scope claims permit one active writer only',async()=>{await clear();const scope=db.collection('posBridgeScopes').doc('activation-scope');const claim=id=>db.runTransaction(async tx=>{const snap=await tx.get(scope);const active=snap.data()?.activeInstallationId;if(active&&active!==id)throw Object.assign(new Error('writer exists'),{code:'conflict'});tx.set(scope,{active:true,locationStatus:'active',activeInstallationId:id},{merge:true});return id;});const settled=await Promise.allSettled([claim('writer-a'),claim('writer-b')]);assert.equal(settled.filter(r=>r.status==='fulfilled').length,1);assert.equal(settled.filter(r=>r.status==='rejected').length,1);});
test('simultaneous bounded checkpoint continuations converge across multiple idle windows',async()=>{const authority=await seed();const stream=db.collection('posBridgeScopes').doc('scope-a').collection('streams').doc('pbi-test');const windows=new Map();for(let sequence=2;sequence<=600;sequence+=1){const windowId=String(Math.floor((sequence-1)/256)).padStart(12,'0');const slots=windows.get(windowId)||{};slots[String((sequence-1)%256)]=`hash-${sequence}`;windows.set(windowId,slots);}for(const [windowId,slots] of windows)await stream.collection('sequenceWindows').doc(windowId).set({slots});await stream.set({highestSequenceObserved:600,highestContiguousSequence:0,uniqueSequencesObserved:599,uniqueEventsReceived:599,stagedEvents:599,missingSequenceCount:1,checkpointComplete:true,checkpointWorkPending:false,reconciliationStatus:'transport-gaps'});await stageEvent(db,authority,orderEvent());await Promise.all([summary(db,authority),summary(db,authority)]);const final=await summary(db,authority);assert.equal(final.highestContiguousSequence,600);assert.equal(final.checkpointComplete,true);assert.equal(final.checkpointWorkPending,false);assert.equal(final.missingSequenceCount,0);});
test('concurrent late sequence arrivals close the real transport gap safely',async()=>{const authority=await seed();await stageEvent(db,authority,orderEvent());await stageEvent(db,authority,orderEvent({eventId:'e3',eventType:'order.updated',sourceEntityVersion:3,sequence:3}));const late=orderEvent({eventId:'e2',eventType:'order.updated',sourceEntityVersion:2,sequence:2});const results=await Promise.all([stageEvent(db,authority,late),stageEvent(db,authority,late)]);assert.equal(new Set(results.map(result=>result.receiptId)).size,1);const final=await summary(db,authority);assert.equal(final.highestContiguousSequence,3);assert.equal(final.reconciliationStatus,'transport-contiguous');});
test('concurrent stale create cannot resurrect a revoked mapping',async()=>{const authority=await seed();const sid=scopeId('rest-a','map-loc','map-ns');await db.collection('posBridgeScopes').doc(sid).set({restaurantId:'rest-a',locationId:'map-loc',sourceNamespaceId:'map-ns'});await db.collection('workspaceMembers').doc('member-a').set({restaurantId:'rest-a',isActive:true});const ctx={uid:'owner-a',userDocId:'owner-a',email:'owner@example.test'};const body={action:'create',expectedRevision:0,restaurantId:'rest-a',locationId:'map-loc',sourceNamespaceId:'map-ns',provider:'86-chaos-pos',entityType:'employee',externalId:'employee-1',internalEntityType:'workspaceMember',internalEntityId:'member-a'};const created=await changeMapping(db,ctx,body);const settled=await Promise.allSettled([changeMapping(db,ctx,{...body,action:'revoke',expectedRevision:created.revision}),changeMapping(db,ctx,body)]);assert.ok(settled.some(result=>result.status==='fulfilled'));const snap=await db.collection('posBridgeScopes').doc(sid).collection('mappings').doc(created.mappingKey).get();assert.equal(snap.data().status,'revoked');assert.equal(snap.data().revision,2);});
}
