'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {MemoryDb}=require('../test-tools/pos-bridge-memory-db.cjs');
const original={...process.env};
const INSTALLATION_ID='pbi_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';

async function setup(){
  const {generateKeyPair,exportJWK,SignJWT}=await import('jose');
  const server=await generateKeyPair('ES256',{extractable:true});
  const client=await generateKeyPair('ES256',{extractable:true});
  const serverPrivate=await exportJWK(server.privateKey);
  const clientPublic=await exportJWK(client.publicKey);
  Object.assign(process.env,{POS_BRIDGE_ENABLED:'true',POS_BRIDGE_ENVIRONMENT:'testing',POS_BRIDGE_TOKEN_ISSUER:'https://86chaos.test/pos-bridge',POS_BRIDGE_TOKEN_AUDIENCE:'86-chaos-pos',POS_BRIDGE_ASSERTION_AUDIENCE:'https://86chaos.test/api/pos-bridge/v1/token',POS_BRIDGE_SIGNING_KEY_ID:'server-k1',POS_BRIDGE_SIGNING_PRIVATE_JWK:JSON.stringify({...serverPrivate,alg:'ES256',kid:'server-k1'}),POS_BRIDGE_SECURITY_EPOCH:'1'});
  const install={posInstallationId:INSTALLATION_ID,restaurantId:'rest-a',locationId:'loc-a',sourceNamespaceId:'ns-a',tenantScopeId:'scope-a',environment:'testing',status:'active',approvedCapabilities:['event.staging','receipt.read','reconciliation.read'],credentialVersion:1,securityEpoch:1,publicKeys:[{kid:'client-k1',status:'active',jwk:{...clientPublic,alg:'ES256',use:'sig',kid:'client-k1'}}]};
  const db=new MemoryDb({[`posBridgeInstallations/${INSTALLATION_ID}`]:install,'restaurants/rest-a':{isActive:true,status:'active'},'posBridgeControl/global':{enabled:true,securityEpoch:1},'posBridgeScopes/scope-a':{restaurantId:'rest-a',locationId:'loc-a',sourceNamespaceId:'ns-a',active:true,locationStatus:'active',activeInstallationId:INSTALLATION_ID}});
  const assertion=async(overrides={})=>{const issuedAt=Number.isInteger(overrides.issuedAt)?overrides.issuedAt:Math.floor(Date.now()/1000);return new SignJWT({environment:'testing',credentialVersion:overrides.credentialVersion??1,token_type:'urn:86chaos:pos-bridge:client-assertion'}).setProtectedHeader({alg:'ES256',kid:overrides.kid||'client-k1',typ:'JWT'}).setIssuer(INSTALLATION_ID).setSubject(INSTALLATION_ID).setAudience(process.env.POS_BRIDGE_ASSERTION_AUDIENCE).setJti(overrides.jti||'jti-1').setIssuedAt(issuedAt).setExpirationTime(issuedAt+60).sign(overrides.privateKey||client.privateKey);};
  return {db,assertion,client,clientPublic};
}
test.after(()=>{for(const key of Object.keys(process.env))if(!(key in original))delete process.env[key];Object.assign(process.env,original);});

test('actual ES256 assertion mints short access token once and verifies current authority',async()=>{
  const {db,assertion}=await setup();const auth=require('./_pos-bridge-auth');const jwt=await assertion();
  const issued=await auth.consumeAssertionAndIssueToken(db,{clientAssertion:jwt,installationId:INSTALLATION_ID,requestedCapabilities:['event.staging']});
  assert.equal(issued.expiresIn,300);const verified=await auth.verifyAccessToken(db,{headers:{authorization:`Bearer ${issued.accessToken}`}}, {requiredCapability:'event.staging'});
  assert.equal(verified.installation.restaurantId,'rest-a');assert.deepEqual(verified.capabilities,['event.staging']);
  await auth.consumeAssertionAndIssueToken(db,{clientAssertion:await assertion({jti:'jti-2'}),installationId:INSTALLATION_ID});
  assert.equal([...db.docs.keys()].filter(key=>key.startsWith('posBridgeControl/quota/windows/')).length,1);
  await assert.rejects(()=>auth.consumeAssertionAndIssueToken(db,{clientAssertion:jwt,installationId:INSTALLATION_ID}),e=>e.code==='assertion_replayed');
});
test('token types cannot be confused and invalid signatures do not allocate replay evidence',async()=>{
  const {db}=await setup();const auth=require('./_pos-bridge-auth');
  for(const token of ['firebase-id-token','shift4-access-token','not.a.jwt'])await assert.rejects(()=>auth.consumeAssertionAndIssueToken(db,{clientAssertion:token,installationId:INSTALLATION_ID}),e=>e.code==='invalid_assertion');
  assert.equal([...db.docs.keys()].some(k=>k.startsWith('posBridgeAuthReplays/')),false);
  db.resetOperations();await assert.rejects(()=>auth.consumeAssertionAndIssueToken(db,{clientAssertion:'not.a.jwt',installationId:'../foreign/path'}),e=>e.code==='invalid_assertion');assert.equal(db.operations.reads,0);
});
test('suspension, epoch changes, credential changes and location changes invalidate access',async()=>{
  const auth=require('./_pos-bridge-auth');
  for(const mutation of [d=>d.status='suspended',d=>d.securityEpoch=2,d=>d.credentialVersion=2]){const {db,assertion}=await setup();const issued=await auth.consumeAssertionAndIssueToken(db,{clientAssertion:await assertion(),installationId:INSTALLATION_ID});const current=db.docs.get(`posBridgeInstallations/${INSTALLATION_ID}`);mutation(current);db.docs.set(`posBridgeInstallations/${INSTALLATION_ID}`,current);await assert.rejects(()=>auth.verifyAccessToken(db,{headers:{authorization:`Bearer ${issued.accessToken}`}}),e=>['installation_inactive','authority_changed'].includes(e.code));}
  const {db,assertion}=await setup();const issued=await auth.consumeAssertionAndIssueToken(db,{clientAssertion:await assertion(),installationId:INSTALLATION_ID});db.docs.set('posBridgeScopes/scope-a',{...db.docs.get('posBridgeScopes/scope-a'),locationStatus:'inactive'});await assert.rejects(()=>auth.verifyAccessToken(db,{headers:{authorization:`Bearer ${issued.accessToken}`}}),e=>e.code==='authority_changed');
});
test('verified old key cannot mint after rotation, including same-kid replacement',async()=>{const auth=require('./_pos-bridge-auth');const {generateKeyPair,exportJWK}=await import('jose');for(const sameKid of [false,true]){const {db,assertion}=await setup();const replacement=await generateKeyPair('ES256',{extractable:true});const replacementPublic=await exportJWK(replacement.publicKey);const jwt=await assertion({jti:`rotate-${sameKid}`});const originalRun=db.runTransaction.bind(db);let rotated=false;db.runTransaction=async fn=>{if(!rotated){rotated=true;const install=db.docs.get(`posBridgeInstallations/${INSTALLATION_ID}`);db.docs.set(`posBridgeInstallations/${INSTALLATION_ID}`,{...install,credentialVersion:2,publicKeys:[{kid:sameKid?'client-k1':'client-k2',status:'active',jwk:{...replacementPublic,alg:'ES256',use:'sig',kid:sameKid?'client-k1':'client-k2'}}]});}return originalRun(fn);};await assert.rejects(()=>auth.consumeAssertionAndIssueToken(db,{clientAssertion:jwt,installationId:INSTALLATION_ID}),error=>error.code==='authority_changed');assert.equal(rotated,true,'rotation hook was reached');assert.equal([...db.docs.keys()].some(key=>key.startsWith('posBridgeAuthReplays/')),false);}});
test('assertion fixture derives iat and exp from one integer boundary timestamp',async()=>{const {assertion}=await setup();const {decodeJwt}=await import('jose');const issuedAt=2_000_000_000,payload=decodeJwt(await assertion({jti:'boundary-clock',issuedAt}));assert.equal(payload.iat,issuedAt);assert.equal(payload.exp,issuedAt+60);assert.equal(payload.exp-payload.iat,60);});
test('assertion freshness is rechecked inside issuance transaction',async()=>{const {db,assertion}=await setup();const auth=require('./_pos-bridge-auth');const jwt=await assertion({jti:'delayed-transaction'});const originalRun=db.runTransaction.bind(db);const realNow=Date.now;db.runTransaction=async fn=>{Date.now=()=>realNow()+2*60*1000;try{return await originalRun(fn);}finally{Date.now=realNow;}};await assert.rejects(()=>auth.consumeAssertionAndIssueToken(db,{clientAssertion:jwt,installationId:INSTALLATION_ID}),error=>error.code==='invalid_assertion');assert.equal([...db.docs.keys()].some(key=>key.startsWith('posBridgeAuthReplays/')),false);});
test('tenant deactivation immediately disables machine authority',async()=>{const {db,assertion}=await setup();const auth=require('./_pos-bridge-auth');const issued=await auth.consumeAssertionAndIssueToken(db,{clientAssertion:await assertion(),installationId:INSTALLATION_ID});for(const tenantState of [null,{isActive:false},{disabled:true},{status:'revoked'}]){if(tenantState===null)db.docs.delete('restaurants/rest-a');else db.docs.set('restaurants/rest-a',tenantState);await assert.rejects(()=>auth.verifyAccessToken(db,{headers:{authorization:`Bearer ${issued.accessToken}`}}),error=>error.code==='installation_inactive');db.docs.set('restaurants/rest-a',{isActive:true,status:'active'});}});
test('suspend and resume cannot resurrect an old token; fresh generation can authenticate',async()=>{const {db,assertion}=await setup();const auth=require('./_pos-bridge-auth');const installations=require('./_pos-bridge-installations');const ctx={db,uid:'owner-a',userDocId:'owner-a',email:'owner@example.test',environment:'testing'};const issued=await auth.consumeAssertionAndIssueToken(db,{clientAssertion:await assertion({jti:'before-suspend'}),installationId:INSTALLATION_ID});const suspended=await installations.transitionInstallation(db,ctx,{action:'suspend',restaurantId:'rest-a',posInstallationId:INSTALLATION_ID});assert.equal(suspended.credentialVersion,2);await installations.transitionInstallation(db,ctx,{action:'activate',restaurantId:'rest-a',posInstallationId:INSTALLATION_ID});await assert.rejects(()=>auth.verifyAccessToken(db,{headers:{authorization:`Bearer ${issued.accessToken}`}}),error=>error.code==='authority_changed');const fresh=await auth.consumeAssertionAndIssueToken(db,{clientAssertion:await assertion({jti:'after-resume',credentialVersion:2}),installationId:INSTALLATION_ID});await assert.doesNotReject(()=>auth.verifyAccessToken(db,{headers:{authorization:`Bearer ${fresh.accessToken}`}}));});
