'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {finalGateOutcome}=require('../scripts/86chaos-release-gate/final-gate-outcome.cjs');
const {validateDeviceEvidence}=require('../scripts/86chaos-release-gate/device-evidence.cjs');
const checklist=require('../test-tools/certification/device-acceptance.json');
const passing=()=>({ok:true,outcome:'PASS',runId:'run-current',fullReleaseCertified:true,sourceIdentityValidation:{ok:true},deploymentIdentityValidation:{ok:true},mandatoryGroupValidation:{ok:true},certificationTruth:{ok:true},skipValidation:{ok:true},playwright:{passed:100,failed:0,timedOut:0,unexpected:0,blocked:0}});
const judge=report=>finalGateOutcome(report,{runId:'run-current'});
test('final adjudication accepts a fully certified current run',()=>assert.equal(judge(passing()).ok,true));
test('collector success cannot override missing mandatory device evidence',()=>{const report=passing();report.ok=false;report.outcome='FAIL';report.fullReleaseCertified=false;report.mandatoryGroupValidation={ok:false,failures:['real-device']};assert.equal(judge(report).ok,false);});
test('final adjudication rejects a stale run even when all checks passed',()=>assert.equal(judge({...passing(),runId:'old'}).ok,false));
test('final adjudication fails closed on incomplete report schemas',()=>{for(const value of [null,{}, {ok:true}, {...passing(),playwright:null}])assert.equal(judge(value).ok,false);});
test('browser failure, timeout, unexpected skip or no execution prevents a green launcher',()=>{for(const patch of [{failed:1},{timedOut:1},{unexpected:1},{passed:0},{blocked:1}])assert.equal(judge({...passing(),playwright:{...passing().playwright,...patch}}).ok,false);});
test('identity, skip and certification validators must each pass independently',()=>{for(const key of ['sourceIdentityValidation','deploymentIdentityValidation','mandatoryGroupValidation','certificationTruth','skipValidation'])assert.equal(judge({...passing(),[key]:{ok:false}}).ok,false);assert.equal(judge({...passing(),fullReleaseCertified:false}).ok,false);});
const identity={version:'17.0.86',sourceManifestHash:'a'.repeat(64),commit:'b'.repeat(40)};
const evidence=()=>({ok:true,...identity,device:{serial:'connected-serial',model:'Pixel',androidVersion:'16'},artifact:{sha256:'c'.repeat(64),packageName:'com.example.qa',versionCode:170086},results:checklist.checks.map(check=>({id:check.id,status:'passed',testedAt:'2026-10-10T15:00:00Z',evidence:'Recorded device observations and logcat artifact'}))});
test('device acceptance requires all 16 documented checks',()=>{assert.equal(checklist.checks.length,16);assert.equal(validateDeviceEvidence(evidence(),identity).ok,true);});
test('pending, failed and absent device checks block certification',()=>{for(const status of ['pending','failed','skipped']){const input=evidence();input.results[0].status=status;assert.equal(validateDeviceEvidence(input,identity).ok,false);}const input=evidence();input.results.pop();assert.equal(validateDeviceEvidence(input,identity).ok,false);});
test('device evidence is bound to version, source hash and commit',()=>{for(const key of Object.keys(identity))assert.equal(validateDeviceEvidence({...evidence(),[key]:'stale'},identity).ok,false);});
test('a browser emulation result without physical device identity cannot certify Android',()=>assert.equal(validateDeviceEvidence({...evidence(),device:{}},identity).ok,false));
test('device checks need distinct IDs, observation dates and evidence',()=>{const input=evidence();input.results.push(input.results[0]);assert.equal(validateDeviceEvidence(input,identity).ok,false);for(const patch of [{evidence:''},{testedAt:'invalid'}]){const input=evidence();Object.assign(input.results[0],patch);assert.equal(validateDeviceEvidence(input,identity).ok,false);}});
test('device results must identify the installed Android artifact',()=>{for(const patch of [{sha256:''},{packageName:''},{versionCode:null}]){const input=evidence();Object.assign(input.artifact,patch);assert.equal(validateDeviceEvidence(input,identity).ok,false);}assert.equal(validateDeviceEvidence(null,identity).ok,false);});
