'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
function response(){return{statusCode:0,payload:null,status(value){this.statusCode=value;return this;},json(value){this.payload=value;return this;}};}
function makeDb(){const rows=new Map(),metrics={transactions:0,writes:0};const db={metrics,collection(name){return{doc(id=`generated_${rows.size+1}`){const path=`${name}/${id}`;return{path,id,async get(){const value=rows.get(path);return{exists:value!==undefined,data:()=>value,ref:this};}};}};},async runTransaction(fn){metrics.transactions+=1;const tx={async get(ref){return ref.get();},set(ref,value,{merge}={}){metrics.writes+=1;rows.set(ref.path,merge?{...(rows.get(ref.path)||{}),...value}:value);},create(ref,value){metrics.writes+=1;if(rows.has(ref.path))throw new Error('exists');rows.set(ref.path,value);},delete(ref){metrics.writes+=1;rows.delete(ref.path);}};return fn(tx);}};return db;}
function loadHandler(db){const chaosPath=require.resolve('./_chaos-admin.js'),original=require.cache[chaosPath];require.cache[chaosPath]={id:chaosPath,filename:chaosPath,loaded:true,exports:{initAdmin:()=>({firestore:()=>db}),readBody:async req=>req.body,clean:value=>String(value||'').trim(),authorize:async()=>({ok:true,uid:'owner',email:'owner@example.invalid',restaurantId:'tenant-a',permissions:{team:true},user:{isOwner:true},db,app:{}}),writeAudit:async()=>{},requireAppCheckIfEnforced:async()=>({ok:true}),requireMfaIfEnforced:()=>({ok:true})}};delete require.cache[require.resolve('./safe-write.js')];const handler=require('./safe-write.js');return()=>{delete require.cache[require.resolve('./safe-write.js')];if(original)require.cache[chaosPath]=original;else delete require.cache[chaosPath];};}
test('ACTUAL HANDLER denies authority and publication injection with zero mutation while allowing contracted task create',async()=>{const db=makeDb(),restore=loadHandler(db),handler=require('./safe-write.js');try{for(const body of [
  {action:'add',collectionName:'tasks',restaurantId:'tenant-a',data:{restaurantId:'tenant-a',title:'x',isSuperAdmin:true}},
  {action:'add',collectionName:'tasks',restaurantId:'tenant-a',data:{restaurantId:'tenant-a',systemAccess:{superAdmin:true}}},
  {action:'set',collectionName:'schedulePublishOperations',docId:'forged',restaurantId:'tenant-a',data:{restaurantId:'tenant-a',status:'complete',generation:99,leaseToken:'forged'}}
]){const before={...db.metrics},res=response();await handler({method:'POST',headers:{},body},res);assert.equal(res.statusCode,403);assert.equal(db.metrics.writes,before.writes);}
  const allowed=response();await handler({method:'POST',headers:{},body:{action:'add',collectionName:'tasks',restaurantId:'tenant-a',data:{restaurantId:'tenant-a',title:'Allowed task'}}},allowed);assert.equal(allowed.statusCode,200);assert.equal(db.metrics.writes,1);
}finally{restore();}});
