'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
function response(){return{statusCode:0,payload:null,status(value){this.statusCode=value;return this;},json(value){this.payload=value;return this;}};}
function makeDb(){const rows=new Map(),metrics={transactions:0,writes:0};const db={rows,metrics,collection(name){return{doc(id=`generated_${rows.size+1}`){const path=`${name}/${id}`;return{path,id,async get(){const value=rows.get(path);return{exists:value!==undefined,data:()=>value,ref:this};}};}};},async runTransaction(fn){metrics.transactions+=1;const tx={async get(ref){return ref.get();},set(ref,value,{merge}={}){metrics.writes+=1;rows.set(ref.path,merge?{...(rows.get(ref.path)||{}),...value}:value);},create(ref,value){metrics.writes+=1;if(rows.has(ref.path))throw new Error('exists');rows.set(ref.path,value);},delete(ref){metrics.writes+=1;rows.delete(ref.path);}};return fn(tx);}};return db;}
function loadHandler(db){const chaosPath=require.resolve('./_chaos-admin.js'),original=require.cache[chaosPath];require.cache[chaosPath]={id:chaosPath,filename:chaosPath,loaded:true,exports:{initAdmin:()=>({firestore:()=>db}),readBody:async req=>req.body,clean:value=>String(value||'').trim(),authorize:async()=>({ok:true,uid:'owner',email:'owner@example.invalid',restaurantId:'tenant-a',permissions:{team:true},user:{isOwner:true},db,app:{}}),writeAudit:async()=>{},requireAppCheckIfEnforced:async()=>({ok:true}),requireMfaIfEnforced:()=>({ok:true})}};delete require.cache[require.resolve('./safe-write.js')];const handler=require('./safe-write.js');return()=>{delete require.cache[require.resolve('./safe-write.js')];if(original)require.cache[chaosPath]=original;else delete require.cache[chaosPath];};}
test('ACTUAL HANDLER denies authority and publication injection with zero mutation while allowing contracted task create',async()=>{const db=makeDb(),restore=loadHandler(db),handler=require('./safe-write.js');try{for(const body of [
  {action:'add',collectionName:'tasks',restaurantId:'tenant-a',data:{restaurantId:'tenant-a',title:'x',isSuperAdmin:true}},
  {action:'add',collectionName:'tasks',restaurantId:'tenant-a',data:{restaurantId:'tenant-a',systemAccess:{superAdmin:true}}},
  {action:'set',collectionName:'schedulePublishOperations',docId:'forged',restaurantId:'tenant-a',data:{restaurantId:'tenant-a',status:'complete',generation:99,leaseToken:'forged'}}
]){const before={...db.metrics},res=response();await handler({method:'POST',headers:{},body},res);assert.equal(res.statusCode,403);assert.equal(db.metrics.writes,before.writes);}
  const allowed=response();await handler({method:'POST',headers:{},body:{action:'add',collectionName:'tasks',restaurantId:'tenant-a',data:{restaurantId:'tenant-a',title:'Allowed task'}}},allowed);assert.equal(allowed.statusCode,200);assert.equal(db.metrics.writes,1);
}finally{restore();}});
test('ACTUAL MODULE waste update/delete remain bound to canonical item, revision, and request intent',async()=>{const db=makeDb(),{mutateWaste}=require('./safe-write.js')._test;db.rows.set('inventoryItems/item-a',{restaurantId:'tenant-a',currentStock:8,revision:3});db.rows.set('inventoryItems/item-b',{restaurantId:'tenant-a',currentStock:100,revision:7});db.rows.set('wasteLogs/log-a',{restaurantId:'tenant-a',workspaceId:'tenant-a',itemId:'item-a',stockDeducted:2,revision:1});const base={restaurantId:'tenant-a',actor:'manager',nowIso:'2026-09-18T12:00:00.000Z'};const wrongWrites=db.metrics.writes;await assert.rejects(()=>mutateWaste(db,{...base,action:'waste-update',body:{operationId:'waste_wrong_item_0001',docId:'log-a',expectedRevision:1,data:{itemId:'item-b',stockDeducted:3}}}),error=>error.code==='waste_item_mismatch');assert.equal(db.metrics.writes,wrongWrites);assert.equal(db.rows.get('inventoryItems/item-a').currentStock,8);assert.equal(db.rows.get('inventoryItems/item-b').currentStock,100);assert.equal(db.rows.get('wasteLogs/log-a').itemId,'item-a');await assert.rejects(()=>mutateWaste(db,{...base,action:'waste-delete',body:{operationId:'waste_stale_delete_1',docId:'log-a',expectedRevision:0,data:{itemId:'item-a'}}}),error=>error.code==='stale_waste_record');const request={operationId:'waste_update_valid_1',docId:'log-a',expectedRevision:1,data:{itemId:'item-a',stockDeducted:3,reason:'updated'}};const updated=await mutateWaste(db,{...base,action:'waste-update',body:request});assert.equal(updated.currentStock,7);assert.equal(db.rows.get('wasteLogs/log-a').revision,2);const retry=await mutateWaste(db,{...base,action:'waste-update',body:request});assert.equal(retry.status,'idempotent');const beforeMismatch=db.metrics.writes;await assert.rejects(()=>mutateWaste(db,{...base,action:'waste-update',body:{...request,data:{...request.data,stockDeducted:4}}}),error=>error.code==='operation_mismatch');assert.equal(db.metrics.writes,beforeMismatch);assert.equal(db.rows.get('inventoryItems/item-a').currentStock,7);await mutateWaste(db,{...base,action:'waste-delete',body:{operationId:'waste_delete_valid_1',docId:'log-a',expectedRevision:2,data:{itemId:'item-a'}}});assert.equal(db.rows.get('inventoryItems/item-a').currentStock,10);assert.equal(db.rows.has('wasteLogs/log-a'),false);});
test('generic contracts deny Daily Close and independent waste writes and require stock operations',()=>{const api=require('./safe-write.js')._test;assert.throws(()=>api.assertGenericContract('sales','update'),error=>error.code==='generic_write_contract_denied');assert.throws(()=>api.assertGenericContract('wasteLogs','update'),error=>error.code==='generic_write_contract_denied');assert.throws(()=>api.assertPayloadAllowed('inventoryItems',{currentStock:12},'update'),error=>error.code==='inventory_operation_required');assert.doesNotThrow(()=>api.assertPayloadAllowed('inventoryItems',{name:'Renamed'},'update'));});
test('ACTUAL MODULE stock set is revision-guarded, finite, and request-intent idempotent',async()=>{const db=makeDb(),{mutateInventoryStock}=require('./safe-write.js')._test,base={restaurantId:'tenant-a',actor:'manager',nowIso:'2026-09-18T12:00:00.000Z'};db.rows.set('inventoryItems/item-a',{restaurantId:'tenant-a',currentStock:8,revision:3,name:'A'});const request={operationId:'inventory_stock_0001',expectedRevision:3,data:{itemId:'item-a',currentStock:12,pendingQty:0}};const committed=await mutateInventoryStock(db,{...base,body:request});assert.equal(committed.status,'committed');assert.equal(db.rows.get('inventoryItems/item-a').currentStock,12);assert.equal(db.rows.get('inventoryItems/item-a').revision,4);const retry=await mutateInventoryStock(db,{...base,body:request});assert.equal(retry.status,'idempotent');const before=db.metrics.writes;await assert.rejects(()=>mutateInventoryStock(db,{...base,body:{...request,data:{...request.data,currentStock:13}}}),error=>error.code==='operation_mismatch');assert.equal(db.metrics.writes,before);await assert.rejects(()=>mutateInventoryStock(db,{...base,body:{operationId:'inventory_stock_0002',expectedRevision:3,data:{itemId:'item-a',currentStock:9}}}),error=>error.code==='stale_inventory_item');await assert.rejects(()=>mutateInventoryStock(db,{...base,body:{operationId:'inventory_stock_0003',expectedRevision:4,data:{itemId:'item-a',currentStock:Infinity}}}),error=>error.code==='invalid_inventory_quantity');assert.equal(db.rows.get('inventoryItems/item-a').currentStock,12);});
