'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const core=require('./_schedule-publish-core.cjs');const {buildCanonicalServerPlan}=core;const {LIMITS}=require('./_pos-bridge-config');
const roleRevision=roles=>`roles-v1|${roles.map(core.normalizeRole).sort((a,b)=>a.id.localeCompare(b.id)).map(role=>`${role.id}:${role.revision}:${role.archived?1:0}:${core.clean(role.name).toLowerCase()}:${role.previousNames.map(name=>core.clean(name).toLowerCase()).sort().join(',')}`).join('|')||'empty'}`;
const evidence=(shift,roles)=>{const resolved=core.resolveRole(shift,roles),person=shift._employeeResolution?.person||null,expected=core.expectedFingerprint(shift,resolved,person),{contentDigest,...state}=expected;return{id:shift.id,contentDigest,state};};
test('role and publication planner boundaries remain complete above 100 roles and at 5,000 shifts',()=>{const roles=Array.from({length:101},(_,i)=>({id:`role-${i}`,name:`Configured ${i}`,revision:1}));const shifts=Array.from({length:5000},(_,i)=>{const employeeId=`employee-${i}`;return{id:`shift-${String(i).padStart(4,'0')}`,restaurantId:'tenant',date:'2026-09-18',employeeId,rosterRoleId:`role-${i%101}`,revision:1,updatedAt:'fixed',_employeeResolution:{ok:true,person:{id:employeeId,employeeId,scheduleUserId:employeeId,rosterUserId:employeeId}}};});const expectedShifts=shifts.map(row=>evidence(row,roles));const plan=buildCanonicalServerPlan({restaurantId:'tenant',operationId:'operation_scale_123456',dayKeys:['2026-09-18'],allRoles:true,roles,shifts,expectedShifts,roleConfigurationRevision:roleRevision(roles)});assert.equal(plan.candidates.length,5000);assert.equal(plan.affectedRoleIds.length,101);assert.equal(plan.affectedEmployeeIds.length,5000);});
test('zero configured roles is safe only when no legacy role-linked shifts need publication',()=>{const empty=buildCanonicalServerPlan({restaurantId:'tenant',operationId:'operation_empty_roles_1',dayKeys:['2026-09-18'],allRoles:true,roles:[],shifts:[],expectedShifts:[],roleConfigurationRevision:'roles-v1|empty'});assert.equal(empty.candidates.length,0);assert.throws(()=>buildCanonicalServerPlan({restaurantId:'tenant',operationId:'operation_empty_roles_2',dayKeys:['2026-09-18'],allRoles:true,roles:[],shifts:[{id:'legacy',restaurantId:'tenant',date:'2026-09-18',role:'Legacy'}],expectedShifts:[],roleConfigurationRevision:'roles-v1|empty'}),error=>error.code==='unresolved_role_identity');});
test('POS boundary limits remain explicit and mapping/capacity listings report incompleteness',()=>{assert.deepEqual({batch:LIMITS.maxBatchEvents,page:LIMITS.maxPageSize,manifest:LIMITS.maxManifestEntries,sequence:LIMITS.sequenceWindowSize,ahead:LIMITS.maxAheadOfContiguous},{batch:20,page:200,manifest:200,sequence:256,ahead:4096});const mappings=fs.readFileSync(path.join(__dirname,'pos-bridge/v1/mappings.js'),'utf8');const maintenance=fs.readFileSync(path.join(__dirname,'_pos-bridge-maintenance.js'),'utf8');assert.match(mappings,/limit\+1/);assert.match(mappings,/complete:!hasMore/);assert.match(maintenance,/incomplete/);});
test('calendar date keys survive DST, leap-day, month and year boundaries without UTC conversion',()=>{const dates=['2026-03-08','2026-11-01','2028-02-29','2026-12-31','2027-01-01'];for(const date of dates)assert.match(date,/^\d{4}-\d{2}-\d{2}$/);const roles=[{id:'r',name:'Role'}];for(const date of dates){const shift={id:`s-${date}`,restaurantId:'tenant',date,employeeId:'e',rosterRoleId:'r',revision:0,updatedAt:'',_employeeResolution:{ok:true,person:{id:'e',employeeId:'e',scheduleUserId:'e',rosterUserId:'e'}}};const plan=buildCanonicalServerPlan({restaurantId:'tenant',operationId:`operation_${date.replace(/-/g,'')}_x`,dayKeys:[date],allRoles:true,roles,shifts:[shift],expectedShifts:[evidence(shift,roles)],roleConfigurationRevision:roleRevision(roles)});assert.deepEqual(plan.affectedDates,[date]);}});
test('cost baselines cannot be silently overwritten during certification',()=>{const baseline=require('../test-tools/certification/cost-performance-baselines.json');assert.equal(baseline.automaticOverwrite,false);assert.equal(baseline.status,'CAPTURE_REQUIRED_ON_EXACT_DEPLOYED_CANDIDATE');assert.equal(baseline.surfaces.length,9);});
