'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const core=require('./_schedule-publish-core.cjs');const service=require('./_schedule-publish-service.cjs');const route=require('./schedule-publish.js');
const roles=[{id:'r1',name:'Grill',revision:2,previousNames:['Line']},{id:'r2',name:'Bar',revision:1,previousNames:[]}];
const roleRevision='roles-v1|r1:2:0:grill:line|r2:1:0:bar:';
const people={e1:{id:'e1',scheduleUserId:'e1',employeeId:'e1',rosterUserId:'e1',userId:'e1',authUid:'e1',name:'Employee One',email:'one@example.invalid'},e2:{id:'e2',scheduleUserId:'e2',employeeId:'e2',rosterUserId:'e2',userId:'e2',authUid:'e2',name:'Employee Two',email:'two@example.invalid'}};
const shifts=[{id:'s1',restaurantId:'tenant',date:'2026-09-18',scheduleDateKey:'2026-09-18',employeeId:'e1',role:'Line',startTime:'09:00',endTime:'17:00',revision:3,updatedAt:'one',_employeeResolution:{ok:true,person:people.e1}},{id:'s2',restaurantId:'tenant',date:'2026-09-18',scheduleDateKey:'2026-09-18',employeeId:'e2',rosterRoleId:'r2',rosterRoleNameSnapshot:'Bar',startTime:'10:00',endTime:'18:00',revision:1,updatedAt:'two',_employeeResolution:{ok:true,person:people.e2}}];
function evidence(shift){const role=core.resolveRole(shift,roles),person=shift._employeeResolution.person,expected=core.expectedFingerprint(shift,role,person);const {contentDigest,...state}=expected;return{id:shift.id,contentDigest,state};}
function build(overrides={}){return core.buildCanonicalServerPlan({restaurantId:'tenant',operationId:'operation_1234567890',dayKeys:['2026-09-18'],selectedRoleIds:['r1'],allRoles:false,roles,shifts,expectedShifts:[evidence(shifts[0])],roleConfigurationRevision:roleRevision,actor:{uid:'manager'},...overrides});}
test('ACTUAL MODULE confirmed plan and executed candidate set are identical',()=>{const plan=build();assert.deepEqual(plan.candidates.map(row=>row.id),plan.backupScope?.shiftIds||plan.candidates.map(row=>row.id));assert.deepEqual(plan.candidates.map(row=>row.id),['s1']);assert.equal(plan.writeCount,1);assert.deepEqual(plan.affectedEmployeeIds,['e1']);assert.match(plan.planDigest,/^[a-f0-9]{64}$/);});
test('empty or broader evidence, stale role configuration, and changed content fail closed',()=>{assert.throws(()=>build({expectedShifts:[]}),/candidate query is incomplete/i);assert.throws(()=>build({roleConfigurationRevision:'stale'}),error=>error.code==='role_configuration_changed');const changed={...shifts[0],date:'2026-09-19'};assert.equal(core.fingerprintsMatch(changed,core.expectedFingerprint(shifts[0],core.resolveRole(shifts[0],roles),people.e1),core.resolveRole(changed,roles),people.e1),false);});
test('unchanged published shifts are neither written nor notified',()=>{const canonical=core.canonicalEmployeeIdentity(people.e2,shifts[1]),published={...shifts[1],...canonical,isPublished:true,published:true,status:'published',publishStatus:'published',scheduleId:'schedule-existing'};const plan=core.buildCanonicalServerPlan({restaurantId:'tenant',operationId:'operation_unchanged_123',dayKeys:['2026-09-18'],allRoles:true,roles,shifts:[published],expectedShifts:[],roleConfigurationRevision:roleRevision});assert.deepEqual(plan.candidates,[]);assert.deepEqual(plan.unchangedShiftIds,['s2']);assert.deepEqual(plan.affectedEmployeeIds,[]);});
test('unresolved linked employee stays draft while explicit open shift remains distinguishable',()=>{const broken={...shifts[0],id:'broken',_employeeResolution:{ok:false,reason:'unresolved-durable-employee-reference'}},open={...shifts[0],id:'open',employeeId:'',isOpenShift:true,_employeeResolution:{ok:false,reason:'missing'}};const openEvidence=(()=>{const expected=core.expectedFingerprint(open,core.resolveRole(open,roles),null),{contentDigest,...state}=expected;return{id:'open',contentDigest,state};})();const plan=core.buildCanonicalServerPlan({restaurantId:'tenant',operationId:'operation_open_12345',dayKeys:['2026-09-18'],selectedRoleIds:['r1'],allRoles:false,roles,shifts:[broken,open],expectedShifts:[openEvidence],roleConfigurationRevision:roleRevision});assert.deepEqual(plan.candidates.map(row=>row.id),['open']);assert.equal(plan.candidates[0].intentionalOpen,true);assert.deepEqual(plan.unresolvedEmployees,[{shiftId:'broken',reason:'unresolved-durable-employee-reference'}]);});
test('request digest binds meaningful confirmed state and same operation cannot change plan',()=>{const body={restaurantId:'tenant',operationId:'operation_1234567890',dayKeys:['2026-09-18'],selectedRoleIds:['r1'],allRoles:false,roleConfigurationRevision:roleRevision,expectedShifts:[evidence(shifts[0])]};const a=service.requestDigest(body),b=service.requestDigest({...body,expectedShifts:[{...body.expectedShifts[0],state:{...body.expectedShifts[0].state,startTime:'11:00'}}]});assert.notEqual(a,b);});
test('ACTUAL MODULE verification binds per-shift commit generation and published content',()=>{const plan=build(),row=plan.candidates[0],data={...shifts[0],...row.desiredEmployeeIdentity,restaurantId:'tenant',workspaceId:'tenant',date:row.date,scheduleDateKey:row.date,rosterRoleId:row.rosterRoleId,rosterRoleNameSnapshot:row.rosterRoleNameSnapshot,isPublished:true,published:true,status:'published',publishStatus:'published',scheduleId:`schedule_${plan.operationId}`,publishOperationId:plan.operationId,publishGeneration:4,revision:4,updatedAt:'committed-at'};const evidenceRow=service.publishedCommitEvidence(data,row,plan,4);assert.equal(service.publishedStateMatches(data,row,plan,evidenceRow),true);assert.equal(service.publishedStateMatches({...data,startTime:'11:00'},row,plan,evidenceRow),false);assert.equal(service.publishedStateMatches({...data,revision:5},row,plan,evidenceRow),false);assert.equal(service.publishedStateMatches({...data,updatedAt:'changed'},row,plan,evidenceRow),false);assert.equal(service.publishedStateMatches({...data,publishGeneration:5},row,plan,evidenceRow),false);});
test('route rejects unsupported method, compressed bodies, oversized declarations and malformed JSON',()=>{const makeRes=()=>({statusCode:0,payload:null,status(n){this.statusCode=n;return this;},json(p){this.payload=p;return this;}});let res=makeRes();route({method:'GET',headers:{}},res);assert.equal(res.statusCode,405);assert.throws(()=>route._test.parseBody({headers:{'content-encoding':'gzip'},body:'{}'}),e=>e.statusCode===415);assert.throws(()=>route._test.parseBody({headers:{'content-length':String(route._test.MAX_BODY_BYTES+1)},body:'{}'}),e=>e.statusCode===413);assert.throws(()=>route._test.parseBody({headers:{},body:'{' }),e=>e.statusCode===400);assert.throws(()=>service.validateRequest({restaurantId:'tenant',operationId:'short',dayKeys:['2026-09-18'],expectedShifts:[],roleConfigurationRevision:roleRevision}),/valid tenant/i);});
