'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const admin=require('firebase-admin');const core=require('./_schedule-publish-core.cjs');const service=require('./_schedule-publish-service.cjs');
if(!process.env.FIRESTORE_EMULATOR_HOST){test('schedule publication concurrency requires the Firestore emulator',{skip:'Run npm run test:schedule-publish:emulator; certification requires it.'},()=>{});}else{
  const projectId=process.env.GCLOUD_PROJECT||'demo-schedule-publish';if(!/^demo-|^test-/.test(projectId))throw new Error('Schedule publication emulator tests refuse non-demo projects.');const app=admin.apps.find(row=>row.name==='schedule-publish-emulator')||admin.initializeApp({projectId},'schedule-publish-emulator'),db=app.firestore(),collections=['schedulePublishOperations','schedulePublishLeases','shifts','roles','timeOffRequests','users','workspaceMembers'];
  async function clear(){for(const name of collections){const snap=await db.collection(name).get();await Promise.all(snap.docs.map(doc=>db.recursiveDelete(doc.ref)));}}test.beforeEach(clear);test.after(clear);
  const roles=[{id:'role-a',name:'Configured A',revision:1,previousNames:[]}],roleRevision='roles-v1|role-a:1:0:configured a:';
  const person={id:'employee-a',scheduleUserId:'employee-a',employeeId:'employee-a',rosterUserId:'employee-a',userId:'employee-a',authUid:'employee-a',name:'Employee A',email:'a@example.invalid'};
  const shift={id:'shift-a',restaurantId:'rest-a',date:'2026-09-18',scheduleDateKey:'2026-09-18',employeeId:'employee-a',rosterRoleId:'role-a',rosterRoleNameSnapshot:'Configured A',startTime:'09:00',endTime:'17:00',revision:1,updatedAt:'v1',_employeeResolution:{ok:true,person}};
  function evidence(row=shift){const expected=core.expectedFingerprint(row,core.resolveRole(row,roles),row._employeeResolution?.person||null),{contentDigest,...state}=expected;return{id:row.id,contentDigest,state};}
  function plan(operationId='operation_aaaaaaaaaaaa'){return core.buildCanonicalServerPlan({restaurantId:'rest-a',operationId,dayKeys:['2026-09-18'],allRoles:true,roles,shifts:[shift],expectedShifts:[evidence()],roleConfigurationRevision:roleRevision,actor:{uid:'manager-a'}});}
  test('FIREBASE EMULATOR overlapping operation is denied and every post-takeover transition is fenced',async()=>{const stored={...shift};delete stored.id;delete stored._employeeResolution;await db.collection('shifts').doc('shift-a').set(stored);const ctxA={uid:'manager-a'},ctxB={uid:'manager-b'},firstPlan=plan(),first=await service.acquireOperation(db,ctxA,firstPlan,new Date(),'intent-a');await assert.rejects(()=>service.acquireOperation(db,ctxB,plan('operation_bbbbbbbbbbbb'),new Date(),'intent-b'),error=>error.code==='publish_in_progress');const expired='2000-01-01T00:00:00.000Z';await Promise.all([first.ref.set({leaseExpiresAt:expired},{merge:true}),first.tenantLeaseRef.set({leaseExpiresAt:expired},{merge:true})]);const second=await service.acquireOperation(db,ctxB,plan('operation_bbbbbbbbbbbb'),new Date(),'intent-b');await assert.rejects(()=>service.commitChunk(db,first,firstPlan,firstPlan.candidates,0,ctxA,new Date()),error=>error.code==='stale_publish_fence');await assert.rejects(()=>service.verifyCommitted(db,first,firstPlan,['shift-a'],new Date()),error=>error.code==='stale_publish_fence');await assert.rejects(()=>service.finalizeOperation(db,first,firstPlan,{}, {},new Date()),error=>error.code==='stale_publish_fence');const lease=(await second.tenantLeaseRef.get()).data();assert.equal(lease.operationId,'operation_bbbbbbbbbbbb');assert.equal(lease.status,'active');});
  test('FIREBASE EMULATOR exact employee/date pairs prevent cross-product time-off mutation and recipients are canonical',async()=>{await Promise.all([db.collection('roles').doc('role-a').set({restaurantId:'rest-a',name:'Configured A',revision:1,previousNames:[]}),db.collection('shifts').doc('shift-a').set(Object.fromEntries(Object.entries(shift).filter(([key])=>!['id','_employeeResolution'].includes(key)))),db.collection('timeOffRequests').doc('exact').set({restaurantId:'rest-a',date:'2026-09-18',employeeId:'employee-a',status:'approved'}),db.collection('timeOffRequests').doc('cross-product').set({restaurantId:'rest-a',date:'2026-09-19',employeeId:'employee-a',status:'approved'}),db.collection('users').doc('employee-a').set({restaurantId:'rest-a',isActive:true,fcmToken:'token-a',email:'a@example.invalid'}),db.collection('workspaceMembers').doc('employee-a_rest-a').set({restaurantId:'rest-a',employeeId:'employee-a',userId:'employee-a',isActive:true,email:'a@example.invalid'})]);let sent=[];const messaging={async sendEachForMulticast(payload){sent.push(...payload.tokens);return{responses:payload.tokens.map(()=>({success:true}))};}},body={restaurantId:'rest-a',operationId:'operation_scope_123456',dayKeys:['2026-09-18'],allRoles:true,selectedRoleIds:[],roleConfigurationRevision:roleRevision,expectedShifts:[evidence()],restaurantName:'Fixture'};const result=await service.executeSchedulePublish({db,ctx:{uid:'manager-a',user:{name:'Manager'}},body,messaging,clock:()=>new Date('2026-09-18T12:00:00.000Z')});assert.equal(result.status,'complete');assert.deepEqual(sent,['token-a']);assert.equal((await db.collection('timeOffRequests').doc('exact').get()).data().archived,true);assert.equal((await db.collection('timeOffRequests').doc('cross-product').get()).data().archived,undefined);});
  test('FIREBASE EMULATOR provider timeout is ambiguous and cannot roll back publication',async()=>{await Promise.all([db.collection('roles').doc('role-a').set({restaurantId:'rest-a',name:'Configured A',revision:1,previousNames:[]}),db.collection('shifts').doc('shift-a').set(Object.fromEntries(Object.entries(shift).filter(([key])=>!['id','_employeeResolution'].includes(key)))),db.collection('users').doc('employee-a').set({restaurantId:'rest-a',isActive:true,fcmToken:'token-a',email:'a@example.invalid'}),db.collection('workspaceMembers').doc('employee-a_rest-a').set({restaurantId:'rest-a',employeeId:'employee-a',userId:'employee-a',isActive:true,email:'a@example.invalid'})]);const body={restaurantId:'rest-a',operationId:'operation_notify_12345',dayKeys:['2026-09-18'],allRoles:true,roleConfigurationRevision:roleRevision,expectedShifts:[evidence()]},messaging={async sendEachForMulticast(){throw new Error('provider sentinel');}};const result=await service.executeSchedulePublish({db,ctx:{uid:'manager-a'},body,messaging,clock:()=>new Date('2026-09-18T12:00:00.000Z')});assert.equal(result.status,'complete');assert.equal(result.notificationState.status,'ambiguous');assert.equal((await db.collection('shifts').doc('shift-a').get()).data().isPublished,true);assert.doesNotMatch(JSON.stringify(result),/provider sentinel/);});
}
