'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const { redactText,redactDiagnostic,sanitizedCorrelationId,classifyDiagnosticError,buildBackupRecoveryStatus,buildPermissionBoundaryDiagnostics,buildSecurityMaturityReport }=require('./_security-maturity.cjs');
const { buildFirebaseCostDiagnostics }=require('../src/core/firebaseCostDiagnostics.cjs');

test('security diagnostics redact tokens passwords API keys authorization cookies OAuth and private keys',()=>{const value=redactDiagnostic({token:'eyJabcdefgh.abcdefgh.abcdefgh',password:'hunter2',apiKey:'AIzaabcdefghijklmnopqrstuvwxyz123456',authorization:'Bearer abc.def.ghi',cookie:'session=x',oauthCredentials:{clientSecret:'secret'},serviceAccount:{private_key:'-----BEGIN PRIVATE KEY-----\nabc\n-----END PRIVATE KEY-----'}});const encoded=JSON.stringify(value);for(const secret of ['hunter2','AIzaabcdefghijklmnopqrstuvwxyz123456','abc.def.ghi','session=x','BEGIN PRIVATE KEY'])assert.doesNotMatch(encoded,new RegExp(secret.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))});
test('redacted plain-text errors preserve action while removing credentials',()=>{const text=redactText('authorization=abc123 password=hunter2 Bearer one.two.three');assert.match(text,/authorization=\[redacted\]/i);assert.doesNotMatch(text,/hunter2|one\.two\.three/)});
test('correlation IDs are sanitized and secret-like IDs are hashed',()=>{assert.equal(sanitizedCorrelationId('request-123456'),'request-123456');assert.match(sanitizedCorrelationId('Bearer secret value'),/^corr_[a-f0-9]{16}$/)});
test('forensics error categories identify authorization tenant timeout and release identity failures',()=>{assert.equal(classifyDiagnosticError('permission denied'),'authorization');assert.equal(classifyDiagnosticError('workspace tenant mismatch'),'tenant-boundary');assert.equal(classifyDiagnosticError('request timed out'),'timeout');assert.equal(classifyDiagnosticError('stale deployment commit'),'release-identity')});
test('admin permission boundaries keep wages and destructive workspace controls owner-only',()=>{const owner=buildPermissionBoundaryDiagnostics({role:'owner',restaurantId:'r1'}),manager=buildPermissionBoundaryDiagnostics({role:'manager',restaurantId:'r1'});assert.equal(owner.effective.canViewWages,true);assert.equal(manager.effective.canViewWages,false);assert.equal(manager.effective.canManageTeam,true);assert.equal(owner.tenantIsolationRequired,true)});
test('security maturity reports tenant/environment mismatch without exposing secret values',()=>{const report=buildSecurityMaturityReport({correlationId:'request-123456',caller:{role:'admin',restaurantId:'r1'},expectedFirebaseProject:'chaos-test-d1601',environment:{projectId:'cheers-34b8d',credentialConfigured:true},mfa:{apiEnforcementEnabled:true},appCheck:{status:'valid',enforcedByApi:true},backupStatus:{},oauthStateProtected:true,deploymentIdentityVerified:true});assert.equal(report.environmentIdentity,'mismatch');assert.equal(report.permissionBoundaries.workspaceId,'r1');assert.equal(report.secrets.valuesExposed,false)});
test('missing expected environment identity remains unknown instead of healthy',()=>{const report=buildSecurityMaturityReport({environment:{projectId:'chaos-test-d1601'}});assert.equal(report.environmentIdentity,'unknown');assert.equal(report.checks.find(row=>row.id==='environment').status,'unknown')});
test('backup healthy state requires current successful and verified evidence',()=>{const status=buildBackupRecoveryStatus({status:'success',lastSuccessfulBackupAt:'2026-09-26T10:00:00Z',lastIntegrityStatus:'verified'},new Date('2026-09-26T12:00:00Z'));assert.equal(status.state,'healthy');assert.equal(status.restoreReadiness,'review-ready')});
test('backup failed state keeps a redacted actionable explanation',()=>{const status=buildBackupRecoveryStatus({status:'failed',lastError:'authorization=secret-token backup export failed',lastErrorAt:'2026-09-26T11:00:00Z'},new Date('2026-09-26T12:00:00Z'));assert.equal(status.state,'failed');assert.match(status.failureExplanation,/backup export failed/);assert.doesNotMatch(status.failureExplanation,/secret-token/)});
test('backup unknown state never claims healthy or restore ready',()=>{const status=buildBackupRecoveryStatus({},new Date('2026-09-26T12:00:00Z'));assert.equal(status.state,'unknown');assert.equal(status.healthy,false);assert.equal(status.restoreReadiness,'not-proven');assert.equal(status.destructiveRestoreAutomatic,false)});
test('Firebase listener diagnostics detect duplicates abandoned listeners and excessive reads without customer rows',()=>{const report=buildFirebaseCostDiagnostics({activeListeners:2,writesInitiated:5,writesCompleted:4,skippedNoOpWrites:2,listeners:{a:{collection:'inventoryItems',subscriberCount:2,consumerLabels:['today','today'],listenerCreationCount:2,documentsReceivedInitial:300},b:{collection:'tasks',subscriberCount:0,documentsReceivedInitial:2}}},{readWarningThreshold:100,rtdbKnown:false});assert.equal(report.findings.duplicateListeners.length,1);assert.equal(report.findings.abandonedListeners.length,1);assert.equal(report.findings.highReadQueries.length,1);assert.equal(report.containsCustomerRecords,false);assert.equal(report.rtdb.status,'unknown')});
test('Firebase aggregate diagnostics remain healthy for one shared bounded listener',()=>{const report=buildFirebaseCostDiagnostics({activeListeners:1,listenerReuseCount:2,listeners:{a:{collection:'tasks',subscriberCount:2,consumerLabels:['today','prep'],listenerCreationCount:1,documentsReceivedInitial:20,releasedAt:''}}});assert.equal(report.findings.duplicateListeners.length,0);assert.equal(report.findings.abandonedListeners.length,0);assert.equal(report.status,'healthy')});
