'use strict';
const assert = require('node:assert/strict');
const { test } = require('node:test');
const {
  changeAccountLoginEmail,
  normalizeEmail,
  emailChanged,
  profileEmailPatch,
  membershipEmailPatch,
  classifyAuthEmailError,
  targetIsPrivileged
} = require('./_account-email-change.cjs');

class FakeDocSnap { constructor(ref, data) { this.ref = ref; this.id = ref.id; this._data = data; this.exists = data !== undefined; } data() { return this._data; } }
class FakeDocRef { constructor(db, coll, id) { this.db = db; this.coll = coll; this.id = id; this.path = `${coll}/${id}`; } async get() { return new FakeDocSnap(this, this.db.data[this.coll]?.[this.id]); } }
class FakeQuery { constructor(db, coll, filters = [], n = 50) { this.db = db; this.coll = coll; this.filters = filters; this.n = n; } where(f, op, v) { return new FakeQuery(this.db, this.coll, [...this.filters, [f, op, v]], this.n); } limit(n) { return new FakeQuery(this.db, this.coll, this.filters, n); } async get() { const rows = Object.entries(this.db.data[this.coll] || {}).filter(([, d]) => this.filters.every(([f, op, v]) => op === '==' && d?.[f] === v)).slice(0, this.n).map(([id]) => new FakeDocSnap(new FakeDocRef(this.db, this.coll, id), this.db.data[this.coll][id])); return { empty: rows.length === 0, docs: rows, forEach: cb => rows.forEach(cb) }; } }
class FakeCollection extends FakeQuery { constructor(db, coll) { super(db, coll); this.db = db; this.coll = coll; } doc(id) { return new FakeDocRef(this.db, this.coll, id); } }
class FakeBatch { constructor(db) { this.db = db; this.ops = []; this.fail = false; } set(ref, patch, options) { this.ops.push({ ref, patch, options }); } async commit() { if (this.db.failBatch) throw new Error('batch failed'); for (const op of this.ops) { const curr = this.db.data[op.ref.coll][op.ref.id] || {}; this.db.data[op.ref.coll][op.ref.id] = op.options?.merge ? { ...curr, ...op.patch } : op.patch; } } }
class FakeDb { constructor(data) { this.data = data; this.batches = []; this.failBatch = false; } collection(coll) { this.data[coll] ||= {}; return new FakeCollection(this, coll); } batch() { const b = new FakeBatch(this); this.batches.push(b); return b; } }
class FakeAuth { constructor(users) { this.users = users; this.updateCalls = []; this.revokeCalls = []; this.failUpdate = false; this.failRevoke = false; this.failRollback = false; } async getUser(uid) { const u = this.users[uid]; if (!u) { const e = new Error('not found'); e.code = 'auth/user-not-found'; throw e; } return { ...u }; } async getUserByEmail(email) { const lower = normalizeEmail(email); const u = Object.values(this.users).find(row => normalizeEmail(row.email) === lower); if (!u) { const e = new Error('not found'); e.code = 'auth/user-not-found'; throw e; } return { ...u }; } async updateUser(uid, patch) { this.updateCalls.push({ uid, patch }); if (this.failUpdate && this.updateCalls.length === 1) { const e = new Error('invalid email'); e.code = 'auth/invalid-email'; throw e; } if (this.failRollback && this.updateCalls.length > 1) throw new Error('rollback failed'); Object.assign(this.users[uid], patch); return { ...this.users[uid] }; } async revokeRefreshTokens(uid) { this.revokeCalls.push(uid); if (this.failRevoke) throw new Error('revoke failed'); } }
function base() { const db = new FakeDb({ users: { auth_1: { email: 'old@example.com', emailLower: 'old@example.com', emailLowercase: 'old@example.com', normalizedEmail: 'old@example.com', authEmail: 'old@example.com', restaurantId: 'restaurant_a', isActive: true, memberships: { restaurant_a: { role: 'Cook', email: 'old@example.com', permissions: { prep: true }, wage: 14, isAdmin: false, isOwner: false, restaurantId: 'restaurant_a' } } } }, workspaceMembers: { m1: { userId: 'auth_1', authUid: 'auth_1', restaurantId: 'restaurant_a', email: 'old@example.com', emailLower: 'old@example.com', employeeEmail: 'old@example.com', userEmail: 'old@example.com', isActive: true, role: 'Cook', permissions: { prep: true }, wage: 14 } }, auditLogs: {} }); const auth = new FakeAuth({ auth_1: { uid: 'auth_1', email: 'old@example.com', emailVerified: true } }); return { db, auth, targetRef: db.collection('users').doc('auth_1'), targetUser: db.data.users.auth_1, currentMembership: db.data.workspaceMembers.m1, ctx: { canManageStaff: true, isSuperAdmin: false, restaurantId: 'restaurant_a', callerEmail: 'manager@example.com', restaurant: { id: 'restaurant_a' } } }; }
async function runChange(overrides = {}) { const b = base(); Object.assign(b, overrides); const audits = []; const result = await changeAccountLoginEmail({ db: b.db, auth: b.auth, ctx: b.ctx, targetRef: b.targetRef, targetDocId: b.targetRef.id, targetUid: 'auth_1', targetUser: b.targetUser, currentMembership: b.currentMembership, currentEmail: 'old@example.com', submittedEmail: 'new@example.com', writeAudit: async (action, detail) => audits.push({ action, detail }) }); return { ...b, result, audits }; }

test('unchanged normalized email does not mutate Auth or memberships', async () => {
  const b = base();
  const result = await changeAccountLoginEmail({ db: b.db, auth: b.auth, ctx: b.ctx, targetRef: b.targetRef, targetDocId: 'auth_1', targetUid: 'auth_1', targetUser: b.targetUser, currentMembership: b.currentMembership, currentEmail: 'old@example.com', submittedEmail: ' OLD@example.com ' });
  assert.equal(result.emailChanged, false); assert.equal(b.auth.updateCalls.length, 0); assert.equal(b.auth.revokeCalls.length, 0);
});
test('normal single-workspace employee Auth email updates without password', async () => { const { auth } = await runChange(); assert.deepEqual(auth.updateCalls[0], { uid: 'auth_1', patch: { email: 'new@example.com', emailVerified: false } }); assert.equal('password' in auth.updateCalls[0].patch, false); });
test('duplicate Auth email fails 409 before writes', async () => { const b = base(); b.auth.users.other = { uid: 'other', email: 'new@example.com' }; await assert.rejects(() => runChange(b), /already assigned/); assert.equal(b.auth.updateCalls.length, 0); assert.equal(b.db.batches.length, 0); });
test('invalid email fails before mutations', async () => { const b = base(); await assert.rejects(() => changeAccountLoginEmail({ db: b.db, auth: b.auth, ctx: b.ctx, targetRef: b.targetRef, targetDocId: 'auth_1', targetUid: 'auth_1', targetUser: b.targetUser, currentMembership: b.currentMembership, currentEmail: 'old@example.com', submittedEmail: 'bad' }), /valid email/); assert.equal(b.auth.updateCalls.length, 0); assert.equal(b.db.batches.length, 0); });
test('manager may change ordinary single-workspace employee email', async () => { const { result } = await runChange(); assert.equal(result.emailChanged, true); });
test('regular staff is denied by caller before helper in source contract', () => { assert.equal(emailChanged('a@b.com', 'a@b.com'), false); assert.equal(emailChanged('a@b.com', 'c@b.com'), true); });
test('ordinary manager cannot globally change multi-workspace login email', async () => { const b = base(); b.db.data.workspaceMembers.m2 = { userId: 'auth_1', restaurantId: 'restaurant_b', email: 'old@example.com', isActive: true }; await assert.rejects(() => runChange(b), /multiple workspaces/); assert.equal(b.auth.updateCalls.length, 0); });
test('System Administrator may change ordinary multi-workspace employee email and updates both memberships', async () => { const b = base(); b.ctx.isSuperAdmin = true; b.db.data.workspaceMembers.m2 = { userId: 'auth_1', restaurantId: 'restaurant_b', email: 'old@example.com', emailLower: 'old@example.com', isActive: true }; const out = await runChange(b); assert.equal(out.db.data.workspaceMembers.m1.email, 'new@example.com'); assert.equal(out.db.data.workspaceMembers.m2.email, 'new@example.com'); });
test('owner target is privileged', () => { assert.equal(targetIsPrivileged({ accountOwner: true, email: 'worker@example.com' }, {}, { restaurant: {} }), true); });
test('Super Admin target is privileged', () => { assert.equal(targetIsPrivileged({ isSuperAdmin: true, email: 'admin@example.com' }, {}, { restaurant: {} }), true); });
test('protected root target is privileged', () => { assert.equal(targetIsPrivileged({ email: 'geoffm1985@gmail.com' }, {}, { restaurant: {} }), true); });
test('legacy profile doc ID resolves Auth UID and does not rename profile doc', async () => { const b = base(); b.db.data.users = { 'old@example.com': { ...b.targetUser, authUid: 'auth_1' } }; b.targetRef = b.db.collection('users').doc('old@example.com'); b.targetUser = b.db.data.users['old@example.com']; const out = await runChange(b); assert.equal(out.auth.updateCalls[0].uid, 'auth_1'); assert.ok(out.db.data.users['old@example.com']); assert.equal(out.db.data.users['new@example.com'], undefined); });
test('all membership aliases update and unrelated membership remains untouched', async () => { const b = base(); b.ctx.isSuperAdmin = true; b.db.data.workspaceMembers.m2 = { uid: 'other', restaurantId: 'restaurant_x', email: 'other@example.com', emailLower: 'other@example.com', employeeEmail: 'other@example.com', userEmail: 'other@example.com', isActive: true }; const out = await runChange(b); assert.equal(out.db.data.workspaceMembers.m1.email, 'new@example.com'); assert.equal(out.db.data.workspaceMembers.m1.emailLower, 'new@example.com'); assert.equal(out.db.data.workspaceMembers.m1.employeeEmail, 'new@example.com'); assert.equal(out.db.data.workspaceMembers.m1.userEmail, 'new@example.com'); assert.equal(out.db.data.workspaceMembers.m2.email, 'other@example.com'); });
test('profile aliases and embedded membership email aliases update without changing role or permissions', async () => { const out = await runChange(); const profile = out.db.data.users.auth_1; assert.equal(profile.email, 'new@example.com'); assert.equal(profile.emailLower, 'new@example.com'); assert.equal(profile.emailLowercase, 'new@example.com'); assert.equal(profile.normalizedEmail, 'new@example.com'); assert.equal(profile.authEmail, 'new@example.com'); assert.equal(profile.memberships.restaurant_a.email, 'new@example.com'); assert.equal(profile.memberships.restaurant_a.role, 'Cook'); assert.deepEqual(profile.memberships.restaurant_a.permissions, { prep: true }); });
test('Auth update failure performs zero Firestore writes', async () => { const b = base(); b.auth.failUpdate = true; await assert.rejects(() => runChange(b), /valid email|Firebase Auth/); assert.equal(b.db.batches.length, 0); });
test('Firestore batch failure rolls Auth back to old email and original verification', async () => { const b = base(); b.db.failBatch = true; await assert.rejects(() => runChange(b), /rolled back/); assert.deepEqual(b.auth.updateCalls[1], { uid: 'auth_1', patch: { email: 'old@example.com', emailVerified: true } }); });
test('rollback failure returns explicit safe partial failure metadata', async () => { const b = base(); b.db.failBatch = true; b.auth.failRollback = true; try { await runChange(b); assert.fail('expected rejection'); } catch (err) { assert.equal(err.emailChangePartialFailure, true); assert.equal(err.authEmailMayBeChanged, true); assert.equal('password' in err, false); assert.equal('token' in err, false); } });
test('successful change forces logout and revokes refresh tokens', async () => { const out = await runChange(); assert.equal(out.db.data.users.auth_1.forceLogout, true); assert.equal(out.db.data.users.auth_1.forceLogoutReason, 'staff-email-changed'); assert.deepEqual(out.auth.revokeCalls, ['auth_1']); });
test('session revocation failure keeps identity update successful with warning', async () => { const b = base(); b.auth.failRevoke = true; const out = await runChange(b); assert.equal(out.result.emailChanged, true); assert.equal(out.result.sessionsRevoked, false); assert.match(out.result.sessionWarning, /could not be revoked/i); });
test('audit event includes STAFF_EMAIL_UPDATE without token or password', async () => { const out = await runChange(); assert.equal(out.audits[0].action, 'STAFF_EMAIL_UPDATE'); const txt = JSON.stringify(out.audits[0]); assert.match(txt, /old@example.com/); assert.match(txt, /new@example.com/); assert.doesNotMatch(txt, /password|token/i); });
test('source contract prevents unbounded workspaceMembers full scan', () => { const src = require('node:fs').readFileSync(require('node:path').join(__dirname, '_account-email-change.cjs'), 'utf8'); assert.equal(/collection\('workspaceMembers'\)\.get\(\)/.test(src), false); assert.match(src, /where\(field, '==', value\)/); });
test('profileEmailPatch and membershipEmailPatch are narrow alias-only helpers', () => { const p = profileEmailPatch({ emailLower: 'old@example.com', accountSecurity: { emailVerified: true }, memberships: { a: { email: 'old@example.com', role: 'Cook' } } }, 'new@example.com', 'now'); assert.equal(p.email, 'new@example.com'); assert.equal(p.emailLower, 'new@example.com'); assert.equal(p.accountSecurity.emailVerified, false); assert.equal(p.memberships.a.email, 'new@example.com'); assert.equal(p.memberships.a.role, 'Cook'); const m = membershipEmailPatch({ employeeEmail: 'old@example.com', role: 'Cook' }, 'new@example.com', 'now'); assert.deepEqual(m, { email: 'new@example.com', emailLower: 'new@example.com', employeeEmail: 'new@example.com', updatedAt: 'now' }); });
test('classifyAuthEmailError maps duplicate and invalid email clearly', () => { assert.equal(classifyAuthEmailError({ code: 'auth/email-already-exists' }).status, 409); assert.equal(classifyAuthEmailError({ code: 'auth/invalid-email' }).status, 400); });
